### ISSUE TITLE
Private properties

### ISSUE THREAD

**Issue by LeonardoCardoso** [Juanpe/SkeletonView#1]
You are using many private properties in public properties, thus it throws accessibility level error and it won't build.

![screen shot 2017-11-09 at 13 16 49](https://user-images.githubusercontent.com/1775157/32605096-6853635a-c550-11e7-9d2e-28a431796fe1.png)

**Comment by Juanpe** [comment]
Hi @LeonardoCardoso, are you using **Swift 4**? You can check it in the build settings of the framework.
<img width="499" alt="screen shot 2017-11-09 at 19 59 28" src="https://user-images.githubusercontent.com/1409041/32624318-286a6a20-c589-11e7-94e8-5a9faae72bb7.png">

In Swift 4, the behaviour of "private" keyword has been modified. If you use the "private" keyword, the property will be visible in this file and extension. You don't need use "fileprivate".

Maybe I could create a new branch for Swift 3, ok?

Thanks

**Comment by LeonardoCardoso** [comment]
That's fine.
