### ISSUE TITLE
Skelton view not working in collectionview

### ISSUE THREAD

**Issue by Smiller193** [Juanpe/SkeletonView#103]
⚠️ Please fill out this template when filing an issue.

### What did you do?
Tried to integrate this with collectionView that is embedded in uicollectionviewcell. Implemented the data source and ran prepareSkeleton. Made cell and corresponding views skeletonable that are inside the cell.

### What did you expect to happen?

I expected the skeleton view to appear and then clear itself once the proper info was received to render the cell.

### What happened instead?

The skeletonView is just stuck there

### Steps to reproduce the behavior

1. Create collectionview with x amount of cells
2. embed a collection view in each of the cells to create a side-scrolling layout similar to Netflix
3. Run prepare for skeleton function on embedded collectionview
4. make cell and views inside cell skeletonable
### SkeletonView Environment

**SkeletonView version:** 1.4
**Xcode version:** 10
**Swift version:** 4.2

Included implementation and screenshot

    //
    //  FinalCategoryCell.swift
  
    import UIKit
    import SkeletonView
    
    class FinalCategoryCell: UICollectionViewCell, UICollectionViewDelegateFlowLayout {
        let categoryCellID = "categoryCell"
        let category = CategoryHeader()
        var categoryEvents:[Event]?{
            didSet{
                print("recieved featured event")
                categroyFeedCollectionView.reloadData()
            }
        }
         weak var mainVC: MainViewController?
        
        override init(frame: CGRect) {
            super.init(frame: frame)
            setupViews()
        }
        
        
        let categroyFeedCollectionView: UICollectionView = {
            let layout = UICollectionViewFlowLayout()
            layout.scrollDirection = .horizontal
            let cv = UICollectionView(frame: .zero, collectionViewLayout: layout)
            cv.backgroundColor = .clear
            cv.isSkeletonable = true
            return cv
        }()
        
        
        @objc func setupViews(){
            addSubview(categroyFeedCollectionView)
            addSubview(category)
            categroyFeedCollectionView.delegate = self
            categroyFeedCollectionView.dataSource = self
            categroyFeedCollectionView.showsHorizontalScrollIndicator = false
            categroyFeedCollectionView.decelerationRate = UIScrollViewDecelerationRateFast
            categroyFeedCollectionView.register(FinalCategoryEventCell.self, forCellWithReuseIdentifier: categoryCellID)
            category.snp.makeConstraints { (make) in
                make.top.equalTo(self.snp.top).offset(5)
                make.height.equalTo(30)
                make.left.right.equalTo(self)
            }
            categroyFeedCollectionView.snp.makeConstraints { (make) in
                make.left.right.equalTo(self)
                make.top.equalTo(self.category.snp.bottom)
                make.bottom.equalTo(self.snp.bottom).inset(25)
            }
            
            categroyFeedCollectionView.prepareSkeleton { (done) in
                self.categroyFeedCollectionView.showSkeleton()
            }
            
        }
        
        required init?(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    }
    
    
    extension FinalCategoryCell: SkeletonCollectionViewDataSource {
        func collectionSkeletonView(_ skeletonView: UICollectionView, cellIdentifierForItemAt indexPath: IndexPath) -> ReusableCellIdentifier {
            return categoryCellID
        }
        
        
        func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
            guard let count = categoryEvents?.count else {
                return 0
            }
            return count
        }
        
        func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: categoryCellID, for: indexPath) as! FinalCategoryEventCell
            cell.event = categoryEvents?[indexPath.item]
            return cell
        }
        
        func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
            return CGSize(width: 142.88, height: 230.17)
        }
        
        func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
            return UIEdgeInsets(top: 0, left: 5, bottom: 0, right: 5)
        }
        
        func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
            let eventDetails = NewEventDetailViewController(collectionViewLayout: UICollectionViewFlowLayout())
             eventDetails.currentEvent = categoryEvents?[indexPath.item]
            mainVC?.navigationController?.pushViewController(eventDetails, animated: true)
            
        }
        
        func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
            self.categroyFeedCollectionView.scrollToNearestVisibleCollectionViewCell()
        }
        
        func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
            if !decelerate {
                self.categroyFeedCollectionView.scrollToNearestVisibleCollectionViewCell()
            }
        }
    }
    
    extension FinalCategoryCell: UICollectionViewDelegate {
        
    }

Cell

    import UIKit
    import SkeletonView
    
    class FinalCategoryEventCell: UICollectionViewCell {
    
        var event: Event? {
            didSet{
                guard let currentEvent = event else {
                    return
                }
                guard URL(string: currentEvent.currentEventImage) != nil else { return }
                backgroundImageView.loadImage(urlString: currentEvent.currentEventImage)
                eventNameLabel.text = currentEvent.currentEventName.capitalized
                let dateComponets = getDayAndMonthFromEvent(currentEvent)
                eventDateLabel.text = dateComponets.0 + " "+dateComponets.1 + " "+dateComponets.2
                backgroundImageView.hideSkeleton()
                eventDateLabel.hideSkeleton()
                eventNameLabel.hideSkeleton()
            }
        }
        
        
        override init(frame: CGRect) {
            super.init(frame: frame)
            isSkeletonable = true
            setupViews()
        }
        let eventNameLabel : UILabel =  {
            let eventNameLabel = UILabel()
            eventNameLabel.isSkeletonable = true
    
            eventNameLabel.font = UIFont(name:"NoirPro-Medium", size: 15.0)
            eventNameLabel.textAlignment = .left
            eventNameLabel.lineBreakMode = .byTruncatingTail
            eventNameLabel.text = eventNameLabel.text?.uppercased()
            return eventNameLabel
        }()
        
        let eventDateLabel : UILabel =  {
            let eventDateLabel = UILabel()
            eventDateLabel.isSkeletonable = true
            eventDateLabel.textColor = UIColor.rgb(red: 132, green: 132, blue: 132)
            eventDateLabel.font = UIFont(name:"NoirPro-Regular", size: 13.0)
            eventDateLabel.textAlignment = .left
            eventDateLabel.adjustsFontSizeToFitWidth = true
            eventDateLabel.text = eventDateLabel.text?.uppercased()
            return eventDateLabel
        }()
        
        public var backgroundImageView: CustomImageView = {
            let firstImage = CustomImageView()
            firstImage.isSkeletonable = true
            firstImage.setupShadow2()
            firstImage.contentMode = .scaleToFill
            return firstImage
        }()
        
        @objc func setupViews(){
            
            addSubview(backgroundImageView)
            addSubview(eventDateLabel)
            addSubview(eventNameLabel)
            backgroundImageView.snp.makeConstraints { (make) in
                make.top.equalTo(self.snp.top)
                make.left.right.equalTo(self)
                make.height.equalTo(180)
            }
            eventDateLabel.snp.makeConstraints { (make) in
                make.top.equalTo(backgroundImageView.snp.bottom).offset(5)
                make.left.right.equalTo(self)
                make.height.equalTo(20)
            }
            eventNameLabel.snp.makeConstraints { (make) in
                make.top.equalTo(eventDateLabel.snp.bottom).offset(5)
                make.left.right.equalTo(self)
                make.height.equalTo(20)
            }
            
        }
        
        required init?(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
        
        
        fileprivate func getDayAndMonthFromEvent(_ event:Event) -> (String, String, String) {
            let apiDateFormat = "MM/dd/yyyy"
            let df = DateFormatter()
            df.dateFormat = apiDateFormat
            let eventDate = df.date(from: event.currentEventDate!)!
            df.dateFormat = "dd"
            let dayElement = df.string(from: eventDate)
            df.dateFormat = "MMM"
            let monthElement = df.string(from: eventDate)
            df.dateFormat = "yyyy"
            let yearElement = df.string(from: eventDate)
            return (dayElement, monthElement, yearElement)
        }
    }

<img width="337" alt="screen shot 2018-10-02 at 3 48 47 pm" src="https://user-images.githubusercontent.com/16108750/46373633-85ddda00-c65c-11e8-9e06-6a2166d05b9f.png">

**Comment by Smiller193** [comment]
@Yonodactyl are you still able to help

**Comment by sudeepdunzo** [comment]
@Smiller193  : hey  were you able to get this to work ?, i am stuck with a similar issue. can't seem to figure out how to solve it.


I have0 UIColltionView  view embedded inside Colltionview cell , the skeletondatasource functions are getting called  inside the cell as well , but not get ing expected behaviour  




![simulator screen shot - iphone xs - 2018-10-26 at 14 37 42](https://user-images.githubusercontent.com/41284821/47556950-302fe100-d92d-11e8-9532-75623d9f93ef.png)

**Comment by Smiller193** [comment]
@sudeepdunzo nope I just moved on

**Comment by dhiraj-quantumsoftech** [comment]
I have same problem , so i am not using SkeltonViewDataSource for returing Identifire , i have to show some dummy cells when we don't have any data . 
ex.  in numberOfitemsinSection -> self.arry.count.count > 0  ? self.arry.count : 4

i am showing 4 as dummy cell , but becareful in CollectionViewDelegate and DataSource before accessing any information

**Comment by hithakshi** [comment]
Any updates? In my case, my cell (that has UICollectionView embedded in it) is breaking. 
I created dummy loading UIViewController with dummy collectionView layout with skeletonable set to true. To show loading view, I added this loadingViewController as subview of existing viewController (this viewcontroller has cells with embedded collection view).  Strangely, my existing viewcontroller's cell UI is breaking.

**Comment by updev0612** [comment]
In compositional layout, I guess it does not work. I followed Video tutorials but There is no solution. 
my issue like this. 020-06-03 02:49:54.822341+0300 Mealz[33863:697211] [UICompositionalLayout] note: the section invalidation handler cannot currently mutate visible items for layouts containing estimated items. Please file an enhancement request on UICollectionView.
(0.0, 0.0)
2020-06-03 02:49:54.822806+0300 Mealz[33863:697211] *** Assertion failure in -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:], /Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3920.31.100/UICollectionView.m:2421

**Comment by az0r234** [comment]
It does work, in the collectionViewCell class you will have to add subviews into the contentView rather than the cellView. 
`contentView.addsubview("somesubviewHere")`.
Then after that you have to set each view you want skeletonized to have the "isSkeletonable" property set to true including the contentView.
`contentView.isSkeletonable = true`
