### ISSUE TITLE
Weird behaviour of skeletonView inside stackView

### ISSUE THREAD

**Issue by kamvoick** [Juanpe/SkeletonView#106]
### What did you do?

Launch the view

### What did you expect to happen?

SkeletonView should be offset by 15 from left (leading)

### What happened instead?

SkeletonView is align to left without any offset/padding

### Steps to reproduce the behavior

SkeletonView is enabled on label inside stackview which is itself constraint to the left and right side of view (constant = 0). Stackview is vertical and it has Alignment - center, the label inside has padding from left and right of stackView by 15(constraints). On the simulator/device it shows that skeletonView is align strictly to the left but when launching Debug View Hierarchy it is properly aligned by 15. Image attached (left: debug hierarchy, right: simulator)

![zrzut ekranu 2018-10-17 o 18 18 08](https://user-images.githubusercontent.com/19606025/47101001-2d503480-d239-11e8-84a5-34c5bea0bc84.png)

### SkeletonView Environment

**SkeletonView version: latest version**
**Xcode version: 10**
**Swift version: 4.2**

**Comment by kamvoick** [comment]
Ok, i found the solution. Don't know exactly why but clipToBounds on that label solves the problem. Close topic pls

**Comment by eduardbosch** [comment]
@kamvoick thanks for sharing the solution.

Let us know if you have any other issue.

**Comment by mltbnz** [comment]
I am also facing some issues when using StackViews. For example when adding the TextView from the Example app in a StackView and setting the constraints again, the TextView is not shown. I have set `isSkeletonable` on the StackView

**Comment by eduardbosch** [comment]
@mltbnz I've added the TextView from the Example to a StackView and seems to work as expected.

Please, if you continue having problems, open a new issue and describe your problem. Provide a sample project to see the bug if possible.

Many thanks.

**Comment by JonathandelaSen** [comment]
I had the same bug here, as Kamvoick said, clipToBounds did the trick.
