### ISSUE TITLE
UICollectionView isScrollEnabled/userInteractionEnabled is set to true after hiding the skeleton view.

### ISSUE THREAD

**Issue by SeNeO** [Juanpe/SkeletonView#108]
### What did you do?

Add a skeleton to a UICollectionView with isScrollEnalbed set to false

### What did you expect to happen?

The collection should stay not scrollable

### What happened instead?

The collectionview is set to be scrollable after hiding the skeletonview 

### SkeletonView Environment

**SkeletonView version:** 1.4.1
**Xcode version:** 1.0.1
**Swift version:** 4.2

**Comment by ohserezha** [comment]
if you are still wondering about such behavior - that's because 
``` swift
fileprivate func recursiveHideSkeleton(reloadDataAfter reload: Bool, root: UIView? = nil) {
        removeDummyDataSourceIfNeeded(reloadAfter: reload)
        isUserInteractionEnabled = true
```
