### ISSUE TITLE
SkeletonView with Static TableViews dosen't work

### ISSUE THREAD

**Issue by LennartKobosil** [Juanpe/SkeletonView#112]
### What did you do?

import SkeletonView
Skeletonable = On

SkeletonTableViewDataSource dosent work for my case I think. Because I have no prototype cells.

### What did you expect to happen?

Text, Images replaced with placeholders.

### What happened instead?

Static Table View dosent work anymore. No Scroll.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/22873369/49457277-d8697d00-f7ea-11e8-9072-188bed65e2b3.png">

### Steps to reproduce the behavior

1.Make an Static Table view for example an Settings Tab.
2.Then I put the cell and the lable and images on Skeletonable On.
3.import SkeletonView
4.view.showSkeleton()

### SkeletonView Environment

**SkeletonView version: 1.4.1**
**Xcode version: Version 10.1 beta 2 (10O35n**
**Swift version: 4.2**

**Comment by Juanpe** [comment]
Hi @LennartKobosil, could you know if cells has an identifier? and also could you provide the debug log? Here you can see how extract it [Skeleton debug](https://github.com/Juanpe/SkeletonView#-debug)

**Comment by LennartKobosil** [comment]
yes, the cells have identifiers. 

```Log

⬇⬇ ☠️ Root view hierarchy with Skeletons ⬇⬇ 

 <UITableView: 0x00007fd77509c000 | (1) subSkeletons | ☠️ > 
      <UITableViewCell: 0x00007fd7758a9600 | (3) subSkeletons | ☠️ > 
       <UIImageView: 0x00007fd773f6c360 | ☠️ > 
       <UILabel: 0x00007fd773e1c1f0 | ☠️ > 
       <UILabel: 0x00007fd773e3aac0 | ☠️ > 
      <UITableViewCell: 0x00007fd775072400> 
       <UILabel: 0x00007fd773c57000> 
       <UIImageView: 0x00007fd773c572f0> 
      <UITableViewCell: 0x00007fd77505a000> 
       <UILabel: 0x00007fd773c54440> 
       <UIImageView: 0x00007fd773c54730> 
      <UITableViewCell: 0x00007fd775020000> 
       <UILabel: 0x00007fd773c51600> 
       <UIImageView: 0x00007fd773c51af0> 
      <UITableViewCell: 0x00007fd775053c00> 
       <UILabel: 0x00007fd773c505b0> 
       <UIImageView: 0x00007fd773c508a0> 
      <UITableViewCell: 0x00007fd77507a000> 
       <UILabel: 0x00007fd773c4e9b0> 
       <UIImageView: 0x00007fd773c4eca0> 
      <UITableViewCell: 0x00007fd77507a600> 
       <UILabel: 0x00007fd773c26aa0> 
       <UIImageView: 0x00007fd773c26d90> 
      <UITableViewCell: 0x00007fd775085000> 
       <UILabel: 0x00007fd773c27d50> 
       <UIImageView: 0x00007fd773c28040> 
      <UITableViewCell: 0x00007fd775085600> 
       <UILabel: 0x00007fd773c29290> 
       <UIImageView: 0x00007fd773c29580> 
      <UITableViewCell: 0x00007fd775087000> 
       <UILabel: 0x00007fd773c2a690> 
       <UIImageView: 0x00007fd773c2a980> 
      <UITableViewCell: 0x00007fd775087600> 
       <UILabel: 0x00007fd773c2bd40> 
       <UIImageView: 0x00007fd773c2c030> 

```

**Comment by Juanpe** [comment]
Do you have implemented this method? 
`func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int`

**Comment by LennartKobosil** [comment]
I Need only the First cell skeletonable

**Comment by LennartKobosil** [comment]
I wanted to use SkeletonView to have placeholders for name email usw in my static menu.

**Comment by LennartKobosil** [comment]
@Juanpe

**Comment by Juanpe** [comment]
Then you can show the skeleton on the first cell. Do you know how?

**Comment by furiosFast** [comment]
Hi,
i've the same problem. 
I've a static tableView with 9 different cell. i've set isSkeletonable, but the effect doesn't start.
Any idea?

thanks
