### ISSUE TITLE
How to skeleton a part of table ?

### ISSUE THREAD

**Issue by gloryluu** [Juanpe/SkeletonView#116]
Is there any way to skeleton only Cell but Header and Footer ? Just config cell only will cover the table with a gray layer.

**Comment by Juanpe** [comment]
Hi @gloryluu, do you mean skeleton cells but headers and footers leave visible, right? 
Now, supplementaries views are not supported, I hope this feature will be available soon

**Comment by gloryluu** [comment]
Got it. Thanks @Juanpe
