### ISSUE TITLE
the skelectonview is out of date. I can't compile my project.

### ISSUE THREAD

**Issue by zechnegli** [Juanpe/SkeletonView#126]
⚠️ Please fill out this template when filing an issue.

### What did you do?

*Please replace this with what you did.*

### What did you expect to happen?

*Please replace this with what you expected to happen.*

### What happened instead?

*Please replace this with of what happened instead.*  

### Steps to reproduce the behavior

*Please replace this with the steps to reproduce the behavior.*

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:**
**Swift version:**
[
![111546921229_ pic_hd](https://user-images.githubusercontent.com/31859869/50809640-b798b980-12b9-11e9-833a-adda3e165bc9.jpg)
](url)

**Comment by gustavo434** [comment]
I am experiencing this same issue. Were you able to find a solution?

**Comment by chrsp** [comment]
I was facing the same issue. I'm using Swift 4.0 and trying to use SkeletonView 1.4.1. I changed to SkeletonView 1.4 and it worked. Try change the SkeletonView version

**Comment by zechnegli** [comment]
thanks， it is very helpful
