### ISSUE TITLE
SkeletonView is not showing in full view.

### ISSUE THREAD

**Issue by suraj-ios** [Juanpe/SkeletonView#127]
1.I have created one custom **XIB** for collectionview cell.
2. Inside this custom cell, I created one Sub-view / Imageview.
3.Enable skeleton for both Sub-View / Imageview.
4. BUT still it is showing only half of the Imageview / Sub-View.

Please see the attached image for your references.
![img_a8ea45c49615-1](https://user-images.githubusercontent.com/28855042/50832435-2d615b80-1374-11e9-9c34-83413825beb8.jpeg)

**Comment by suraj-ios** [comment]
@zechnegli ,

No i did not get any issues about variable name.

Can you share me screenshots?

**Comment by zechnegli** [comment]
I posted my problem under your problem which lead to a compliling error.

**Comment by Juanpe** [comment]
Hi @suraj-ios, last version (1.8.1) fixes a lot of errors related to frames. 
Please, update the library and if the issue is not fixed, open a new one with more details, please.

Thanks
