### ISSUE TITLE
Tableview inside Scrollview

### ISSUE THREAD

**Issue by edhoprast** [Juanpe/SkeletonView#129]
⚠️ Please fill out this template when filing an issue.

### What did you do?
import SkeletonView
enable skeleton on my tableview
put tableview inside scrollview because i want not only the tableview to be scrolled

### What did you expect to happen?
skeleton working on my tableview cell with condition my tableview inside a scrollview

### What happened instead?
only first cell became skeleton and the others not

### SkeletonView Environment

**SkeletonView version: 1.4.1
**Xcode version: 10.1
**Swift version: 4.2

**Comment by eduardbosch** [comment]
Hi @edhoprast,

Why do you want to use a `UITableView` inside a `UIScrollView`?

Maybe you can approach your issue in a different way. I think is not recommended to embed a `UITableView` inside a `UIScrollView`.

Can you explain your approach or share a sample project?

**Comment by edhoprast** [comment]
Hi @eduardbosch,

I see, I'll try different approach then thanks!
