### ISSUE TITLE
Gradient for Skeleton View

### ISSUE THREAD

**Issue by pushkardeshmukh1992** [Juanpe/SkeletonView#132]
Hey thanks for such a great Skeleton loading library. I don't have issues so far. Just a question if it can be achieved.

Is there any way I can set **gradients** for **default skeleton view**? 
Gradient Animated has gradient animation which can be configurable. That's cool. 
Moreover,  I want to apply **gradient** on the default view (which is mostly set to gray as default)

### SkeletonView Environment

**SkeletonView version:** 1.4
**Xcode version:** 10.1
**Swift version:** 4.0

**Comment by Juanpe** [comment]
Hi @pushkardeshmukh1992, you can use the gradient that you want. You only need to create the gradient:
```
let customGradient = SkeletonGradient(baseColor: .red)
view.showGradientSkeleton(usingGradient: customGradient)
```
