### ISSUE TITLE
Nested UICollectionView inside UITableViewCells.

### ISSUE THREAD

**Issue by Dominik777** [Juanpe/SkeletonView#133]
⚠️ Please fill out this template when filing an issue.

### What did you do?

Added a UITableView which has nested UICollection view in each cell. Set isSkelenotable to true on all views. Called prepareSkeleton on the nested UICollectionView.

### What did you expect to happen?

That the recursion includes the nested collection view and its cells.

### What happened instead?

The recursion stops at the nested collection view.

### Steps to reproduce the behavior

Create a UITableView that has nested UICollectionViews in the table view cells. Set isSkelenotable true on all views.

### SkeletonView Environment

**SkeletonView version: latest
**Xcode version: Xcode 10
**Swift version: 4.2

**Comment by callo90** [comment]
not working for me either, tried to load collection by collection using `UITableView visibleCells` but still not working for me

**Comment by selivandex** [comment]
Same

**Comment by seth-folley** [comment]
Confirming this as well.

**Comment by i0sa** [comment]
Confirming, still...

**Comment by yusufkildan** [comment]
Same

**Comment by jordanpichler** [comment]
Have a `UICollectionView` inside a `UICollectionView` (🤪) and it works for me. 

At first it didn't, blurred out the entire cell, but I got it fixed by giving my `UILabels` inside the cells widths and heights (or using constraints on all 4 sides). Use the ViewDebugger and in the list on the left, check what size they have.

**Comment by nisargmehta** [comment]
Any update here? how to have the shimmer on a collection view inside a UITableviewCell?
