### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by stevenp** [Juanpe/SkeletonView#136]
With so many open issues, and the fact that pod doesn't compile with the most modern version of Swift, I'm wondering if this project is still being maintained. If not, are you open to transitioning it to someone else?

**Comment by Juanpe** [comment]
Hi @stevenp, this project is alive. But we are fixing the issues as soon as we can :)
Version 1.4.1 is compatible with Swift 4.2, what problem do you have?

**Comment by stevenp** [comment]
I'm glad, thanks!

I had to make the change to the Podfile that's in https://github.com/Juanpe/SkeletonView/pull/128 in order to get things working.

**Comment by eduardbosch** [comment]
@stevenp can we close this question?
