### ISSUE TITLE
Custom Cell , it display the default cell before getting data from API

### ISSUE THREAD

**Issue by X901** [Juanpe/SkeletonView#137]
Hi , 
I have a Custom Cell
and I notice when I open the app, the data will download from API
but If I scroll down or if there is no internet 
I can see the default cell
what I mean by default is what I did design in Storyboard 

this image will let you understand what I mean 
https://cl.ly/997eabe6cb92

**what I expect ?**
either all cell be SkeletonView
or the user can not scrolling !

**Comment by eduardbosch** [comment]
Hi @X901 

Thanks for reporting this issue. Could you provide a sample project to check what's happening?

Meanwhile, can you check the branch `feature/Allow_updating_skeleton_layers` and let me know if it solves your issue?
https://github.com/Juanpe/SkeletonView/tree/feature/Allow_updating_skeleton_layers

**Comment by X901** [comment]
Can I install this version it via Cocoapods?

**Comment by Juanpe** [comment]
Sure, you only need to specify which branch you want inside the `Podfile`:
`pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git', :branch => 'Allow_updating_skeleton_layers'`

**Comment by X901** [comment]
I did test it 
noting change

**Comment by eduardbosch** [comment]
> I did test it
> noting change

Sorry @X901 , the pod specification that @Juanpe wrote was wrong.
I've updated it in his answer: https://github.com/Juanpe/SkeletonView/issues/137#issuecomment-491815154

Please, check it and update it again.

Thanks

**Comment by X901** [comment]
@eduardbosch Thank you 
it working fine!
I don't see the default cell anymore

**Comment by X901** [comment]
I notice after update one of my viewController broken 
before the update was looking right
https://cl.ly/fa2ed573c9c0

After
https://cl.ly/def8baa79142

I didn't change anything 
and also I try to change AutoLayout
noting change always like this

**Comment by eduardbosch** [comment]
Hi @X901,

I'm sorry that it broke your app.

Could you provide us with a sample project to test it out?

Many thanks 🙂

**Comment by X901** [comment]
Hi ,
I just notice this issue only happened with Label
when the viewController have the only label 
not inside StackView for example 

the label doesn't care about the AutoLayout
so it always will looking like this way 

see this image
https://cl.ly/29188a639310

**Comment by eduardbosch** [comment]
Hi @X901,

Are you sure you are calling this in your view controller?
```
    override func viewDidLayoutSubviews() {
        view.layoutSkeletonIfNeeded()
    }
```

It seems that the skeleton layout has not been updated.

If the problem persists, please, upload a sample project to GitHub and give us a link so we can check it.

Meanwhile, have you checked the examples from this repo?
https://github.com/Juanpe/SkeletonView/tree/master/Example

**Comment by X901** [comment]
@eduardbosch Thank
this fix my problem!

now everything working as expected

**Comment by eduardbosch** [comment]
@X901 great that is working now!

Could you provide a little bit more about what's happening?

Do you have a sample demo showing this problem?

**Comment by eduardbosch** [comment]
I'm closing this. Please, feel free to reopen if needed.
