### ISSUE TITLE
Editing textfield - textfield when skeleton is running 

### ISSUE THREAD

**Issue by manuel21** [Juanpe/SkeletonView#14]
⚠️ Please fill out this template when filing an issue.

### What did you do?

![simulator screen shot - iphone 8 - 2017-11-21 at 09 55 17](https://user-images.githubusercontent.com/7534410/33082481-865013f2-cea2-11e7-8c24-51b7f02c434e.png)

### What did you expect to happen?

nothing

### What happened instead?

enter text and the keyboard has been showed 

### Steps to reproduce the behavior

Set a texview with skeleton and  tap it 

### SkeletonView Environment

**SkeletonView version: Skeleton Sample project **
**Xcode version: 9**
**Swift version: 3.2**

**Comment by jontelang** [comment]
In https://github.com/Juanpe/SkeletonView/pull/12/files#diff-a514d17d33b5ed416f656b08b98d8a4bR88 I fixed this for the example project. But maybe it should be automatically set on textviews when skeleton'ed. That would make sense.

**Comment by Juanpe** [comment]
Hi @manuel21, you're right. It's a bug, I'm going to fix it as soon as possible 🙂

**Comment by Juanpe** [comment]
It's already solved in [version 1.0.4](https://github.com/Juanpe/SkeletonView/releases/tag/1.0.4)
