### ISSUE TITLE
CollectionView with RxDatasources not working

### ISSUE THREAD

**Issue by aabanaag** [Juanpe/SkeletonView#140]
⚠️ Please fill out this template when filing an issue.
### What did you do?

SkeletonView not showing in CollectionView with RxDatasources

### What did you expect to happen?

It should show SkeletonView on CollectionView even if data is not yet loaded.

### What happened instead?

CollectionView is empty and doesn't show skeletonview. 

### Steps to reproduce the behavior

I added (snippet below) but still not working. I already have set isSkeletonable to _TRUE_ or _ON_ on the storyboard. I also added the stubs with `collectionSkeletonView:numberofItemsonSection` set to 2(sample number)

```
collectionView.prepareSkeleton { [weak self] (done) in
      self?.collectionView.showAnimatedSkeleton()
    }
```

### SkeletonView Environment

**SkeletonView version: latest**
**Xcode version: 10**
**Swift version: 4.2**

**Comment by aabanaag** [comment]
I was able to show the skeletonView but any ideas on how I where I should call `hideSkeleton` using RxSwift?

**Comment by alouanemed** [comment]
Interesting one, were you able to solve this?

**Comment by Dfmarulanda** [comment]
I have the same problem; it works when is re-loading; but first time it shows only a gray space.
