### ISSUE TITLE
Dose not work with uitableview

### ISSUE THREAD

**Issue by adelbios** [Juanpe/SkeletonView#141]
I tried to run it, with the UItableView, it took 3 consecutive days without any trace result
,, i use this dependancy programitically .. tha't mean i coding without storyboard 
I puth everything isEnable , I tried all the solutions without getting a result... if u have any example with tableView please send the link ... seriously iam disappointing

**Comment by Douvi** [comment]
did you try to lock at `https://github.com/Juanpe/SkeletonView/tree/master/Example`

**Comment by adelbios** [comment]
With storyboard work fine ,,,but i do everything programitically

**Comment by adelbios** [comment]
Any help ?? Can u provide demo project for UITableView programitically?!

**Comment by chrsp** [comment]
I'm facing the same problem. doens't work with tableview created programmatically :(

**Comment by jpeckner** [comment]
See my [comment](https://github.com/Juanpe/SkeletonView/issues/125#issuecomment-469459560) in issue #125, sounds like this might be related.

**Comment by adelbios** [comment]
@jpeckner can u provide demo ?! u're solution dose not work

**Comment by daveleenew** [comment]
without storyboard demo : https://drive.google.com/open?id=17VmHMwweV5QNdtpU-PqmcOpVbEt696tu

**Comment by eduardbosch** [comment]
@adelbios is your issue solved using UITableView programmatically?
Can I close this issue?

**Comment by daveleenew** [comment]
Yes

「Eduard Bosch Bertran <notifications@github.com>」在 2019年5月8日 週三，05:38 寫道：

**Comment by nabs107** [comment]
> without storyboard demo : https://drive.google.com/open?id=17VmHMwweV5QNdtpU-PqmcOpVbEt696tu

Says No preview available. File is in owner's bin.
