### ISSUE TITLE
display is wrong in RTL

### ISSUE THREAD

**Issue by ahmediosDeveloper** [Juanpe/SkeletonView#143]
every this is doing right , but when i use RTL direction it shows wrong.
this for english
![Simulator Screen Shot - iPhone 8 - 2019-03-30 at 15 25 15](https://user-images.githubusercontent.com/18172069/55276883-d8453e00-5301-11e9-8cbb-9ba641c5fbf9.png)
but same in arabic comes in this way 

![Simulator Screen Shot - iPhone 8 - 2019-03-30 at 15 38 58](https://user-images.githubusercontent.com/18172069/55276890-fc088400-5301-11e9-9f86-57db900cd50f.png)

**Comment by alghraibehMahmoud** [comment]
Hi , 
Just start skeleton in  viewDidLayoutSubviews ,

`
override func viewDidLayoutSubviews() {
        tableView.showAnimatedGradientSkeleton()
        tableView.startSkeletonAnimation()
    }
`

**Comment by zaidqattan** [comment]
I'm having the same issue while trying to use this effect in RTL. Did you find any solutions?

**Comment by zaidqattan** [comment]
@Juanpe any solutions for this problem?

**Comment by Juanpe** [comment]
Hi @zaidqattan, could you give me more info about this bug, in order to investigate how to fix it?

**Comment by Juanpe** [comment]
Hi @zaidqattan, please, could you provide us more info about this bug, in order to investigate how to fix it? Thanks

**Comment by zaidqattan** [comment]
![Simulator Screen Shot - iPhone Xs - 2019-08-28 at 09 28 23](https://user-images.githubusercontent.com/43964601/63831295-06917d00-c977-11e9-8e32-d08dab6eace9.png)
![Simulator Screen Shot - iPhone Xs - 2019-08-28 at 09 28 26](https://user-images.githubusercontent.com/43964601/63831302-085b4080-c977-11e9-8721-595c5224a922.png)

When I tried to apply the skeleton view on arabic text in UILabel as you see it fail to cover the line with correct alignment

**Comment by zaidqattan** [comment]
@Juanpe waiting for you response, Thanks!

**Comment by Juanpe** [comment]
Thanks for the info, I'm going to investigate this. Just one thing, sorry but I never did it, how you configure the UILabel to show Arabic text, only need to align the text to right?

**Comment by zaidqattan** [comment]
<img width="255" alt="Screen Shot 2019-08-28 at 11 44 47 AM" src="https://user-images.githubusercontent.com/43964601/63840172-45303300-c989-11e9-94d0-690c01d7cb2e.png">
Sorry it was UITextView
also UILabel has same issue and I think it's a general issue in supporting RTL languages.

**Comment by zaidqattan** [comment]
@Juanpe I set the alignment to right as you see in the screenshot above

**Comment by zaidqattan** [comment]
@Juanpe any news?

**Comment by Juanpe** [comment]
Not yet, let you know when I found the problem and it's solved. Thanks

**Comment by zaidqattan** [comment]
any news about the bug fixing ? @Juanpe

**Comment by crabman448** [comment]
I don't think you have to specify alignment to the right specifically for RTL. As I understand you have to set the proper anchors and then the system will display things fine for RTL

**Comment by crabman448** [comment]
From the docs

```
By default, text alignment in iOS is natural; in OS X, it’s left. Using natural text alignment aligns text on the left in a left-to-right language, and automatically mirrors the alignment for right-to-left languages. For example, if you set the alignment of an NSMutableParagraphStyle object using the setAlignment: method, pass NSNaturalTextAlignment as the parameter.

However, if you want to align a control to the right in a left-to-right language (and to the left in a right-to-left language), get the layout direction, as described in Getting the Layout Direction, and set the alignment to NSLeftTextAlignment for a right-to-left language.
```

[Source](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html#//apple_ref/doc/uid/10000171i-CH17)

**Comment by zaidqattan** [comment]
@crabman448 I'm still having the same issue even after specifying the alignment.

**Comment by zaidqattan** [comment]
@Juanpe any news please?

**Comment by Juanpe** [comment]
Hi @zaidqattan, I tried to reproduce this bug, I can't :/ 
Actually, the skeleton layer uses the view frame and doesn't matter the text alignment. So, if you specify correctly the layout constraints, the skeleton should work fine...

Let me know if you solved this problem or if you can provide more info about your layout.

**Comment by Abe-2** [comment]
This issue is occurring when using multiline skeletons on labels. To reproduce the issue, create a vertical stack view and place two labels inside it. let the first label have only one line of text and the other multiple lines. The alignment doesn't matter. For the stack view, set the alignment to "Leading." Change the app semantic to right-to-left. When you run the app the first label with align to the right and the second aligning to the left.

**Comment by Juanpe** [comment]
Hi!

Finally, SkeletonView has support for RTL, since version 1.10.0 🎉 

![skeleton_rtl](https://user-images.githubusercontent.com/1409041/94940114-596f2980-04d3-11eb-81b6-25bb204a8b0a.gif)
