### ISSUE TITLE
numberOfLines nor calculated text length dictate number of lines

### ISSUE THREAD

**Issue by bpollock-vida** [Juanpe/SkeletonView#147]
### What did you do?

Made a UILabel skeletonable and set the numberOfLines to 3

### What did you expect to happen?

That a skeleton with three lines would show

### What happened instead?

Only one line rendered for UILabel

### Steps to reproduce the behavior

Set fakeLabel.numberOfLines = 3 in the example project

### SkeletonView Environment

SkeletonView version: 1.4.2
Xcode version: 10.1
Swift version: 4.2

### Other details
Another approach to this problem is to supply a long text string so auto layout will expand the view size. However, SkeletonView must get in the way first because the view never expands to fit text.

Workaround:
The size of a label must be set manually and cannot be dynamic based up on UILabel properties.

**Comment by yaxunliu** [comment]
I meet same question too . To solve it, you should set label's width, or constrain label's width less than xx or more than.  you can find it in author's demo

**Comment by Juanpe** [comment]
Hi @bpollock-vida, I've reviewed your problem and I don't understand very well what is it working wrong, I mean, If you set the number of lines equal 3, the UILabel height is not calculated dynamically, you need to specify the height value. But if you set the number of lines to 0, then UILabel height is calculated dynamically. In this case, the skeleton uses the constraint to calculated what is the maximum height that the UILabel could have.
