### ISSUE TITLE
Gradient direction changed after leaving app

### ISSUE THREAD

**Issue by kimsonwong** [Juanpe/SkeletonView#149]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I made this view with top to bottom gradient. This is what I used to create gradient:

let gradient = SkeletonGradient.init(baseColor: color_262626, secondaryColor: color_4B4B4B)
       let animation = SkeletonAnimationBuilder().makeSlidingAnimation(withDirection: .topBottom)
       skeletonView.isSkeletonable = true
       skeletonView.showAnimatedGradientSkeleton(usingGradient: gradient, animation: animation)

### What did you expect to happen?

When I leave the app or go to app switcher and go back to my app I expect the gradient to be the same because I did not update it in any way.

### What happened instead?

Instead of staying the same gradient direction, it changed from top to bottom, to left to right.

### Steps to reproduce the behavior

Video attached.

### SkeletonView Environment

SkeletonView 1.5
Xcode 10.1 (10B61)
Swift 3

![skeleton gradient issue](https://user-images.githubusercontent.com/3351877/56945811-f39ea580-6b5a-11e9-8509-ca1b321dd7b5.gif)

**Comment by Juanpe** [comment]
Thanks @kimsonwong for report this bug. It will fixed soon :)

**Comment by FeedMyTummy** [comment]
I have the issue that when I use it in a tab view switch out and switch back, the animation stops. Anyway to prevent this?

**Comment by danqing** [comment]
To add to @FeedMyTummy, for me not only does the animation stop, the skeleton view looks pretty strange (not a solid color).

@Juanpe do you know if this and the issue reported by OP are the same? It sounds like you already have an idea of what might have gone wrong? I believe this is also related to (much older) #88.

![IMG_26EC07CB83C7-1](https://user-images.githubusercontent.com/5134133/63180506-0349e780-c081-11e9-84d0-4f5e1fc2aaed.jpeg)

**Comment by danqing** [comment]
FWIW, after upgraded to 1.8, I always see the above, even on the first load..

**Comment by Juanpe** [comment]
Thanks @danqing, I’m working on this bug, I hope release a patch soon 🤙🏼

**Comment by Juanpe** [comment]
Hi!

This bug has been fixed in [version 1.8.1](https://github.com/Juanpe/SkeletonView/releases/tag/1.8.1)

Thanks for reporting this bug and for use SkeletonView.
