### ISSUE TITLE
Update for swift 5 and Xcode 10.2

### ISSUE THREAD

**Issue by osamaazmat** [Juanpe/SkeletonView#153]
Can you please update this library for swift 5 and Xcode 10.2?

**Comment by Juanpe** [comment]
Hi @osamaazmat, the last version (1.5) is compatible with Swift 5 and Xcode 10.2. So you should update your local pod repo and check if installed version is the last.

If after re-install and update the pods, this issue is solved, please close it :)

**Comment by osamaazmat** [comment]
@Juanpe I understand, Thankyou so much.
