### ISSUE TITLE
Isn't issue ,, SwiftUI

### ISSUE THREAD

**Issue by adelbios** [Juanpe/SkeletonView#154]
What's the plan for this awesome library to make it work with SwiftUI 😍

**Comment by Juanpe** [comment]
Hi, @adelbios, we need to know exactly what SwiftUI 😍 is, then SkeletonView will be compatible with SwiftUI.

**Comment by adelbios** [comment]
I am so happy and excited,,, can i work with u're time to develop this library to support SwiftUI?!

**Comment by adelbios** [comment]
Any update ?!

**Comment by sboh1214** [comment]
Any update ?
