### ISSUE TITLE
Rounded corners for cells with shadows

### ISSUE THREAD

**Issue by tomasbek** [Juanpe/SkeletonView#157]
### What did you do?
I have a CollectionView cell with rounded corners and shadow behind it. I want to show an animated gradient skeleton view on top of the cell.
![IMG_3034](https://user-images.githubusercontent.com/14822950/59766551-23d80a00-92a9-11e9-91fe-9a609cfde579.PNG)

### What did you expect to happen?
I expected to have a skeleton view shown with cell's rounded corners maintained.

### What happened instead?
Unfortunatelly, the rounded corners dissapear when the skeleton view is shown.
![IMG_3033](https://user-images.githubusercontent.com/14822950/59766727-803b2980-92a9-11e9-8e0b-fe5582b6d48f.PNG)

### Steps to reproduce the behavior
I tried to fix this by adding `masksToBounds = true` (following the example [here](https://github.com/Juanpe/SkeletonView/issues/13)). However, in this case I retain the rounded corners but loose the shadow behind the cell.
![IMG_3035](https://user-images.githubusercontent.com/14822950/59767476-158aed80-92ab-11e9-8afd-95a8c97a0197.PNG)

My question is the following: **is it possible to have both - cell's rounded corners and shadow behind the cell when skeleton view is shown**?

### SkeletonView Environment

**SkeletonView version: 1.6**
**Xcode version: 11**
**Swift version: 5**

**Comment by ohserezha** [comment]
i have UICollectionViewCell with rounded corners and shadows in my project too. And it's working fine with skeleton. 
I'm using this approach for rounded corners with shadows simultaneously: 
1) create shadows using UIBezierPath (notice `masksToBounds = false`)

```
extension UIView {
     func dropShadow(radius: CGFloat, offsetX: CGFloat, offsetY: CGFloat, color: UIColor) {
        layer.masksToBounds = false
        layer.shadowPath = UIBezierPath(roundedRect: bounds, cornerRadius: layer.cornerRadius).cgPath
        layer.shadowRadius = radius
        layer.shadowOffset = CGSize(width: offsetX, height: offsetY)
        layer.shadowOpacity = 1 // setting this property to 1 makes full relation on color's opacity
        layer.shadowColor = color.cgColor
    }
}
```

2) in cell's class override `layoutSubviews`

```
override func layoutSubviews() {
        super.layoutSubviews()
        layer.cornerRadius = 10
        dropShadow(radius: 15, offsetX: 0, offsetY: 5, color: .grey)
 }
...

**Comment by tomasbek** [comment]
@ohserezha, thank you for your suggestion. I have tried to implement your appraoch, however, unsuccessfully. Even with your proposed code I get non-round-corner cells. Could this be related with the fact that those collectionview cells of mine are within a tableview cell?

**Comment by ohserezha** [comment]
> Even with your proposed code I get non-round-corner cells
but the shadows are in place, aren't they?

> Could this be related with the fact that those collectionview cells of mine are within a tableview cell?
very unlikely

i forgot to mention important fact that you have to carefully inspect your cell's views hierarchy within this approach. Sorry for that. You have to check that any superview of your rounded+shadowed view doesn't clip your shadow or overrides `maskToBounds` property.

**Comment by tomasbek** [comment]
@ohserezha, thanks for clarifying your point.  After checking the cell's views hierarchy and after manually setting `maskToBounds = false ` of all the views within the cell, I still cannot achieve the desired outcome of rounded corners + shadow.

To make it easier to explain what I mean, here is the cell's view hierarchy with a skeleton gradient enabled. In this case, I get no rounded corners, though, the shadow is visible behind the cell.
<img width="441" alt="Screenshot 2019-07-01 at 20 45 53" src="https://user-images.githubusercontent.com/14822950/60457017-9e0e7400-9c43-11e9-90f0-597bc2144324.png">

After hiding the skeleton gradient, rounded corners appear. Shadow is also visible behind the cell.
<img width="441" alt="Screenshot 2019-07-01 at 20 42 55" src="https://user-images.githubusercontent.com/14822950/60457019-9ea70a80-9c43-11e9-9c94-ee2c997c0626.png">

Any ideas? 😥

**Comment by ohserezha** [comment]
sorry for the long response.
are you having skeleton's gradient on the deepest layer? like on the same layer as shadows?

**Comment by ohserezha** [comment]
oh, somehow I missed it. try to distinct shadow layer from animating-skeleton layer (just make animation not on the shadowed view). don't forget to make all views in hierarchy skeletonable

**Comment by ohserezha** [comment]
It seems that there is no complete mechanism for a full view's state restoration after showing skeleton
