### ISSUE TITLE
Problem with position of mask 

### ISSUE THREAD

**Issue by kszuba** [Juanpe/SkeletonView#16]
@Juanpe 
### What did you do?
Use your project in my app :)

### What did you expect to happen?
This will work perfectly :)

### What happened instead?
Something weird :)
<img src="https://user-images.githubusercontent.com/25151619/33232117-946ab80a-d200-11e7-95b7-9d043d734c31.png" width="300"/><img src="https://user-images.githubusercontent.com/25151619/33232116-9440a2f4-d200-11e7-82f9-f1122472f3ff.png" width="300"/>

### Steps to reproduce the behavior
Don't worry, I changed your example, added my cell and this still not work. Without skeleton tableView look good, but with animated skeleton some of views in cell have problems.
Can you help me fix this ? :) My app has complicated logic and unfortunately I need this and others cells AS IS :/ 

[SkeletonViewWithError.zip](https://github.com/Juanpe/SkeletonView/files/1503202/SkeletonViewWithError.zip)

### SkeletonView Environment

**SkeletonView version: 1.0.4**
**Xcode version: 9.1**
**Swift version: 4**

**Comment by Juanpe** [comment]
Hi @kszuba, I'm going to check :)
Thanks

**Comment by kszuba** [comment]
Hi @Juanpe,
have you had time to check the error?

**Comment by jbweimar** [comment]
I also find it's not working well. I'm going to write my own since that would probably take as much time as debugging what's going on. Too bad, because the concept/code looks good.

**Comment by jbweimar** [comment]
FYI, I'm doing it a different way. It might not be entirely economical, but for my use-case it works fine. I just hold an extra UIView in each UIView extension that resizes itself to its parent. This way, the skeleton will always be the size of the view that contains dummy data. This is nice if you change orientation and your label changes size (the skeleton will also change size).

**Comment by Wilsonilo** [comment]
I just want to give my input here just in case someone gets in my same situation. Using trailing / leading constrains was making problems with the Skeleton View. As @Juanpe mentioned using direct width + height was the only way to go around it. I tried to update constraints, setNeedsLayout, making a subclass of UILabel, nothing worked, so here is what happened after doing the direct width/height. 
![screen shot 2018-07-11 at 10 36 37 am](https://user-images.githubusercontent.com/2402695/42583627-f72e31de-84f6-11e8-902d-4b0cbc496f5f.png)
![screen shot 2018-07-11 at 10 35 02 am](https://user-images.githubusercontent.com/2402695/42583628-f74b7488-84f6-11e8-91a4-f679336b3bcd.png)

**Comment by q351941406** [comment]
A year on, the problem has not been solved
