### ISSUE TITLE
hideSkeleton error

### ISSUE THREAD

**Issue by adelbios** [Juanpe/SkeletonView#161]
what's the correct way to hide Skeleton 

![IMG_0005](https://user-images.githubusercontent.com/16545509/60182285-bbe76d80-982c-11e9-81f0-f66d451b1b16.PNG) is

**Comment by Juanpe** [comment]
Hi @adelbios, you need to call `hideSkeleton` using the same view when you start to show it.

**Comment by nikhil-p-crest** [comment]
I am also having the same issue, I tried to call hideSkeleton from the same view I called show but it still not working.

**Comment by Juanpe** [comment]
@adelbios, any news about this issue?

**Comment by np-43** [comment]
For now, I found a solution is that you can call hideSkeleton() method in `cellForRowAt indexPath` for cell object.

Example:

`func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell")
        cell?.hideSkeleton()
        return cell!
    }`

**Comment by np-43** [comment]
For now, I found a solution is that you can call hideSkeleton() method in `cellForRowAt indexPath` for cell object.

Example:
```
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell") as! CustomTableViewCell
        cell.hideSkeleton()
        return cell
}
```
