### ISSUE TITLE
The effect cannot be displayed on headerView in collectionView

### ISSUE THREAD

**Issue by lczalh** [Juanpe/SkeletonView#163]
The headerView in collectionView and its children set isSkeletonable = true, but it failed

**Comment by Juanpe** [comment]
hi @lczalh, headers are supported from version 1.7

Please, could you update `SkeletonView` on your project?

Thanks

**Comment by Juanpe** [comment]
Hi @lczalh, could you update the project?

**Comment by lczalh** [comment]
thanks

**Comment by lczalh** [comment]
When I used SnapKit to lay out the UI, the UILabel did not fix the size, but it gave the default value, and the skeleton showed an offset

**Comment by Juanpe** [comment]
Please, could you create a new issue one? In order to close the original issue. Thanks :)
