### ISSUE TITLE
Crashed when using layoutSkeletonIfNeeded

### ISSUE THREAD

**Issue by bentahyar** [Juanpe/SkeletonView#165]
### What did you do?

Upgrading to SkeletonView 1.7 and using ```layoutSkeletonIfNeeded```

### What did you expect to happen?

The skeleton works as it supposed to be

### What happened instead?

Crashed when using the function, the log cat shown 
```
dyld: lazy symbol binding failed: Symbol not found: _$sSo6UIViewC12SkeletonViewE06layoutB8IfNeededyyF
  Referenced from: ...
  Expected in: ...Frameworks/SkeletonView.framework/SkeletonView

dyld: Symbol not found: _$sSo6UIViewC12SkeletonViewE06layoutB8IfNeededyyF
  Referenced from: ...
  Expected in: ...Frameworks/SkeletonView.framework/SkeletonView
```

### Steps to reproduce the behavior

Use the function as example
```
override func viewDidLayoutSubviews() {
    view.layoutSkeletonIfNeeded()
}
```

### SkeletonView Environment

**SkeletonView version: 1.7**
**Xcode version: 10.2.1**
**Swift version: 4**

**Comment by Juanpe** [comment]
Hi @bentahyar, could you check if you can see the method (`layoutSkeletonIfNeeded`) inside the framework?

**Comment by bentahyar** [comment]
yes, I could see the method inside the framework.
after I test it again, it strangely works as expected. Thank you :)
