### ISSUE TITLE
Crashed on header and footer for collectionview

### ISSUE THREAD

**Issue by bentahyar** [Juanpe/SkeletonView#166]
### What did you do?

Upgrading to SkeletonView 1.7, implemented header and footer before upgraded and worked as expected.

### What did you expect to happen?

SkeletonView worked as it's supposed to be

### What happened instead?

Application crashed pointing that my header is nil (eventhough I have changed nothing to the implementation). The crash shown
```
uncaught exception 'NSInternalInconsistencyException', reason: 'the view returned from -collectionView:viewForSupplementaryElementOfKind:atIndexPath (UICollectionElementKindSectionFooter
```
notes: I already registered the view etc. It worked before I upgrade the library

### Steps to reproduce the behavior

Implement header and footer to collection view

### SkeletonView Environment

**SkeletonView version: 1.7**
**Xcode version: 10.2.1**
**Swift version: 4**

**Comment by Juanpe** [comment]
Hi @bentahyar, are you implemented this method `func collectionSkeletonView(_ skeletonView: UICollectionView, supplementaryViewIdentifierOfKind: String, at indexPath: IndexPath) -> ReusableCellIdentifier?`?

this is an important point, because the library needs to know which the header/footer identifier

**Comment by bentahyar** [comment]
no, I haven't. After implementing it, the skeleton works as it's supposed to be. Thank you for the reply :)

Maybe you can update the docs, so that we know that if we have supplementary view implemented, we must implement
`func collectionSkeletonView(_ skeletonView: UICollectionView, supplementaryViewIdentifierOfKind: String, at indexPath: IndexPath) -> ReusableCellIdentifier?`

**Comment by Juanpe** [comment]
Yep, totally agree with you, I'm going to update de docs, because could be confusing :)

Thanks!

BTW this issue is solved then?

**Comment by bentahyar** [comment]
Yesss, thanks for the response :)

**Comment by SuperCrazyCodeMan** [comment]
hello, I use that code for the header on UICollectionView but nothing happened. any suggest guys ?
