### ISSUE TITLE
Doesn't work with TableViews with auto cell height

### ISSUE THREAD

**Issue by weiran** [Juanpe/SkeletonView#17]
⚠️ Please fill out this template when filing an issue.

### What did you do?

Tried to integrate with `TableView`s that use automatic cell height.

### What did you expect to happen?

Either use the estimated cell height (if set), the height of the specific cell prototype, or an appropriate default value for cell height to display skeleton cells.

### What happened instead?

It seems the whole tableview gets treated as one single control. 

### Steps to reproduce the behavior

Edit TableView in example project to use auto cell height.

### SkeletonView Environment

**SkeletonView version:** 1.0.4 (latest)
**Xcode version:** 9.1
**Swift version:** 4

Alternative solution: create an `SkeletonTableViewDelegate` protocol which has a method to return a skeleton cell height if the height is ambiguous.

**Comment by Juanpe** [comment]
Hi @weiran, I'm going to check and fix it as soon as possible :) 
Thanks!

**Comment by FaridBehnia** [comment]
Any updates on this?

**Comment by Juanpe** [comment]
Hi @weiran, the problem has been fixed in version [1.0.5](https://github.com/Juanpe/SkeletonView/releases/tag/1.0.5)

**Comment by weiran** [comment]
Thanks confirmed 👍
