### ISSUE TITLE
After the UITableView USES SkeletonView, the skeleton layout doesn't appear

### ISSUE THREAD

**Issue by luopan1990911** [Juanpe/SkeletonView#172]
import UIKit
import SkeletonView

class MoneyCommissionViewController: UIViewController {

fileprivate lazy var itemTableView: UITableView = {
        let view = UITableView()
        view.separatorColor = UIColor(red: 0.96, green: 0.96, blue: 0.96, alpha: 1.0)
        view.separatorStyle = .singleLine
        view.isScrollEnabled = false
        view.register(CommissionItemViewCell.self, forCellReuseIdentifier: "ItemViewCell")
        view.estimatedRowHeight = 130
        view.rowHeight = UITableView.automaticDimension
        view.delegate = self
        view.dataSource = self
        view.isSkeletonable = true
        view.reloadData()

        return view
    }()

override func viewDidLoad() {
        super.viewDidLoad()
        
       view.addSubview(itemTableView)
        itemTableView.snp.makeConstraints { (make) in
            make.left.equalToSuperview().offset(15)
            make.right.equalToSuperview().offset(-15)
            make.top.equalTo(hotView.snp.bottom)
            make.size.equalTo(CGSize(width: screenWidth - 30, height: 650))
        }
        itemTableView.showAnimatedSkeleton()
    }

}
// MARK: - UITableViewDelegate, UITableViewDataSource 代理
extension MoneyCommissionViewController: SkeletonTableViewDelegate,SkeletonTableViewDataSource {
    
    func collectionSkeletonView(_ skeletonView: UITableView, cellIdentifierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
        return "ItemViewCell"
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return items.count
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 130
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "ItemViewCell", for: indexPath) as! CommissionItemViewCell
        cell.isSkeletonable = true
        
        return cell
    }

}

**Comment by Juanpe** [comment]
hi @luopan1990911, checking your code I see that you are showing the skeleton, but I can't see the method to hide the skeleton (`hideSkeletonView()`). 

Where are you calling this method?

**Comment by StasanTelnov** [comment]
Hello.
I have this case too.
When is correct calling `hideSkeletonView()`?

I have:
```swift
    func numberOfSections(in tableView: UITableView) -> Int {
        return eatBoxesList.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        ...
    }
    func numSections(in collectionSkeletonView: UITableView) -> Int {
        return 1
    }
    
// skeletonable
    func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, cellIdentifierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
        EatBoxTableViewCell.tableCellRegisterXib(tableView: skeletonView) // my wrapper for register cells
        return EatBoxTableViewCell.reuseIdentifier
    }
```
I think, that:
* Calling `hideSkeletonView()` in `numberOfSections` is hard logic with `if`/`guard`
* Calling `hideSkeletonView()` in `cellForRowAt` is overhead
* Calling `hideSkeletonView()` when I get data from server is hard logic too (checks for non-zero variants and errors handing)

How as alternative I try this variant:
```swift
    func numberOfSections(in tableView: UITableView) -> Int {
        return eatBoxesList.count == 0 ? 3 : eatBoxesList.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        ...
        guard let item = eatBoxesList[safe: indexPath.section] else {
            cell.showAnimatedGradientSkeleton()
            return cell
        }
        cell.hideSkeleton()
        ...
    }
```

But I think that is not very good solution.

What is the best practic of calling `hideSkeletonView()` in this case?

**Comment by StasanTelnov** [comment]
And I have strange logic.
I viewDidLoad, if I try this code:
```
    override func viewDidLoad() {
        ...
        view.showAnimatedGradientSkeleton()
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            self.view.hideSkeleton()
            self.eatBoxesList = ["test1", "test2"]
            self.boxesTable?.reloadData()
        }
    }
```
That skeleton view dont removed, it stays over first cell.
But this code, work correct:
```
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            self.eatBoxesList = ["test1", "test2"]
            self.boxesTable?.reloadData()
            self.view.hideSkeleton()
        }
//or
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            self.view.hideSkeleton()
        }
//or
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            self.eatBoxesList = ["test1", "test2"]
            self.view.hideSkeleton()
            self.boxesTable?.reloadData()
        }
```

When, if I calling `hideSkeleton()` before reloadTable, skeleton view dont hidding?
It is normal logic or bug?
