### ISSUE TITLE
Swift Package Manager version format

### ISSUE THREAD

**Issue by miguelangel-dev** [Juanpe/SkeletonView#175]
### Description
Swift Package Manager is not working using the current tag format `VERSION`.`MINOR` 

Apple recommend use version formatting [`VERSION`.`MINOR`.`PATCH`](https://semver.org/) as we can read in [swift.org](https://swift.org/package-manager/)

`
The source URL is a URL accessible to the current user that resolves to a Git repository. The version requirements, which follow Semantic Versioning (SemVer) conventions, are used to determine which Git tag to check out and use to build the dependency
`

### What did you do?

`swift package resolve` - using a Package.swift file with the next dependency
```swift
.package(url: "https://github.com/Juanpe/SkeletonView.git", from: "1.7")
```
is not resolving the SkeletonView dependency because `tag format` is not correct.

### How to resolve problems about SPM?

Just change current versioning to `VERSION`.`MINOR`.`PATCH` 

ex. following the current version
```swift
.package(url: "https://github.com/Juanpe/SkeletonView.git", from: "1.7.0")
```

**Comment by Juanpe** [comment]
Hi @miguelangel-dev! Thanks for the comment! Would you like contribute to the project? 😬

**Comment by Juanpe** [comment]
Solved! README file has been updated specifying full version
