### ISSUE TITLE
Hide specific element from appearing at all

### ISSUE THREAD

**Issue by i0sa** [Juanpe/SkeletonView#176]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I tried skeleton, but i having one element skeletonable to OFF, makes it appear still, how about hiding it all ?
### Steps to reproduce the behavior
Have an option for the element in code, to keep hidden, as long as skeletonable is active

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:** 10.2
**Swift version:** 5

**Comment by Juanpe** [comment]
Hi @i0sa, if you want to hide an element while the skeleton is active, you can use  both `isHidden` and `alpha` property. 
Is it valid for you?

**Comment by i0sa** [comment]
@Juanpe I still have to re-toggle this myself, I'm talking about an explicit hiding function for skeleton, that would work if i show gradient or hide skeleton, automatic

**Comment by diogot** [comment]
I have a similar issue.
Is there a delegate or some callback that we can use to be notified when the skeleton is activated and deactivated?

**Comment by anoop4real** [comment]
I am also interested to know this

**Comment by diogot** [comment]
I opened a PR (#227) that will emits notifications when the skeleton state of a view changes.
I'm using it to hide specific views, it might not be the best way, but it works.

**Comment by Juanpe** [comment]
PR (#227) has been merged :)

**Comment by i0sa** [comment]
Note that PR https://github.com/Juanpe/SkeletonView/pull/339 has done exactly what i was asking for.

**Comment by Khaled-elsedek** [comment]
@i0sa  did you got the solution to hide specific element

**Comment by Juanpe** [comment]
hi @Khaled-elsedek, as you can check in the readme file, you can hide an element when the skeleton is active.

```
/// Hiding views when the animation starts
/// Sometimes you wanna hide some view when the animation starts, so there is a quick property that you can use to make this happen:

view.isHiddenWhenSkeletonIsActive = true  // This works only when isSkeletonable = true
```

It's important to make skeletonable the view which you want to hide
