### ISSUE TITLE
show skeleton for only one cell in table view

### ISSUE THREAD

**Issue by ahmadsallam** [Juanpe/SkeletonView#177]
hello,

We have case that we need to show skeleton for specific view at some row in table view that already have skeleton view but it will be hide after end of the first request of the api the second request is for specific view in the same table view that not depends on the first request 
i've search in the library but couldn't find any thing that can help so is there is way to do it ?

**Comment by Juanpe** [comment]
Actually, you can show the skeleton for whatever view. So, you don't need to show the skeleton in your table. 

I think your cells could show the skeleton instead of the table view.

Does it solve your problem?
