### ISSUE TITLE
Unable to find a specification for `SkeletonView`

### ISSUE THREAD

**Issue by jamesTheKid** [Juanpe/SkeletonView#18]
⚠️ Please fill out this template when filing an issue.

### What did you do?

*I tried to install it via cocoapod *

### What did you expect to happen?

*It should install it.*

### I got an error : Unable to find a specification for `SkeletonView`

*Please replace this with of what happened instead.*  

### SkeletonView Environment

**SkeletonView version:*1.0.4* and *1.0.2*
**Xcode version:*9.1*
**Swift version:*3*

**Comment by Juanpe** [comment]
Hi @jamesTheKid, Could you provide your podfile? Which is the minimum iOS version in your project? ```SkeletonView``` needs iOS 9 or bigger

**Comment by superjoo** [comment]
me too!
when use 'pod search SkeletonView' in terminate, shows error ： 
[!] Unable to find a pod with name, author, summary, or description matching `skelentonView`

**Comment by thabofletcher** [comment]
'pod repo update' fixed this for me. 
'pod search SkeletonView' still returns [!] Unable to find a pod with name, author, summary, or description matching `SkeletonView`
'pod search --simple SkeletonView' returns the pod details

**Comment by jamesTheKid** [comment]
'pod repo update' fixed it for me too.
