### ISSUE TITLE
Passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API 

### ISSUE THREAD

**Issue by danqing** [Juanpe/SkeletonView#180]
I'm pretty sure this is a regression in 1.8.1 since I don't recall seeing the error before.

> ```2019-08-27 14:54:44.646515+0800 SkeletonViewExample[89040:9327175] [Unknown process name] Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.```

This can be seen when running the example app.

**Comment by Juanpe** [comment]
Hi @danqing, could you provide which swift and xcode version are you using, please?

**Comment by danqing** [comment]
Hi Juanpe, I'm on Xcode 10.3 and Swift 5 (macOS 10.14.6).

**Comment by Juanpe** [comment]
It was a problem calling the layoutSubviews early. It's fixed on the master branch, it will be included in the next version. 
Thanks for reporting!
