### ISSUE TITLE
Crash in Hero after 1.8.1

### ISSUE THREAD

**Issue by mohpor** [Juanpe/SkeletonView#181]
⚠️ Please fill out this template when filing an issue.

#### 🙏🏼 *Please check if it already exists other issue related with yours.*:   
Nope.

### What did you do?

Nothing.

### What did you expect to happen?

App not crashing.

### What happened instead?

App crashing at a transition initiated by Hero. specifically, when tries to call *layoutIfNeeded()* on a view that is totally not related to Skeleton view.

### Steps to reproduce the behavior

Update SkeletonView to `1.8.1`, cross your fingers and try to find a crash related to this.

### SkeletonView Environment

**SkeletonView version:**
1.8.1
**Xcode version:**
10.3
**Swift version:**
5

It seems like `swizzleLayoutSubviews` breaks something critical to other layouting systems.

**Comment by mohpor** [comment]
Current workaround: Downgrade your pod to `1.8`

**Comment by shial4** [comment]
It does not only crash, but breaks views and collection view from rendering in initial state. 
The views are cut off in a half or displayed in random pieces.

**Comment by Juanpe** [comment]
Hi @shial4, are you using version `1.8` or `1.8.1`. If you are using the version `1.8.1`, please downgrade your pod to `1.8` while the bug is fixing.

**Comment by hrool20** [comment]
I have an error when using cocoa pods. When I try to upgrade to 1.8.1 and 1.8 in podfile, this happens.
![Captura de Pantalla 2019-09-05 a la(s) 16 11 23](https://user-images.githubusercontent.com/13945077/64380980-d04ba180-cff7-11e9-875c-87397a091967.png)


This is my podfile
![Captura de Pantalla 2019-09-05 a la(s) 16 13 05](https://user-images.githubusercontent.com/13945077/64381108-0d179880-cff8-11e9-81c6-05ae998b78d0.png)

**Comment by Juanpe** [comment]
You need to update your local repo. For this execute the command `pod repo update`
