### ISSUE TITLE
Views getting Frozen

### ISSUE THREAD

**Issue by GaneshKumarSelvam** [Juanpe/SkeletonView#183]
Using Pod version 1.8.1, when I push to Other ViewController and pop to particular ViewController or when app goes to foreground and when it becomes active, the gradient views getting frozen, how to keep those in animating position.

<img width="350" alt="Screen Shot 2019-09-10 at 2 41 02 PM" src="https://user-images.githubusercontent.com/22673703/64606131-28f9b080-d3e3-11e9-8bb9-ac2cd9b8073e.png">

**Comment by Juanpe** [comment]
Hi @GaneshKumarSelvam, version 1.8.2 should be solve this bug :)
Please, update your pod and tell me if it's fixed

**Comment by GaneshKumarSelvam** [comment]
@Juanpe Working Fine Thanks
