### ISSUE TITLE
How to custom height line UILabel without change height of UILabel

### ISSUE THREAD

**Issue by phannguyenvn** [Juanpe/SkeletonView#184]
I want to custom height line UILabel without change height of UILabel same facebook
![IMG_0598](https://user-images.githubusercontent.com/15127142/64759559-aa774d00-d561-11e9-8a94-bd06fdb67941.jpg)

**SkeletonView version:** 1.8.1
**Xcode version:** 10
**Swift version:** 5

**Comment by AhmBesbes** [comment]
I have the same problem
