### ISSUE TITLE
Hiding skeleton won't change tableview cell values

### ISSUE THREAD

**Issue by wollodev** [Juanpe/SkeletonView#185]
### What did you do?

I started the TableView example app and selected the `hide skeleton` button.
First, I saw this behaviour in my own app and could easily reproduce it with the Example-App.

### What did you expect to happen?

Showing me the tableView with cells containing ` "cell => \(indexPath.row)"`, e.g., "cell => 1"

### What happened instead?

Cells have the default label "Label" instead. After scrolling, it will change to the right "cell => x" label.

### Steps to reproduce the behavior

1. start TableView Example app
2. press "Hide skeleton"

### SkeletonView Environment

**SkeletonView version:** master branch
**Xcode version:** 10.3
**Swift version:** Swift5

**Comment by wollodev** [comment]
I solved it by 
```swift
tableView.hideSekelton()
tableView.reloadData()
```
but this won't allow me to use animations.

**Comment by pauloec** [comment]
Happening to me as well. Thinking about rolling back to 1.7.

**Comment by rlester** [comment]
I am seeing this as well, seems like it's easier to reproduce in a table with many cells than just a handful.
