### ISSUE TITLE
why Skeleton has been hiddened  but the TextView's text does'n exist 

### ISSUE THREAD

**Issue by qs991011** [Juanpe/SkeletonView#19]
⚠️ Please fill out this template when filing an issue.

### What did you do?

*Please replace this with what you did.*

### What did you expect to happen?

*Please replace this with what you expected to happen.*

### What happened instead?

*Please replace this with of what happened instead.*  

### Steps to reproduce the behavior

*Please replace this with the steps to reproduce the behavior.*

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:**
**Swift version:**

**Comment by Juanpe** [comment]
Hi @qs991011, could you provide more info?
Thanks
