### ISSUE TITLE
Skeletons are misaligned with auto laid out UILabels

### ISSUE THREAD

**Issue by gilbertl-shuffle** [Juanpe/SkeletonView#191]
### What did you do?

I have a ViewController with several auto laid out views. As per picture, the 3 views in question are all horizontally center aligned. One image view and two UILabels.

### What did you expect to happen?

I expected the skeletons to go right where the text goes.

### What happened instead?

The skeletons are misaligned and positioned differently from the text.

After showSkeleton() is called at viewDidLoad: https://imgur.com/ZeeovsY
After hideSkeleton() is called: https://imgur.com/vNEpUjg

### SkeletonView Environment

**SkeletonView version:** 1.8.2
**Xcode version:** 11.0
**Swift version:** 5

**Comment by diogot** [comment]
A similar thing happens to me, but on `viewDidLoad` works fine. The design breaks when I display skeleton after a pull to refresh.

**Comment by ignkarman** [comment]
I am experiencing the same behavior 👍
