### ISSUE TITLE
Custom skeleton color not persistently adaptive

### ISSUE THREAD

**Issue by danqing** [Juanpe/SkeletonView#197]
I have the following code in my app delegate that customizes my skeleton color:

```swift
SkeletonAppearance.default.tintColor = Color.skeleton
SkeletonAppearance.default.gradient = SkeletonGradient(baseColor: Color.skeleton)
```

Here `Color.skeleton` is an adaptive color that has light/dark mode. And this works - if I open the app in dark mode, the skeletons show up in the dark color.

However, when I background the app, toggle the system light/dark switch (or if it auto changes at sunrise/sunset), then come back to the app, the skeleton still keeps the original color and doesn't automatically switch to the color for the opposite appearance.

All other parts of the app can adjust without problem (and with a nice animation even). It looks SkeletonView somehow caches an absolute color instead of the adaptive parent color in this case.

**Comment by danqing** [comment]
Looks like #199 has fixed this? Can we have a new release please @Juanpe ? Thanks!

**Comment by Juanpe** [comment]
Hi @danqing, finally, request #199 has been merged, so you can update the pod, to check if this issue is solved, please?

**Comment by danqing** [comment]
Works great. Thanks!

**Comment by kristofferanger** [comment]
I still have this issue (version 1.30.4). Was it never fixed or has it reappeared?
