### ISSUE TITLE
How to work with SkeletonView and UITableViewDataSource

### ISSUE THREAD

**Issue by ramonsgds** [Juanpe/SkeletonView#20]
I am trying to implement a tableview with SkeletonView but it's giving me a compile-time error saying that my UIViewController does not conform to protocol UITableViewDataSource. Before trying to implement SkeletonView it was working perfect. 

I have the following in my view controller:

```
extension ChooseListViewController : SkeletonTableViewDataSource {
    func numSections(in collectionSkeletonView: UITableView) -> Int {
        return 1
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return food.count
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, cellIdenfierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
       /* let cell = tableView.dequeueReusableCell(withIdentifier: "FoodCell") as! ChooseTableViewCell
        
        cell.delegate = self
        
        cell.food = foods[indexPath.row]
        
        return cell*/
        
        return "FoodCell"
    }
}

```

I commented how my code was beforehand. What I don't understand is how do you expect me to customize my cell if I should rather return only its identifier?

**Comment by B4V4-G** [comment]
I think you need to implement this method as well

`func collectionSkeletonView(_ skeletonView: UITableView, cellIdenfierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier`

Please check the example, this method is implemented there like this:

```
func collectionSkeletonView(_ skeletonView: UITableView, cellIdenfierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
        return "CellIdentifier" 
       //I think in your case it would be 
       //return "FoodCell"
}
```

**Comment by B4V4-G** [comment]
Hi,

You can easily customize your cell, skeleton view (as the name suggests is only for view) , you are missing the main method of tableview datasource 

`func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell`

simply return the cell for your tableview from this method. I think your implementation will look like this:

```
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    return tableView.dequeueReusableCell(withIdentifier: "FoodCell") as! ChooseTableViewCell
}
```

**Comment by Juanpe** [comment]
Hi @ramonsgds, as @B4V4-G, you need to implement the UITableViewDataSource protocol methods. 
In your case, ```ChooseListViewController```'s extension should look like this:
```swift

extension ChooseListViewController : SkeletonTableViewDataSource {
    
 
    func collectionSkeletonView(_ skeletonView: UITableView, cellIdenfierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
        return "FoodCell"
    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return food.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "FoodCell") as! ChooseTableViewCell
        
        cell.delegate = self
        cell.food = foods[indexPath.row]
       
        return cell
    }
}
```

**Comment by ramonsgds** [comment]
I had figured it out after some tries. Thank you @Juanpe !
