### ISSUE TITLE
Tableview hideSkeleton() is Don't work？

### ISSUE THREAD

**Issue by cs571393** [Juanpe/SkeletonView#201]
I called hideSkeleton() when I got the data after the network request. But the Skeleton on the cell did not disappear.

I hope I can fix this bug, otherwise I wouldn't be able to use SkeletonView at all
### Steps to reproduce the behavior

**SkeletonView version:1.8.2
**Xcode version:10.2
**Swift version:swift5

**Comment by Juanpe** [comment]
Hi @cs571393, try to reloadData of the tableView after hiding the skeleton. It seems is a bug in the last version

**Comment by cs571393** [comment]
@Juanpe The new problem is that the Tableview hideSkeleton() doesn't slide after it

**Comment by cs571393** [comment]
@Juanpe The Tableview hideSkeleton() doesn't scroll, but the cell can still be clicked

**Comment by cs571393** [comment]
@Juanpe https://v.youku.com/v_show/id_XNDQwMTk0MTM0OA==.html?spm=a2hzp.8253869.0.0

**Comment by shubham14896** [comment]
Does not work even after reload data, case for collection view too, but cells are clickable.
Kindly update / fix #urgent

**Comment by ahmadsallam** [comment]
same problem here i solve it by adding cell.hideSkeleton() in CellForRow when it's not requesting

**Comment by 29satnam** [comment]
> same problem here i solve it by adding cell.hideSkeleton() in CellForRow when it's not requesting

Life saver!
