### ISSUE TITLE
UIView.layoutSubviews swizzle is messing with standard controls

### ISSUE THREAD

**Issue by ricardopereira** [Juanpe/SkeletonView#202]
# What did you do?

Enabled SkeletonView in some of `UIViewController`'s.

### What did you expect to happen?

I expected that SkeletonView didn't messed with current `UIView`'s layout.

I.e.: I have a view controller with an `AVRoutePickerView` and intermittently the layout of that control gets messed:

![Screenshot 2019-10-17 at 12 21 18](https://user-images.githubusercontent.com/3541185/67040161-c9e23680-f11a-11e9-8f7a-aabb7fe1d7f4.png)

The constraints are fine but the route picker is broken:

![Screenshot 2019-10-17 at 12 20 39](https://user-images.githubusercontent.com/3541185/67039319-fa28d580-f118-11e9-873f-90c7a590da20.png)

After removing all imports of `SkeletonView`, things started to function properly.

### Possible solution

🥴 After 5h of my day trying to understand what was going on, I found out the problem. So, SkeletonView is [swizzling the `UIView.layoutSubviews` method](https://github.com/Juanpe/SkeletonView/blob/01d68190abb826ef1ac825ef38372dba9dfc694a/Sources/SkeletonView.swift#L258-L268) and besides that it's doing it inside of an async call that, in my opinion, it's risky and turns this solution into a code smell.

Please give the user the possibility to **NOT** use swizzling hacks something like Firebase does:
> Developers who prefer not to use swizzling can disable it by adding the flag FirebaseAppDelegateProxyEnabled

### Steps to reproduce the behavior

Just incorporate the `AVRoutePickerView` in a view controller.

### SkeletonView Environment

**SkeletonView version:** 1.8.2
**Xcode version:** 11.1
**Swift version:** Swift 5.1

**Comment by ricardopereira** [comment]
This is one of the reasons I hate swizzling because it turns things very unpredictable 😩

**Comment by AlexCogniteq** [comment]
I have the same "magic" issues in the app after enabling skeletons for some views.
Problem definitely comes from method swizzling and possible because **super** implementation is not called. UI issues disappeared after I added **self.skeletonLayoutSubviews()**:
```swift
@objc func skeletonLayoutSubviews() {
     layoutSkeletonIfNeeded()
     self.skeletonLayoutSubviews()
}
```

**Comment by santoshios** [comment]
I am facing similar issue after using skeleton view.
My view before using skeletonView : 
![Simulator Screen Shot - iPhone 8 - 2019-11-20 at 15 59 28](https://user-images.githubusercontent.com/52994138/69231434-10f69800-0baf-11ea-89c0-1c86b966e5dc.png)

views modified in viewDidLayout() method does not layout properly : 
![Simulator Screen Shot - iPhone 8 - 2019-11-20 at 15 59 45](https://user-images.githubusercontent.com/52994138/69231517-3b485580-0baf-11ea-8060-b6a3aa79115e.png)

I tried @AlexCogniteq solution, but that did not make any difference

**Comment by crabman448** [comment]
I also had some issues after swizzling was added. So I rolled back to the version that doesn't have swizzling

**Comment by santoshios** [comment]
@crabman448 Which version of skeletonView are you using ?

**Comment by crabman448** [comment]
@santoshios awizzling was introduced in 1.8.1. So I use 1.8.0

**Comment by Juanpe** [comment]
Hi all, the latest version (1.14.0) contains a fix to solve this problem. I'm going to close this issue, feel free to open a new one if you still facing the problem
