### ISSUE TITLE
showSkeleton not working properly

### ISSUE THREAD

**Issue by asteiman** [Juanpe/SkeletonView#204]
⚠️ Please fill out this template when filing an issue.

### What did you do?

`view.showSkeleton()` in `viewDidLoad`

### What did you expect to happen?

Show skeleton on views only marked as `isSkeletonable`

### What happened instead?

The whole view of the viewController got the skeleton

### Steps to reproduce the behavior

I have the following structure:
UIViewController
|-- UIView
|    |-- UIScrollView, edges pinned to superview
|    |    |-- UIStackView, edges pinned to superview
|    |    |    |-- UIView
|    |    |    |    |-- UILabel **marked as Skeletonable**

note:
If I call `showSkeleton()` on scrollView or stackView, nothing at all happens

### SkeletonView Environment

**SkeletonView version:** 1.8.2
**Xcode version:** 11
**Swift version:** 5

**Comment by pavlyhabashy** [comment]
Did you figure this out? I'm having the same issue.

**Comment by asteiman** [comment]
@pavlyhabashy unfortunately I decided not to use this library because of this issue and lack of support from developer

**Comment by pavlyhabashy** [comment]
https://medium.com/@jaydeepvora/skeletonview-animation-ade973655d03

I found this article to be helpful. However, did you find a replacement?

**Comment by asteiman** [comment]
@pavlyhabashy i followed that article.

No, for now just using the old fashioned activity indicator, i know is not the same though

**Comment by pavlyhabashy** [comment]
:/

**Comment by Juanpe** [comment]
Hi! You need to set skeletonable the viee of the view controller. Could you set the property please?
