### ISSUE TITLE
Tableview cell for reuse.cell again showSkeleton

### ISSUE THREAD

**Issue by cs571393** [Juanpe/SkeletonView#205]
Tableview cell for reuse.cell again showSkeleton
The SkeletonView/TableViewDemo has same situation

**SkeletonView version:1.8.2 branch:master
**Xcode version:10.2
**Swift version:swift5

**Comment by X901** [comment]
This is the must anoying things all my users complainant about this .
I didn't find any solution , I tried every versions but it still not fixed .

**Comment by X901** [comment]
I found the sloution 

add `cell.hideSkeleton()`
on `cellForRowAt`

https://github.com/Juanpe/SkeletonView/issues/201#issuecomment-547779319
