### ISSUE TITLE
Not drawing lines to simulate multiline label 

### ISSUE THREAD

**Issue by Recouse** [Juanpe/SkeletonView#206]
### What did you do?
Made `UILabel` skeletonable with `numberOfLines = 0`. The label has width and height constraints.

### What did you expect to happen?
Drawing lines like in that example https://github.com/Juanpe/SkeletonView#-multiline-text

### What happened instead?
One big rectangle instead of multiple lines

### SkeletonView Environment

**SkeletonView version:** 1.8.2
**Xcode version:** 11.1
**Swift version:** 5.1

**Comment by ciccioska** [comment]
Hi, I got the same issue if I select numberOfLines = 1. So try to verify if in the Storyboard there is a place where you override numberOfLines = 0.

**Comment by beaneyios** [comment]
This is not fixed. Same issue here - tried `numberOfLines = 0`, `numberOfLines = 1`, `numberOfLines = 15`, still just shows a big rectangle.

**Comment by ricardoisidro** [comment]
Same, I had to replace labels for textViews in order to overcome this problem.

**Comment by wongzigii** [comment]
Same issue here, any update ?

**Comment by dimkoy** [comment]
Try to set something like "       " to label and call `layoutIfNeeded()` just before `showAnimatedSkeleton`

**Comment by Juanpe** [comment]
Hi, are you using the latest version (1.11.0)?

**Comment by Recouse** [comment]
@Juanpe checked with the latest version (1.11.0). It's not working with `numberOfLines = 0`, but works for any other values.

**Comment by PramodShukla10** [comment]
any one got solution?

**Comment by andrewfirsenko** [comment]
> 

Try set skeletonTextNumberOfLines
