### ISSUE TITLE
Table cell data is not refresh after hiding skeleton. Worked on 1.7

### ISSUE THREAD

**Issue by gloryluu** [Juanpe/SkeletonView#210]
**SkeletonView version:*1.8.2*
**Xcode version:*11.2.1*
**Swift version:*5.0*

**Comment by mahmoudibra** [comment]
I'm facing the same issue too

**Comment by Juanpe** [comment]
Please, could you provide more info? thanks

**Comment by nandogameiro** [comment]
You might need make sure you hideSkeleton before tableview reloadData

```
view.hideSkeleton()
tableView.reloadData()
```

**Comment by lordzsolt** [comment]
I had the same issue. If you are not skeletonizing the whole table view, but only UITableViewCells that have skeletons inside them, make sure you do hide the skeletons first, before updating anything inside your view.

Ex: 
```
struct CellData {
    var title: String
}

class Cell: UITableViewCell {
    var cellData: CellData {
   		didSet {
   			titleLabel.hideSkeleton() // Make sure you call this !BEFORE! you change `titleLabel.text`
   			titleLabel.text = cellData.title
   		}
   	}
}
```
