### ISSUE TITLE
SkeletonView overrides isUserInteractionsEnabled property

### ISSUE THREAD

**Issue by MikeGlotov** [Juanpe/SkeletonView#215]
### What did I do?

I Implemented table view with cells, containing dynamically sized UITextViews. These text views have been set up not to receive toches by turning _isUserInteractionsEnabled_ property off.

### What did I expect to happen?

_isUserInteractionsEnabled_ property value doesn't change if the skeleton is shown.

### What happened instead?

_isUserInteractionsEnabled_ property value changes if the skeleton is shown, because of that table cell can't receive touches.

### Steps to reproduce the behavior

Create a plain table view with a cell and place a UITextView inside of the cell. Disable touches on the text view, then show and hide a skeleton. After that, we can observe that for some reason UItextView is able to receive touches even though we disabled them beforehand.

### SkeletonView Environment

**SkeletonView version:** 1.8.1
**Xcode version:** 10.3 / 11.2.1
**Swift version:** Swift 5

**Comment by Juanpe** [comment]
It's fixed. It will available on the next version (1.8.3)

**Comment by MikeGlotov** [comment]
@Juanpe Thank you! 🙏
