### ISSUE TITLE
HideSkeleton causing crash in quickly-switching views

### ISSUE THREAD

**Issue by Warwolfer** [Juanpe/SkeletonView#219]
I used skeletonview in a UItableview, which is called from a page view controller. The skeletonview waits for async API call before hiding the skeleton, but meanwhile user can swipe the page view left and right. Rapidly changing views will cause 
"NSInternalInconsistencyException - datasource not set " crash. This doesn't happen with Collection View, only Table View.

I've tried :
- Implementing UITableViewDataSource too
- Setting datasource to self on ViewDidLoad
- Setting the datasource to normal UITableViewDataSource self

Not calling HideSkeleton resolved all the crash I have.

SkeletonView version: 1.8.2
Xcode version: 11.2.1
Swift version: 5

**Comment by irfanCheetah** [comment]
@Warwolfer did you find any solution, i am also having same crash

**Comment by Warwolfer** [comment]
@irfanCheetah unfortunately no, I decided not to use the skeletonview in that particular pageview.
