### ISSUE TITLE
Unpredictable spacing with UILabels

### ISSUE THREAD

**Issue by austboston** [Juanpe/SkeletonView#222]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I'm using SkeletonView to go over my UILabel inside of a UITableViewCell. This cell is on a view controller presented modally. 

### What did you expect to happen?

The SkeletonView should go over my label as expected. It does this the first time the modal view is launched, but every other time...

### What happened instead?

The SkeletonView presents correctly every time the first time, but then every time after, is incorrectly spaced and looks bad.

### Steps to reproduce the behavior

Reply for more info. Can't seem to crack this one.

Correctly looks like this the first time shown:
<img width="124" alt="Screen Shot 2019-12-10 at 11 09 12 PM" src="https://user-images.githubusercontent.com/44538463/70596018-176ea300-1ba2-11ea-9c79-524a27596800.png">
Incorrectly looks like this every time after:
<img width="132" alt="Screen Shot 2019-12-10 at 11 11 59 PM" src="https://user-images.githubusercontent.com/44538463/70596195-78967680-1ba2-11ea-99e6-d29e33c7a650.png">

### SkeletonView Environment

**SkeletonView version:** latest
**Xcode version:** 11.2
**Swift version:** 5.1

**Comment by Juanpe** [comment]
Hi @austboston, could you provide more info about, please? I mean, you always show the modal in the same way?

**Comment by austboston** [comment]
Hey Juanpe,

I apologize, but seeing as how this issue was some time ago, I’ve since found an alternative solution and can no longer recall the specific details of this problem.

Thanks for sharing your code with the world, and good luck.

Austin Blake

**Comment by Juanpe** [comment]
Ok! Sorry for the late response 😕
