### ISSUE TITLE
On UICollectionView, the SkeletonView won't show properly

### ISSUE THREAD

**Issue by SuperCrazyCodeMan** [Juanpe/SkeletonView#223]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I use this code, but nothing show up. 
**func collectionSkeletonView(_ skeletonView: UICollectionView, supplementaryViewIdentifierOfKind: String, at indexPath: IndexPath) -> ReusableCellIdentifier?**

### What did you expect to happen?

I expect that skeletonview work properly for the header on UICollectionView

### What happened instead?

SkeletonView won't work for the header UICollectionView

**Comment by Juanpe** [comment]
Hi @SuperCrazyCodeMan, the latest version has changes related to headers and footers views, could you install this version, to check if this issue is solved?
