### ISSUE TITLE
texts of Labels in TableView Cell don't get new value after stopping animation

### ISSUE THREAD

**Issue by iliakhaburdzania** [Juanpe/SkeletonView#226]
### What did you do?

I was trying to apply skeleton animation to cell with 2 labels 

### What did you expect to happen?

The labels in cell to get new value after stopping and reloading data with your method

### What happened instead?

the labels text value didn't get new values when I configure with reload that happens with your method `func hideSkeleton(reloadDataAfter reload: Bool = true, transition: SkeletonTransitionStyle = .none)` instead it gets the value that I set default in Xib file
(While debugging the texts get new value but visually doesn't have any effect before I reload tableview "manually")

### Steps to reproduce the behavior

I think it might be problem with iOS 13+ 

### SkeletonView Environment

**SkeletonView version:** 1.8.2
**Xcode version:** 11
**Swift version:** 5

**Comment by harmittaa** [comment]
Did you find a reason and fix for this issue?

**Comment by danielrobleM** [comment]
Hi, I just realized that i have the same issue.
I fixed just set text after call `hide Skeleton()`. 
These is fixed on 1.8.2 ? 🤔

**Comment by ruby109** [comment]
Same issue.

**Comment by ldt25290** [comment]
Same issue here on 1.8.6 and 1.8.7.

**Comment by huylv-teko** [comment]
same problem here, why this issue closed :(
