### ISSUE TITLE
Set corner radius for image view

### ISSUE THREAD

**Issue by huylv-teko** [Juanpe/SkeletonView#228]
### What did you do?
I want to set corner for **image view**'s skeleton, but there is no option in xib 
### What did you expect to happen?
A field in xib file to define corner radius
### SkeletonView Environment

**SkeletonView version: 1.8.2

**Comment by BossOz** [comment]
the best will be to set the corner radius to everything, just to keep the stile of the skeleton the same.

**Comment by Juanpe** [comment]
Hi @huylv-teko, you can round the image using the native methods, `maskToBounds` and `cornerRadius` of the layer. Check issue #13 for more details. Thanks
