### ISSUE TITLE
Problem with UIStackView

### ISSUE THREAD

**Issue by robinkunde** [Juanpe/SkeletonView#23]
### What did you do?

I have a UIStackView that contains several labels. I called showSkeleton() on all the labels.

### What did you expect to happen?

Each label shows up skeletonized.

### What happened instead?

Because SkeletonView sets the text of each label to nil, UIStackView sets the height of each label to 0 and lays them out on top of each other.

### SkeletonView Environment

**SkeletonView version:**
1.0.4
**Xcode version:**
9.2
**Swift version:**
4

**Comment by Juanpe** [comment]
Hi @robinkunde, sorry for the delay in the answer. I've checked this behaviour and you're right, it's a bug. So, I'm going to add this bug in the backlog and I'm going to try to fix as soon as possible.

**Comment by jmjordan** [comment]
I am also having this issue. Are there any updates?

**Comment by weiran** [comment]
@jmjordan my workaround for `UITableView`s is to have a skeleton cell prototype that doesn't use `UIStackView` and show that instead.

**Comment by ZachOrr** [comment]
One workaround is to wrap your labels in a UIView. It's subpar, but it gets you most of the way there.

**Comment by giantramen** [comment]
https://github.com/Juanpe/SkeletonView/pull/73

**Comment by Juanpe** [comment]
Could you check if this bug is solved?
Thanks!

**Comment by robinkunde** [comment]
Sorry, I'm not using SkeletonView at the moment, but I looked at the diff at that should take care of it. You can close the issue if that works for you.
