### ISSUE TITLE
Showing animation can not render UIView's border?

### ISSUE THREAD

**Issue by iWECon** [Juanpe/SkeletonView#232]
### What did you do?

I have a View with Border.

### What did you expect to happen?

The Border always not be rendered when startGradientAnimation.

### Steps to reproduce the behavior

Create a UIView, and set borderColor, borderWith, borderOpacity, then use SkeletonView's showGradientAnimation show it.
The view's border is not hidden or render.

### SkeletonView Environment

**SkeletonView version: 1.8.2**
**Xcode version: 11.3**
**Swift version: 5**

**Comment by iWECon** [comment]
I checked SkeletonView's APIs, it contains SkeletonFlowDelegate.
The delegate's two methods that can help me resolve this problem, but it's not `Public`.

**Comment by iWECon** [comment]
I want to hide border use `willBeginShowingSkeletons(rootView:)`, and show border use `willBeginHidingSkeletons(rootView: UIView)`.

**Comment by iWECon** [comment]
![image](https://user-images.githubusercontent.com/16604027/71653963-1d534080-2d6a-11ea-9ced-c3364429ddef.png)
The screenshot contains two UIView with `border`.

**Comment by iWECon** [comment]
![image](https://user-images.githubusercontent.com/16604027/71654074-a1a5c380-2d6a-11ea-86b6-1173665d2b0e.png)

The screenshot contains two UIView with `border`.

**Comment by iWECon** [comment]
![image](https://user-images.githubusercontent.com/16604027/71654226-9737f980-2d6b-11ea-8e13-13b1e335b328.png)

Now, I find the `RecoverableViewState`, maybe you can add a line code with `self.layer.borderWidth`.

**Comment by Juanpe** [comment]
Hi @iWECon, SkeletonView now has notications using `NotificationCenter`. This change was included in version 1.8.5.

Thanks!
