### ISSUE TITLE
Unable to use `identifierForHeaderInSection` and `viewForHeaderInSection`

### ISSUE THREAD

**Issue by MamtaKukreja** [Juanpe/SkeletonView#235]
### What did you do?

Used `heightForHeaderInSection`, `viewForHeaderInSection` with `SkeletonTableViewDelegate`

### What did you expect to happen?

Populate header of tableview through `viewForHeaderInSection`

### What happened instead?

App crashed.

### Steps to reproduce the behavior

Install pod 1.8.2 and try to use `viewForHeaderInSection` and `heightForHeaderInSection` with `SkeletonTableViewDelegate`. If `UITableViewDelegate` is used instead of `SkeletonTableViewDelegate` , with the `SkeletonTableViewDataSource`, then the `viewForHeaderInSection` shows a warning but does not execute at all

### SkeletonView Environment

**SkeletonView version: 1.8.2 pod**
**Xcode version: 11.2.1**
**Swift version: 5**

**Comment by Juanpe** [comment]
duplicate #243
