### ISSUE TITLE
SkeletonView with 'willDisplayHeaderView'

### ISSUE THREAD

**Issue by Vetas-R** [Juanpe/SkeletonView#237]
### What did you do?

I'm trying to use SkeletonView with UITableView's 'willDisplayHeaderView'. I've implemented 'SkeletonTableViewDataSource' and 'UITableViewDelegate' protocols.

### What did you expect to happen?

I expected the standard UITableViewDelegate behavior.

### What happened instead?

 In 'UITableViewDelegate' protocol I use 'titleForHeaderInSection', 'willDisplayHeaderView', 'heightForHeaderInSection' but, unfortunately, only the last one is called when tableView's skeleton animation is active. So, there is no titles on headers, but headers have a correct height. 

### Steps to reproduce the behavior

Implement SkeletonTableViewDataSource and said methods.

### SkeletonView Environment

**SkeletonView version:  1.8.2**
**Xcode version: 11.3**
**Swift version: 5**

**Comment by Vetas-R** [comment]
There's mistake in my issue. I have the last (1.8.2) version of SkeletonView

**Comment by Juanpe** [comment]
Hi @Vetas-R, note that the protocol that you should conform is `SkeletonTableViewDelegate` instead of `UITableViewDelegate`. Could you check it, please?
