### ISSUE TITLE
Skeleton not rendered properly for one line label

### ISSUE THREAD

**Issue by BossOz** [Juanpe/SkeletonView#241]
### What did you do?

I setup the "lines corner radius" and "the last line fill percent" from the Storyboard for a label with only one line.

### What did you expect to happen?

I would like to see one skeleton line, filled properly, with the asked corner radius.

### What happened instead?

The "lines corner radius" and the "last line fill percent" are not applied and I see a squared cornered line full filled.

### Steps to reproduce the behavior

- Go to the storyboard
- Insert a label
- Set the "lines" = 1
- Set the "lines corner radius" = 5
- Set the "last line fill percent" = 10
- Write the proper code to render the skeleton in the view controller
- Run

### SkeletonView Environment

**SkeletonView version: 1.8.2**
**Xcode version: 11.2.1**
**Swift version: 5**

**Comment by BossOz** [comment]
Here a picture

<img width="424" alt="Schermata 2020-02-11 alle 20 28 48" src="https://user-images.githubusercontent.com/4025510/74271529-55f11d00-4d0d-11ea-95dc-b1a95cc97985.png">

**Comment by Juanpe** [comment]
Hi @BossOz, there was a bug related to this. It's fixed, so now you can update the pod to version 1.8.4, and you shouldn't have the problem.

Please, confirm that is it solved and close this issue :)

**Comment by BossOz** [comment]
Hello @Juanpe,

I have updated the project with the new version but nothing is changing.
https://github.com/BossOz/TestSkeletonView

here the configuration of my label in the storyboard
<img width="262" alt="Schermata 2020-02-12 alle 22 31 32" src="https://user-images.githubusercontent.com/4025510/74379129-86a58500-4de7-11ea-8c8e-1a4e722ae628.png">

And here the result
<img width="417" alt="Schermata 2020-02-12 alle 22 32 47" src="https://user-images.githubusercontent.com/4025510/74379171-9ae98200-4de7-11ea-89ef-7ea62ba7451a.png">

The first line still squared.

What am I doing wrong?

**Comment by Juanpe** [comment]
Hi @BossOz, I've downloaded the project, and it's working fine. I don't modify anything :/ well, just I've removed the line spacing for the second label, but it's not relevant for your issue.

Here is the project: 
[TestSkeletonView-master.zip](https://github.com/Juanpe/SkeletonView/files/4199718/TestSkeletonView-master.zip)

**Comment by BossOz** [comment]
Hello @Juanpe,

this sound like something wrong on the pod installation because I downloaded your attachment and is ok.
I tried to remove the dependency from the pod, pod install, and install it back again and now all is working good.
Thank your for your time!

**Comment by Juanpe** [comment]
Hi! I had the same problem afternoon. I cleaned the build folder and then it’s worked fine 👍
