### ISSUE TITLE
Header and footer identifier delegate methods not getting called

### ISSUE THREAD

**Issue by MamtaKukreja** [Juanpe/SkeletonView#243]
### What did you do?

Set the header and footer identifiers through the `SkeletonTableViewDelegate` methods

### What did you expect to happen?

To see headers and footers of tableview sections as skeletonables

### What happened instead?

Headers and footers are not visible at all as skeletonables. The header and footer directly appear when they contain data instead

### Steps to reproduce the behavior

Set header and footer identifiers from delegate methods `identifierForHeaderInSection` and `identifierForFooterInSection`.
These methods are not getting called at runtime.

### SkeletonView Environment

**SkeletonView version: pod 1.8.3**
**Xcode version: 11.2.1**
**Swift version: 5.0**

**Comment by Juanpe** [comment]
Hi @MamtaKukreja, could you update the pod and check if the issue still happens? I've checked the example and the methods of the delegate are called :/

Thanks

**Comment by MamtaKukreja** [comment]
@Juanpe I updated pod but still facing the same issue. The updated pod version is 1.8.5.

**Comment by Juanpe** [comment]
Hi! Taking into account this [comment](https://github.com/Juanpe/SkeletonView/issues/241#issuecomment-586497584), could it be your problem? 

Sometimes, incremental builds, cache, or other problems can affect. A possible solution is to clean the build folder.

Thanks and sorry for the inconvenient
