### ISSUE TITLE
Skeletons stopped working in version 1.8.3

### ISSUE THREAD

**Issue by fedorpashin** [Juanpe/SkeletonView#245]

**Comment by Juanpe** [comment]
Hi @fedorpashin, in version 1.8.3, it has been included a critical change. Now, you need to set as skeletonable the root view. So the view used to show the skeleton view is skeletonable too?

**Comment by fedorpashin** [comment]
The problem was that I left "Default" state for "Is Skeletonable" property of my skeletonable views. It was working fine until the last version.

**Comment by fedorpashin** [comment]
Also, the recursive skeleton activation is not working when I call it after any direct activation. Here is the demo: [Samples.zip](https://github.com/Juanpe/SkeletonView/files/4179700/Samples.zip).

**Comment by fedorpashin** [comment]
Also, the recursive skeleton activation is not working when I call it after any direct activation. Here is the demo: [Samples.zip](https://github.com/Juanpe/SkeletonView/files/4179700/Samples.zip).

**Comment by Juanpe** [comment]
Hi @fedorpashin, you don't need to activate the skeleton recursively; the library does it.
```swift
topLabel.showSkeleton()
view.showSkeleton()
```
It's not needed because `topLabel` is inside the `view`, so if you activate the skeleton using the `view`, the `topLabel` also will be activated.

**Comment by fedorpashin** [comment]
I know, but I have to do this to make the custom width for label skeleton as I mentioned in the issue #246.
