### ISSUE TITLE
Does SkeletonView work with  DZNEmptyDataSet? 

### ISSUE THREAD

**Issue by sourabhsharmait** [Juanpe/SkeletonView#249]
[https://github.com/dzenbot/DZNEmptyDataSet](DZNEmptyDataSet)

Can I use both third party libraries in my class? 
### What did you do?
After using both the shimmer effect is not showing. Ony empty data source handing is working by  using DZNEmptyDataSet
### What did you expect to happen?

I expect to work both.. shimmer effect and when no data available then DZNEmptyDataSet will show the placeholder.

### What happened instead?

DZNEmptyDataSet is showing placeholder but no shimmer effect.

### Steps to reproduce the behavior

When we use both libraries in the same controller for table view or collectionview.

### SkeletonView Environment

**SkeletonView version:** latest
**Xcode version:** 11.3.1
**Swift version:** 5.0

**Comment by Juanpe** [comment]
Hi @sourabhsharmait, could you provide more info about how are you calling both hide skeleton and show empty methods?

**Comment by sourabhsharmait** [comment]
Working fine... there was some issue in handling the delegate methods.

Thank for your response
