### ISSUE TITLE
Data is not shown properly

### ISSUE THREAD

**Issue by BossOz** [Juanpe/SkeletonView#252]
### What did you do?

Calling the `self.view.showAnimatedGradientSkeleton(transition: .crossDissolve(0.25))` at `viewDidLoad()` and change the texts of two labels.

```
self.oneLabel.text = "This is the label number one"
self.twoLabel.text = "And this is the label number two!!"
```

After 3 seconds, hide the skeleton
```
DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
   self.view.hideSkeleton(reloadDataAfter: true, transition: .crossDissolve(0.25))
}
```

### What did you expect to happen?

I expect, once the skeleton is gone, that the labels present the desired texts.

### What happened instead?

The labels still have the text set in the Storyboard.

### Steps to reproduce the behavior

Here a sample project
[https://github.com/BossOz/TestSkeletonView](https://github.com/BossOz/TestSkeletonView)

### SkeletonView Environment

**SkeletonView version:** 1.8.3
**Xcode version:** 11.3.1
**Swift version:** 5

Please help! What I'm missing?
Thank you!

**Comment by Juanpe** [comment]
Hi @BossOz, I've checked your project, and the problem is that you are setting the data before hiding the skeleton. So to solve this problem, you should set the data after calling the `hideSkeleton` method.

Your code should look like this:

```swift
 DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
    self.view.hideSkeleton(reloadDataAfter: true, transition: .crossDissolve(0.25))
    self.oneLabel.text = "Cione"
    self.twoLabel.text = "Ciaone ancora ancorone!"
}
```
Please, let me know if the issue is solved with this code :)

**Comment by BossOz** [comment]
Yesss! Thank you!
