### ISSUE TITLE
SkeletonView within Stackview using custom UITableViewCell class displays not as expected

### ISSUE THREAD

**Issue by bribar** [Juanpe/SkeletonView#253]
Continuation of this issue https://github.com/Juanpe/SkeletonView/issues/106

I have a similar issue with stackviews in the table cell. The animated gradient bar fills the whole cell, therefore making it look like all the cells are one giant gradient animation. I'm using a custom table cell with a xib. The stackview has constraints of 10 all around relative to the cell xib view. Single label within stackview

If I take the label out of the stackview and constrain it, it works as expected with only the label being the animated gradient.

I have a example project on Github of the issue if necessary

**SkeletonView version:** Latest
**Xcode version:** Latest
**Swift version:**Latest

**Comment by Juanpe** [comment]
Hi @bribar, I've downloaded your project from Github, and I've made some changes, and I think that it is working fine now. Please, download your project updated from [here](http://cdn.juanpecatalan.com/skeleton/SkeletonView-master.zip).

The main change was to move the `showGradientAnimatedSkeleton` call from the `viewDidLayoutSubviews` to the `viewDidAppear` method. Also, I've set the tableView as skeletonable.

Let me know if it's solved :)

**Comment by bribar** [comment]
@Juanpe That seems to solve it, thanks!

But it seems like a bug or docs aren't real clear. Docs say that you can declare a tableView skeletable in code or IB, I chose the code option and declared in viewDidAppear tableView.isSkeletonable = true. I see you set it in IB which made the difference.

Previously, I moved tableView.showAnimatedGradientSkeleton() to viewDidAppear and also tried viewDidLayoutSubviews, to no avail. 

Seems like you have to use IB in this case and have showAnimatedGradientSkeleton() in viewDidAppear for it to work, otherwise no bueno.

**Comment by bribar** [comment]
@Juanpe It looks like you also changed the IB Is Skeletonable settings for most of the layers in the Table2Cell xib. If I change them to only have the Label is skeletonable is doesn't work even though I have your two suggestions set.

I really only want the Label as skeletonable. Is this not possible?

**Comment by Juanpe** [comment]
> @Juanpe That seems to solve it, thanks!
> 
> But it seems like a bug or docs aren't real clear. Docs say that you can declare a tableView skeletable in code or IB, I chose the code option and declared in viewDidAppear tableView.isSkeletonable = true. I see you set it in IB which made the difference.
> 
> Previously, I moved tableView.showAnimatedGradientSkeleton() to viewDidAppear and also tried viewDidLayoutSubviews, to no avail.
> 
> Seems like you have to use IB in this case and have showAnimatedGradientSkeleton() in viewDidAppear for it to work, otherwise no bueno.

Yep, totally right. I've checked and the problem is if you set skeletonable in code, you need to set skeletonable the table cell in code too. Then it's working for me in your example. But just only for table view and the cell, for the rest of the elements, you can use IB to set the property. I don't know exactly why, but yes. I need to investigate a little more about that.

```swift
/// Table2Cell.swift

override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
        isSkeletonable = true
        tableCellLabel.clipsToBounds = true
    }
```

> @Juanpe It looks like you also changed the IB Is Skeletonable settings for most of the layers in the Table2Cell xib. If I change them to only have the Label is skeletonable is doesn't work even though I have your two suggestions set.
> 
> I really only want the Label as skeletonable. Is this not possible?

About this, you only need to set the cell, the stackview and the label as skeletonable. You can find more info [here](https://github.com/Juanpe/SkeletonView#-hierarchy)

**Comment by mo3bius** [comment]
Hi @Juanpe :) I have a problem with stackview. I tried to set clipsToBound to labels but a label is cutting in half. I also tried to not set clipsToBound but the right label (as you can see in my project) start far from right constraint.

Where am I doing wrong?

Target: iOS 13.2
Pod Version: 1.8.6
[Project sample](https://drive.google.com/open?id=1a4rFgwQ_LbJTlg0CPSK4UDPWBLgMUjSG)

**Comment by bribar** [comment]
@mo3bius check out my comment here https://github.com/Juanpe/SkeletonView/issues/236#issuecomment-594249919

I saw a similar issue with my labels when I didn't have this configured correctly. Might be a fix for you too.
