### ISSUE TITLE
Unit test problem when using SkeletonView

### ISSUE THREAD

**Issue by bentahyar** [Juanpe/SkeletonView#257]
⚠️ Please fill out this template when filing an issue.

### What did you do?

Doing a unit test

### What did you expect to happen?

The value of `numberOfItemsInSection` returned correctly

### What happened instead?

My collectionview always return the `numberOfItemsInSection` for skeletonview instead of the value that i return

### Steps to reproduce the behavior

Do a unit test returning the value of `numberOfItemsInSection` while implementing SkeletonViewDataSource

### SkeletonView Environment

**SkeletonView version: 1.8.3**
**Xcode version: 11.3**
**Swift version: 4**

**Comment by Juanpe** [comment]
Hi, let me check it

**Comment by Juanpe** [comment]
Hi @bentahyar, the next version skips the replacement of the original data source when the tests are running.

**Comment by Czajnikowski** [comment]
Now it causes a problem when snapshot testing a view with skeleton enabled... If anybody has time it'd be good to revisit this fix and make sure that it works in both cases, or is configurable @Juanpe .
