### ISSUE TITLE
[Documentation] Skeleton view when added programatically in UITableViewCell

### ISSUE THREAD

**Issue by anoop4real** [Juanpe/SkeletonView#276]
This is not  an issue but an observation. I no longer use storyboards for my view. Today I faced an issue with Skeletonview when I added it to my UITableViewCell, animations, frames everything was working wrong... did a lot of permutation combinations turning the properties `on` and `off`. Finally found that when you add elements in UITableViewCell you should add it to  `contentView `and not to the `cell` ie

        contentView.addSubview(titleLabel) not         self.addSubview(titleLabel)

It would be great if you add this  as a note to  the  documentation (I couldnt find it,  may be its  already there :) )

**Comment by pennywise94** [comment]
This might be relevant for you:
https://github.com/Juanpe/SkeletonView/issues/125

**Comment by Lihuo** [comment]
@anoop4real , you save me a lot of time 👍

**Comment by Juanpe** [comment]
Hi, good idea I'm going to specify this in the README file. More people could be having this problem

**Comment by Juanpe** [comment]
Hi, the README file has been updated including this info 🙂

You can check it here: https://github.com/Juanpe/SkeletonView#-collections

**Comment by anoop4real** [comment]
Great 👍
