### ISSUE TITLE
Swift 5.2 compatibility

### ISSUE THREAD

**Issue by kerry** [Juanpe/SkeletonView#280]
### What did you do?

Updated to Xcode 11.4 and built the project

### What did you expect to happen?

Successful build

### What happened instead?

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler error for import SkeletonView

### Steps to reproduce the behavior

Update to Xcode 11.4 and try to build with Skeleton as a dependency via cocoapods

### SkeletonView Environment

**SkeletonView version:** 1.8.6
**Xcode version:** 11.4
**Swift version:** 5.2

**Comment by Juanpe** [comment]
It's already compatible :)
