### ISSUE TITLE
UILabel appearing as one block 

### ISSUE THREAD

**Issue by adamallard** [Juanpe/SkeletonView#281]
```
override func awakeFromNib() {
        titleLabel.styleAs(.statusTitle)
        subtitleLabel.styleAs(.statusMessage)
        cardContainer.styleAsCardView()
        actionButton.addTarget(self, action: #selector(handleTappedButton(_:)), for: .touchUpInside)
        titleLabel.isSkeletonable = true
        
        titleLabel.showSkeleton()
        titleLabel.lastLineFillPercent = Int.random(in: 20...70)
        titleLabel.linesCornerRadius = 5
        titleLabel.numberOfLines = 5
        
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        titleLabel.layoutIfNeeded()
        layoutSkeletonIfNeeded()
        titleLabel.updateSkeleton()
    }
```

The Skelton just appears as one block. 

**SkeletonView version:**
**Xcode version:**
11.3.1
**Swift version:**
swift 5

**Comment by RuiAAPeres** [comment]
I am also seeing this issue.

**Comment by Juanpe** [comment]
Hi! I'm investigating it

**Comment by RuiAAPeres** [comment]
![](https://media.giphy.com/media/dXckBa1HDG86RqUh19/giphy.gif)

**Comment by Juanpe** [comment]
Hi!

I've done some changes trying to fix this issue. Before merging these changes I would like to try if the issue is solved. Please, could you check it?

The changes are in the branch called `feature/resize_labels_based_on_number_of_lines` 

Please, let me know. Thanks 👍

**Comment by Juanpe** [comment]
Hi guys! Could you check it? I'm going to merge this feature, but if it's possible, I would like to get some feedback before :)

Thanks
