### ISSUE TITLE
Whole Cell is covered animation(Programmatically Solved!!)

### ISSUE THREAD

**Issue by oguzveozturk** [Juanpe/SkeletonView#283]
⚠️ Please fill out this template when filing an issue.

### What did you do?

<a href="https://ibb.co/zZvc5hG"><img src="https://i.ibb.co/GRSwJvc/Ekran-Resmi-2020-04-01-00-22-24.png" alt="Ekran-Resmi-2020-04-01-00-22-24" border="0"></a>
`import UIKit
import SkeletonView

class ViewController: UITableViewController, SkeletonTableViewDataSource {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.isSkeletonable = true
        tableView.isSkeletonable = true
        tableView.register(TableViewCell.self, forCellReuseIdentifier: "cell")
        tableView.estimatedRowHeight = 130
      tableView.rowHeight = UITableView.automaticDimension
        view.showAnimatedSkeleton()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        view.updateSkeleton()
    }

    override func updateViewConstraints() {
        super.updateViewConstraints()
        view.updateSkeleton()
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 30
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 30
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as! TableViewCell
        cell.label.text = "test skeletonView"
        return cell
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, cellIdentifierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
        return "cell"
    }
}

class TableViewCell: UITableViewCell {
    
    lazy var label: UILabel = {
        let label = UILabel()
        label.translatesAutoresizingMaskIntoConstraints = false
        label.text = ""
        label.isSkeletonable = true
        return label
    }()
    
    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        isSkeletonable = true
        setupLayout()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func setupLayout() {
        addSubview(label)
        NSLayoutConstraint.activate([
            label.centerXAnchor.constraint(equalTo: self.centerXAnchor),
            label.centerYAnchor.constraint(equalTo: self.centerYAnchor),
            label.widthAnchor.constraint(equalToConstant: 300),
            label.heightAnchor.constraint(equalToConstant: 25)
        ])
    }
}`
### What did you expect to happen?

just want to try skeleton animation in a simple project

### What happened instead?

as it shows in the `picture;` whole cell is covered with animation, not the label inside.

### Steps to reproduce the behavior

my code is programmatically written. no storyboard or interface builder.
[download project](https://drive.google.com/file/d/1HB0GKWWTDLxQi9c3Fyd-LuwuMXuDtcsM/view?usp=sharing).
### SkeletonView Environment

**SkeletonView version: 1.8.6
**Xcode version: 11.4
**Swift version: 5

**Comment by oguzveozturk** [comment]
Solved issue;
when you writing programmatically; view objects should not be added to cell. Should be added to cell's contentView. (as it shows in the pic below)
@Juanpe 
you must add this information to the "How to use" because there are lot of people who encounter the same problem while writing programmatically.

<a href="https://imgur.com/a/ij0TE4d"><img src="https://i.imgur.com/c4Z6pDD.jpg" alt="Ekran-Resmi-2020-04-01-17-45-26" border="0"></a>

**Comment by boungly** [comment]
Hello @oguzveozturk 

I also work on the UI programmatically, and in my case also on UITableViewCell, But I face a problem with the layout during animating as the layout keeps jumping.

> UI Structure
![image](https://user-images.githubusercontent.com/25840592/134805499-aa5abd32-708a-4455-acf1-ada16e27d893.png)


> OUTPUT
> - First Load
> ![First Load](https://user-images.githubusercontent.com/25840592/134804903-f741758b-5786-42e6-aec4-a655992b60d7.png)
> 
> - Second ViewDidAppear
> ![First ViewDidAppear](https://user-images.githubusercontent.com/25840592/134804917-9f24c608-5fab-42cb-92f8-cd95df69410e.png)
> 
> - Other ViewDidAppear
> ![Other ViewDidAppear](https://user-images.githubusercontent.com/25840592/134804933-b9e7b4f3-c7ae-4c0c-898e-4d12464aeb7c.png)

**Comment by mendesahdivio** [comment]
hi i tried creating programmatic view as like mentioned above but i dont see any skeleton view for it 



import UIKit
import SkeletonView

class ViewController: UIViewController {
  private var viewModel = ViewModel()
  var strings: [String]?
  
  
  
  private let uiTableView: UITableView = {
    let tableView = UITableView()
    tableView.translatesAutoresizingMaskIntoConstraints = false
    tableView.estimatedRowHeight = 100
    tableView.rowHeight = 100
    tableView.isSkeletonable = true
    return tableView
  }()
  
  
  override func viewDidLoad() {
    super.viewDidLoad()
    //set up the tableview
    uiTableView.register(CustomTableViewCell.self, forCellReuseIdentifier: "CellId")
    setupTableView(uiTableView)
    setTableViewDelegateAndDataSource(uiTableView)
    
    
    //call the skeleton view
    showAnimationForView()
    
    
    // call network which is just a simple dispatchqeue with 5 seconds delay
    callNetwork()
  }
  
  final func setupTableView(_ tableView: UITableView) {
    view.addSubview(tableView)
    NSLayoutConstraint.activate([
      tableView.topAnchor.constraint(equalTo: self.view.topAnchor),
      tableView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor),
      tableView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor),
      tableView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor)
    ])
  }
  
  final func setTableViewDelegateAndDataSource(_ tableView: UITableView){
    tableView.delegate = self
    tableView.dataSource = self
  }
}


//table view delegate and data source
extension ViewController: UITableViewDelegate, SkeletonTableViewDataSource {
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return strings?.count ?? 10
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCell(withIdentifier: "CellId", for: indexPath) as! CustomTableViewCell
    if let value = strings?[indexPath.item]  {
      cell.labelView.text = value ?? "boyjdkjfhdsh"
      cell.uiImageView.image = UIImage(systemName: "heart.fill")
    }
    return cell
  }
  
  func collectionSkeletonView(_ skeletonView: UITableView, cellIdentifierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
    return "CellId"
  }
}



//functions to call skeleton view animations
extension ViewController {

  private final func showAnimationForView() {
    view.showAnimatedSkeleton()
  }
  
  func stopSkeletonView() {
    self.view.stopSkeletonAnimation()
    self.view.hideSkeleton()
  }
  
  func callNetwork()  {
    
    DispatchQueue.main.asyncAfter(deadline: .now() + 5) {[weak self] in
      self?.strings =  self?.viewModel.getdata()
      self?.stopSkeletonView()
      self?.uiTableView.reloadData()
    }
  }
}


//dumy view model
struct ViewModel {
   func getdata()  -> [String] {
    return ["hey", "there", "boy", "lol", "test", "make", "proud", "test", "you", "ass"]
  }
}



//custom tableview cells with programatic UI
 class CustomTableViewCell: UITableViewCell {
  
   let labelView: UILabel = {
    let labelView = UILabel()
     labelView.font = .systemFont(ofSize: 25)
     labelView.translatesAutoresizingMaskIntoConstraints = false
     labelView.numberOfLines = 0
     labelView.text = "some randon text"
     labelView.isSkeletonable = true
    return labelView
  }()
   
   
   let uiImageView: UIImageView = {
     var imageView = UIImageView()
     imageView.translatesAutoresizingMaskIntoConstraints = false
     imageView.image = UIImage()
     imageView.contentMode = .scaleAspectFit
     imageView.frame.size.width = 70
     imageView.frame.size.height = 70
     imageView.clipsToBounds = true
     imageView.isSkeletonable = true
     return imageView
   }()
   
   
   private lazy var stackView: UIStackView = {
     let hstack = UIStackView(arrangedSubviews: [
      uiImageView,
      labelView
     ])
     hstack.translatesAutoresizingMaskIntoConstraints = false
     hstack.axis = .horizontal
     hstack.spacing = 10
     hstack.distribution = .fillEqually
     hstack.isSkeletonable = true
     return hstack
   }()
  
  override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
    super.init(style: style, reuseIdentifier: reuseIdentifier)
    isSkeletonable = true
    contentView.addSubview(stackView)
    NSLayoutConstraint.activate([
      stackView.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 0),
      stackView.topAnchor.constraint(equalTo: self.topAnchor, constant: 0),
      stackView.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: 0),
      stackView.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant: 0),
      labelView.widthAnchor.constraint(equalToConstant: 200),
      labelView.heightAnchor.constraint(equalToConstant: 25)
    ])
    
    
  }
  
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
}
