### ISSUE TITLE
Gradient transition animation not as deep in dark mode

### ISSUE THREAD

**Issue by CameronHamidi** [Juanpe/SkeletonView#285]
### What did you do?

I created a `skeletonable` view in my app, and set `SkeletonAppearance.default.tintColor` to `.clouds` and `SkeletonAppearance.default.gradient` to `SkeletonGradient(baseColor: .clouds)`. I then ran the app in both dark mode and lite mode and compared the gradient animations.

### What did you expect to happen?

I expected the view to look the exact same in dark mode and lite mode.

### What happened instead?

The dark mode gradient transitions between white and a light grey, while the lite mode gradient transitions between white and a dark grey.

### Steps to reproduce the behavior

Create a skeletonable view, and set `SkeletonAppearance` as detailed above. Call `showAnimatedSkeleton` on the view. Observe how the view appears in lite mode, then set `darkModeEnabled` in user defaults to true and observe the view again. The animations look different despite all skeleton settings being the same.

### SkeletonView Environment

**SkeletonView version:** 1.8.7
**Xcode version:** 11.3.1
**Swift version:** 5

**Comment by Juanpe** [comment]
Hi @CameronHamidi, I've checked this issue, and the code is working fine, I mean, if you set the color manually, you need to update the color/gradient when the dark mode is active. 

However, if you use the default color, the library updates the color automatically.
![dark_mode](https://user-images.githubusercontent.com/1409041/96883115-50dd9380-1480-11eb-9e40-fabb054b6abb.gif)


By the way, the default color is `.clouds`
