### ISSUE TITLE
DataSource is in correct and lag before show animated

### ISSUE THREAD

**Issue by adelbios** [Juanpe/SkeletonView#288]
We have two problems, the first is the lag before the skeleton is shown, and the second is that when the skeleton is shown again the arrangement of the data is different meaning is incorrect , the next video explain the weird issue

**Comment by iDevPro** [comment]
We have the same behaviour :)
We saw missing order (backordered data) before animate enable
Workaround:

`DispatchQueue.main.async { [weak self] in
            self?.skeletonViews.forEach({
                $0.showSkeleton()
            })
        }`

**Comment by adelbios** [comment]
> We have the same behaviour :)
> We saw missing order (backordered data) before animate enable
> Workaround:
> 
> `DispatchQueue.main.async { [weak self] in self?.skeletonViews.forEach({ $0.showSkeleton() }) }`

thanks

**Comment by Hilzom** [comment]
> > We have the same behaviour :)
> > We saw missing order (backordered data) before animate enable
> > Workaround:
> > `DispatchQueue.main.async { [weak self] in self?.skeletonViews.forEach({ $0.showSkeleton() }) }`
> 
> thanks

We ran into problems when using DispatchQueue.main.async {}

The solution to the problem now looks like this:
 view.showAnimatedSkeleton(usingColor: skeletonColor, animation: nil, transition: .none)

(or just delete this buggy pod <3 )
