### ISSUE TITLE
UICollectionView with Header, cell, footer

### ISSUE THREAD

**Issue by tsangaris** [Juanpe/SkeletonView#289]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I have a UICollectionView that has a Header, cells and a Footer.

The header and the cells have data that are coming from Firebase. So I want to have the SkeletonView show up until the data are retrieved.

In the documentation says that our collection view must conform to SkeletonCollectionViewDataSource protocol. That protocol comes with 3 methods:

    func numSections(in collectionSkeletonView: UICollectionView) -> Int

    func collectionSkeletonView(_ skeletonView: UICollectionView, numberOfItemsInSection section: Int) -> Int

    func collectionSkeletonView(_ skeletonView: UICollectionView, cellIdentifierForItemAt indexPath: IndexPath) -> ReusableCellIdentifier

**Question 1:** 
If you have header, cells, and footer, you have to register 3 different cell identifiers. How do we use the `ReusableCellIdentifier` method in this case? Obviously it has to return a different cell identifier based on the type..

**Question 2:** 
What if the method `numberOfItemsInSection` is already implemented by the conforming to `UICollectionViewDataSource `? Will i need to delete this implementation and go with the skeletonView one?

**Question 3:**
When getting data back from Firebase (or any resource(, you dont know exaclty how many results to expect. Is there a way to build the skeletonView beforehand or do you just guess the number of results? 

### SkeletonView Environment

**SkeletonView version:** 1.8.7
**Xcode version:** 11.4
**Swift version:** 5.2

**Comment by Avishekk4121** [comment]
have you found any solution for this?

**Comment by Juanpe** [comment]
Hi @tsangaris and @Avishekk4121 ,

**Question 1**
There is another method to return the identifier of the section header/footer. It is this:
```swift
func collectionSkeletonView(_ skeletonView: UICollectionView, supplementaryViewIdentifierOfKind: String, at indexPath: IndexPath) -> ReusableCellIdentifier?
```

**Question 2**
The methods are not the same, I mean, there is a method that returns the number of items when the skeleton is active.
```swift
func collectionSkeletonView(_ skeletonView: UICollectionView, numberOfItemsInSection section: Int) -> Int
```

And there is another one, the native method that returns the number of items when the skeleton is not active:
```swift
func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int
```

As you can see, they are not the same.

**Question 3**
You don't need to define the number of items when the skeleton is active. The library will calculate the number of items taking into account the layout. When the skeleton is gone and you have been set the data, your collection view should show the number of items based on your data fetched from Firebase.

Thanks
