### ISSUE TITLE
iOS 11 Large Titles don't work like it should

### ISSUE THREAD

**Issue by FurkanSimsir** [Juanpe/SkeletonView#29]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I implemented the Skeleton in my UITableview.

### What did you expect to happen?

That everything remained the same and only the Skeleton placeholder would show when loading.

### What happened instead?

Everything remained the same, except the Large Titles on the status bar on iOS 11. They appear small until I scroll down and then they are the way they should be.

### Steps to reproduce the behavior

Implement Skeleton in UITableView, turn Prefers Large Titles on. And set the Large Title to Automatic.

### SkeletonView Environment

**SkeletonView version: 1.0.4**
**Xcode version: 9.2**
**Swift version: 4.0**

**Comment by shravansukumar** [comment]
Any update on this? Even I'm facing the same issue.

**Comment by nara15** [comment]
hey! I got the same problem. I could fix it by setting the content insets to always from the table view scroll. 

![screen shot 2018-04-26 at 9 06 13 am](https://user-images.githubusercontent.com/9888134/39314271-1ccff776-4931-11e8-9094-a518df092486.png)
