### ISSUE TITLE
Issue in loading  UICollectionElementKindSectionHeader in collection view

### ISSUE THREAD

**Issue by pabitranjan13** [Juanpe/SkeletonView#290]
> Assertion failure in -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:], /Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3920.26.113/UICollectionView.m:2420
> 2020-05-08 01:37:42.536685+0530 SampleApp[46773:994114] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the view returned from -collectionView:viewForSupplementaryElementOfKind:atIndexPath (UICollectionElementKindSectionHeader,<NSIndexPath: 0xe48a5bc82c7ec6e8> {length = 2, path = 0 - 0}) was not retrieved by calling -dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath: or is nil (<UICollectionReusableView: 0x7fabb67c0d50; frame = (0 0; 0 0); layer = <CALayer: 0x600003f452e0>>)'
> 

### SkeletonView Environment

**SkeletonView version:**1.8.7
**Xcode version:** 11.4.1
**Swift version:** 5

**Comment by DedicatedDev** [comment]
func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
        }

please return correct header identifier in this method.

**Comment by carllindberg** [comment]
I think you need to implement

func collectionSkeletonView(_ skeletonView: UICollectionView, supplementaryViewIdentifierOfKind: String, at indexPath: IndexPath) -> ReusableCellIdentifier

to return the String cell identifier to use for headers while in Skeleton mode.  Skeleton returns a bare UICollectionReusableView() if you don't implement the skeleton data source method, which now appears to crash inside UICollectionView just like returning nil always has.

**Comment by taylorlannister** [comment]
I had implemented the method about collectionView header And footer, then  set the  collectionView.isSkeleton = true, got the same error about 'collectionView:viewForSupplementaryElementOfKind:atIndexPath (UICollectionElementKindSectionHeader'
and cannot finde the same implemented like tableView

**Comment by Juanpe** [comment]
Hi @taylorlannister, are you setting `header/footer.isSkeletonable = true` as well?
