### ISSUE TITLE
Whole Skeleton animations is gone with XCode 11.4.1

### ISSUE THREAD

**Issue by barankaansert** [Juanpe/SkeletonView#291]
SkeletonView was working on existing project and source code has no changes, when xcode updated, all working animations re gone. 

I tried older versions of pods but nothing works, pls help.

Thanks

SkeletonView version: 1.8.7
Xcode version: 11.4.1
Swift version: 5

**Comment by NikitaAsabin** [comment]
@barankaansert,  I had the same issue, check that view where you show skeleton is `view.isSkeletonable = true`

**Comment by barankaansert** [comment]
thanks for your help, interface builder's isSkeletonable wasnt works correctly, this way is solved .

**Comment by phynet** [comment]
Of this issue is fixed, may I ask you to close it, please.
