### ISSUE TITLE
Skeletonview UITableview datasource in not getting deallocated. 

### ISSUE THREAD

**Issue by gunapandianraj** [Juanpe/SkeletonView#293]
⚠️ Please fill out this template when filing an issue.

### What did you do?

Pushed a UIViewcontroller containing a table view with enabled skeletonview  and started animating it on viewdidload and stopped when a task get finished and popped the viewcontroller from navigation stack by tapping back button

### What did you expect to happen?
UIViewcontroller object should be deallocated. 

### What happened instead?

UIViewcontroller didnt deacllocated as skeletonview's  dummydatasource is holding its reference. checked on Xcode's memory graph

### Steps to reproduce the behavior

Push a UIViewcontroller having tableview to navigation stack  with animating skeletonview and then pop the view controller.

### SkeletonView Environment

**SkeletonView version:* 1.8.6*
**Xcode version:*11.2.1*
**Swift version:*13.2.2*

**Comment by Juanpe** [comment]
Hi @gunapandianraj, maybe there was something wrong, but the current code releases all the elements when the skeleton is hidden.

Check the video and the screenshot with the memory graph:

https://user-images.githubusercontent.com/1409041/130095493-5ec391b0-c1b9-4372-af9f-f179e7a7b519.mp4

**Xcode memory graph focus on SkeletonView elements**
![Screenshot 2021-08-19 at 17 18 36](https://user-images.githubusercontent.com/1409041/130095560-7850efbb-75d3-43ca-9c59-39e43bb23541.png)
