### ISSUE TITLE
The tableview cell does not show correct data after pressing Hide Skeleton

### ISSUE THREAD

**Issue by ldt25290** [Juanpe/SkeletonView#296]
### What did you expect to happen?
How to show correct data on tableview cell after hiding skeleton animation?
### Steps to reproduce the behavior
Open library example project, modify cellForRowAt method as below button on screen:
```
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCell(withIdentifier: "CellIdentifier", for: indexPath) as! Cell
    cell.label1.text = "cell => \(indexPath.row) date \(Date())" // add current date
    print("zzz \(String(describing: cell.label1.text))") // print current date
    return cell
}
```
The result is as below after pressing Hide Skeleton button:
<img width="2294" alt="Screen Shot 2020-06-03 at 14 27 07" src="https://user-images.githubusercontent.com/4800933/83608326-edbd9400-a5a6-11ea-8dfd-1274946ca9e1.png">

As you can see, the date on the tableview cell does not show correctly on simulator. It shows different value from the value in the console at the bottom.

The date on the cell is 2020-06-03 07:26:**35 +0000**
The current date is 2020-06-03 07:26:**59 +0000**

### SkeletonView Environment

**SkeletonView version:** 1.8.7
**Xcode version:** 11.5
**Swift version:** 5

**Comment by ivensdenner** [comment]
I'm facing the same problem!

I'm updating an `UILabel`'s `text` and `textColor` property while `isKeletonActive == true`. But when the skeleton is hidden, the data is replaced by the old values on `recoverState` method.

Is there some way to update the saved state of UILabel or something like that?

**Comment by jsahoo** [comment]
+1 same issue. There's definitely a bug here that needs to be fixed but in the meantime a workaround is to hide the skeleton with no animation. It's a bit harsh (visually) but at least your labels will load properly:

`hideSkeleton(transition: .none)`

**Comment by mortenholmgaard** [comment]
Same case with view outside tables:
`emailLabel.hideSkeleton(transition: .crossDissolve(0.25))`
v. 1.8.7
@Juanpe please have a look at this.

**Comment by Juanpe** [comment]
Hi guys, I'm going to investigate. Let's you know when I've more info about that

**Comment by Juanpe** [comment]
> Same case with view outside tables:
> `emailLabel.showAnimatedSkeleton()`
> async handling
> `emailLabel.text = "abc@email.com"`
> `emailLabel.hideSkeleton(transition: .crossDissolve(0.25))`
> emailLabel shows text from before `emailLabel.showAnimatedSkeleton()`
> 
> v. 1.8.7
> @Juanpe please have a look at this.

I'm reviewing that, but you can swap the execution of the methods. I mean, your code would look like that:
```swift
emailLabel.hideSkeleton() // Default transition is crossDissolve(0.25)
emailLabel.text = "abc@email.com"
```

**Comment by t643961** [comment]
hi all,  do wen have any update on this issue? It is still not working for me.

**Comment by Juanpe** [comment]
Hi all, the next version will fix this problem. 

If you want to check if the problem is solved with this fix you can set the dependency in your podfile, pointing to the develop branch.

Podfile
pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git', :branch => 'develop'
