### ISSUE TITLE
HideSkeleton doesn't hide all tableView cells 

### ISSUE THREAD

**Issue by OmarJalil** [Juanpe/SkeletonView#299]
### What did you do?

I have this code that makes an API call and hides the skeleton view inside reloadUI 
```
// all this inside viewDidLoad ⬇️

view.showAnimatedSkeleton()

homeViewModel.getData { [weak self] _ in
      self?.reloadUI()
 }
```

My reloadUI method 
```
fileprivate func reloadUI() {
        DispatchQueue.main.async {
            self.shouldAnimateSkeleton = false
            self.view.hideSkeleton()
            self.tableView.reloadData()
        }
    }
```
        
### What did you expect to happen?

All cells should be hiding

### What happened instead?

Instead, just some cells hid. 
Actually all the views you are looking at, are cells (where view.hideSkeleton() worked). The first one, the account one, the ranking one, the one with the dog. 
![Simulator Screen Shot - iPhone 8 - 2020-06-25 at 11 32 01](https://user-images.githubusercontent.com/25520015/85770768-7deb8680-b6d8-11ea-9844-268245aa9eee.png)

### SkeletonView Environment

**SkeletonView version:**
1.8.7
**Xcode version:**
11.5
**Swift version:**
5.2

**Comment by avjiang** [comment]
For my case, after reloading data, random skeletonView in random indexPath still shown

**Comment by QianKaiLu** [comment]
Do not use same resuseId with skeleton cell.

**Comment by imWalsh** [comment]
+1

**Comment by Juanpe** [comment]
Hi guys. Investigating

**Comment by saikumar-osv** [comment]
Started facing the same issue, after updating to latest version of Xcode.

**Comment by chang-guofeng** [comment]
can you say something more?
Very grateful for thay.

**Comment by chang-guofeng** [comment]
> Do not use same reuseId with skeleton cell.

It solved my problem.
Thanks!

**Comment by Pavel71** [comment]
Do not use same reuseId with skeleton cell. 
Hi Every One! What is this mean?

**Comment by Pavel71** [comment]
> Do not use same reuseId with skeleton cell.

Hi Every One! What is this mean?

**Comment by chang-guofeng** [comment]
I create another cell  for skeleton to show the animation.
I guess it is what he said and it works well for now.

**Comment by chaser-young** [comment]
I call "cell.hideSkeleton()" before set data to the cell.

**Comment by Juanpe** [comment]
Hi!

Please, check issue #399, I think there, there is a workaround to solve this issue. Meanwhile, I'm going to investigate more in order to solve it

**Comment by Juanpe** [comment]
The latest version should fix this problem. Please, could you check it to close this issue?
