### ISSUE TITLE
Doesn't work when using in a resizable cell

### ISSUE THREAD

**Issue by ramonsgds** [Juanpe/SkeletonView#30]
When using a resizable cell:

`tableView.rowHeight = UITableViewAutomaticDimension`         
 `tableView.estimatedRowHeight = 250`

The skeleton animation does not work. It animates the whole tableview frame as if its childviews were configured with `isSkeletonable = false`.

I know this is probably because the library works with fixed cells and it needs to due to the fact that it  is based on the height of the cells that the skeleton template is drawn. It would be great to allow for resizable cells as well.

**Comment by Juanpe** [comment]
Hi @ramonsgds, the problem has been fixed in version [1.0.5](https://github.com/Juanpe/SkeletonView/releases/tag/1.0.5)
