### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'Invalid update when delete all

### ISSUE THREAD

**Issue by X901** [Juanpe/SkeletonView#302]
Hi ,
I have problem 

My code download everything and save it on Realm

I have button that will delete everything (Reset button , so I can download everything again)

when I delete everything I got this error

### Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (20) must be equal to the number of rows contained in that section before the update (20), plus or minus the number of rows inserted or deleted from that section (0 inserted, 14 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out)

My Tableview had 14 cells 

I see the issue is because of these lines

```
 func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
           return 20
       }
```

when I remove SkeletonView from my code completely
I don't get any error

so this issue is related to SkeletonView

**Comment by Juanpe** [comment]
Hi @X901, could you give me more details about where did you call to both `reloadData` and `hideSkeletonView` methods? I think this error could be related to the order of execution of the calls.

**Comment by X901** [comment]
> Hi @X901, could you give me more details about where did you call to both `reloadData` and `hideSkeletonView` methods? I think this error could be related to the order of execution of the calls.

your replay is too late , this issue happened on my perverse work project , I forget what I did 😅

**Comment by Juanpe** [comment]
In this case,  I'll close this issue 

Sorry for the late response :/
