### ISSUE TITLE
Single Line Customization

### ISSUE THREAD

**Issue by inickt** [Juanpe/SkeletonView#303]
Hey @Juanpe! Thanks for making such a great library - its been been basically perfect for me.

Just had one bug/feature request. It looks like in https://github.com/Juanpe/SkeletonView/pull/195 there were some changes to customizing single line made, but this was backed out in commit https://github.com/Juanpe/SkeletonView/commit/65299378c49e97ce7f6e3213a0527cdc72182b4a it seems. Was this an intentional change? I would love to be able to customize the size of single lines, or use the value I set for `multilineCornerRadius` when there is just 1 line.

If this was accidental I would be more than happy to fix merge conflicts and open a new PR, but I wanted to check first.

Thanks for your help!

### SkeletonView Environment

**SkeletonView version: 1.8.7**
**Xcode version: 11.5**
**Swift version: 4.2**

**Comment by xpereta** [comment]
I also would like to customize single line views as UILabel, and could lend a hand here. As a workaround I'm using using the skeletonPaddingInsets property to adjust the height of the skeleton.

**Comment by Juanpe** [comment]
Hi! 👋

I'm going to check this issue, maybe this code was removed wrongly :/ 

Let's you know when I give more details about

**Comment by Juanpe** [comment]
BTW, any help is welcomed :)

**Comment by Juanpe** [comment]
Hi, you were right. The feature was broken :/

The next version will contain this fix. Meanwhile, you can point your pod dependency to the `develop` branch.

**Comment by inickt** [comment]
Thank you, really appreciate your work and maintaining the project!
