### ISSUE TITLE
Shimmering on existing image

### ISSUE THREAD

**Issue by p-nicolaou** [Juanpe/SkeletonView#306]
Is it possible to add the shimmering effect on an existing `UIImageView`? My hierarchy is as follows:
UIViewController
  |- WKWebView
  |- UIImageView (shimmering)

If possible, how can I achieve this? Should I include image in another container? Which one should be skeletonable?

**Comment by Juanpe** [comment]
Hi @p-nicolaou, yes, it's possible. You can show the skeleton in the view you want. I mean, if the UIImageView is skeletonable (`isSkeletonable = true`), the image can directly trigger the skeleton: `image.showSkeleton()`
