### ISSUE TITLE
when i called btn.showAnimatedSkeleton(),  UIButton can't hide text

### ISSUE THREAD

**Issue by greatsk55** [Juanpe/SkeletonView#309]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I want to showanimatedSkeleton to a UIButton.

### What did you expect to happen?

When I called btn.showAnimatedSkeleton(), I expected it to be animated like any other view.

### What happened instead?

Skeleton animation was the same, but the text of the UIButton came out.

**Comment by Juanpe** [comment]
Hi @greatsk55 ,

Could you give me more details about your problem? I've checked and the skeleton appears and the text is out...
![button_skeleton](https://user-images.githubusercontent.com/1409041/91549330-0da2f080-e927-11ea-8cc3-5e82fe5fe9d3.gif)

**Comment by hrool20** [comment]
I have the same problem. I'm using XIB's and I have this structure.

<img src="https://user-images.githubusercontent.com/13945077/91826608-70380d00-ec03-11ea-9170-26d1735cf109.png" alt="" height="400">

I'm not using custom buttons and inside **viewDidLoad()** function, I'm calling:
> view?.showAnimatedGradientSkeleton(usingGradient: gradient, animation: animation, transition: .crossDissolve(0.0))

**Comment by Juanpe** [comment]
Hi! I'm checking this issue but I need more info about it. Which Xcode version and iOS are you using?

**Comment by hrool20** [comment]
I'm using:
Xcode version: `11.6`.
Swift versión: `Swift 5`.
Minimum iOS version: `11.0`.

I was researching and it seems that now when you add a layer on a button, it is added after de text. I'm not sure if it's because of the Swift version or Xcode version, but previously the layer was added before the text.

**Comment by Juanpe** [comment]
I've merged a PR solving this problem. This fix will be available in the next version. Meanwhile, you can set the `SkeletonView` dependency line to point to the `develop` branch.

*Podfile*
`pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git', :branch => 'develop'`

Anyway, I'd like to release the next version at the end of this week :)
