### ISSUE TITLE
Errors after compilies the SkeletonView.

### ISSUE THREAD

**Issue by arishanapalli** [Juanpe/SkeletonView#310]
After sucessfully included the cocoa pods into my project received this Erros.

```
extension UITableView {
    override var subviewsToSkeleton: [UIView] {
        return visibleCells + visibleSectionHeaders + visibleSectionFooters
    }
}
```

Error: Type of expression is ambiguous without more context

    public var complementaryColor: UIColor {
        if #available(iOS 13, tvOS 13, *) {
            return UIColor { traitCollection in
                return self.isLight() ? self.darker : self.lighter
            }
        } else {
            return isLight() ? darker : lighter
        }
    }

Here its an 
```
extension UITableView {
    var indexesOfVisibleSections: [Int] {
        (0..<numberOfSections).reduce([]) {
            let headerRect: CGRect?
            
            if self.style == .plain {
                headerRect = rect(forSection: $1)
            } else {
                headerRect = rectForHeader(inSection: $1)
            }
            
            if headerRect != nil {
                let visiblePartOfTableView: CGRect = CGRect(
                    x: contentOffset.x,
                    y: contentOffset.y,
                    width: bounds.size.width,
                    height: bounds.size.height
                )
                
                if (visiblePartOfTableView.intersects(headerRect!)) {
                    return $0 + [$1]
                }
            }
            
            return $0
        }
    }

```
Error Missing return in a function expected to return '[Int]'

    var visibleSectionHeaders: [UITableViewHeaderFooterView] {
        indexesOfVisibleSections.compactMap { headerView(forSection: $0) }
    }

### Error:  Missing return in a function expected to return '[UITableViewHeaderFooterView]'
    
    var visibleSectionFooters: [UITableViewHeaderFooterView] {
        indexesOfVisibleSections.compactMap { footerView(forSection: $0) }
    }

Error: Missing return in a function expected to return '[UITableViewHeaderFooterView]'

My Max version of X-Code  supported is Version 10.1 (10B61)
Due to hardware preferences, max supported is High Sierra 10.13.6 (17G14019) 

Here uploaded error image.
![SkeletonView](https://user-images.githubusercontent.com/3903433/88535669-f7ec9380-d027-11ea-84c3-3eebd2c29b06.png)

Please let me know how to fix those in swift 4.2

**Comment by Juanpe** [comment]
Hi @arishanapalli , sorry for the late response.

In your case, the last version compatible with you IDE is version 1.8.3

To use this version you must to specify it in the **Podfile**, if you are using **Cocoapods**
`pod 'SkeletonView', '= 1.8.3'`
