### ISSUE TITLE
Crash - [__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 0

### ISSUE THREAD

**Issue by AlexPinhasovSelina** [Juanpe/SkeletonView#315]
### What did you do?

Dont know why it happened, I got crash reports from firebase crashlytics 

### What did you expect to happen?

Not to crash

### What happened instead?

crash

### Steps to reproduce the behavior

Not sure how
Maybe a cell was removed while being animated, and when calling isSkeletonActive the model of views didnt change and the count was incorrect, just an assumption 

### SkeletonView Environment

**SkeletonView version:** 1.8.6
**Xcode version:** 11.5
**Swift version:** 5.2
** iOS version: ** 12.x.x

![Screen Shot 2020-08-17 at 9 45 25](https://user-images.githubusercontent.com/46086995/90366100-9d1aea80-e06f-11ea-94d6-26533aa5d92b.png)

**Comment by Juanpe** [comment]
Hi @AlexPinhasovSelina, this bug was fixed in version 1.8.7. Please update your dependency and check if it's fixed 👍
