### ISSUE TITLE
on view loadViewModel

### ISSUE THREAD

**Issue by matthewscalf** [Juanpe/SkeletonView#316]
⚠️ Please fill out this template when filing an issue.

### What did you do?

*Please replace this with what you did.*

### What did you expect to happen?

*Please replace this with what you expected to happen.*

### What happened instead?

*Please replace this with of what happened instead.*  

### Steps to reproduce the behavior

*Please replace this with the steps to reproduce the behavior.*

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:**
**Swift version:**

**Comment by Juanpe** [comment]
Hi, 

Please, could you provide more info about your issue? Thanks

**Comment by matthewscalf** [comment]
This can be closed, it was open on accident.

**Comment by Juanpe** [comment]
Thanks
