### ISSUE TITLE
Carthage import not working properly

### ISSUE THREAD

**Issue by JLEdevelop** [Juanpe/SkeletonView#317]
### What did I do?

I tried to import SkeletonView framework with Carthage to a new project.

### What did I expect to happen?

Test if I can access to the Inspectable elements from the storyboard options

### What happened instead?

I can import programmatically the framework and use it but nothing related to this framework appears in the storyboard

### Steps to reproduce the behavior

1- Create new proyect.
2- Import SkeletonView with Carthage.
3- Try to look for something from SkeletonView in any storyBoard

### SkeletonView Environment

SkeletonView version: Latest (1.8.7)
Xcode version: 11.6
Swift version: 5

**_View_**-> (https://user-images.githubusercontent.com/62858387/91407287-d5c27d00-e842-11ea-9dc3-22a1de00a9e5.png)
**_Button_**-> (https://user-images.githubusercontent.com/62858387/91407308-d6f3aa00-e842-11ea-923d-143f3509efc8.png)
**_ViewController_**-> (https://user-images.githubusercontent.com/62858387/91407324-d824d700-e842-11ea-9e16-23905e7743d5.png)

Interesting fact: I tried to import SkeletonView with cocoaPods and works well.

**Comment by Juanpe** [comment]
Hi @JLEdevelop, there seems to be a problem with that. It should be solved with PR #292, so it will be available in the next version.

We will let you know when the next version comes out :)

**Comment by JLEdevelop** [comment]
Im glad to hear that! Thank you

**Comment by Juanpe** [comment]
Version 1.8.8 has been released, could you check if your problem is solved, please?

**Comment by JLEdevelop** [comment]
Thank you!

I updated the clean project that i´d created for testing and didnt work but
creating a new one did it.
I don´t really know why it doesn´t work in an existing project but at least
now importing skeletonView with Carthage works fine.

PD. I will continue looking for some way to fix my main project so if you
have some crazy idea about this problem I would appreciate it hahaha

**Comment by JLEdevelop** [comment]
My main project got updated and works fine.
I don't really know what is the difference between the test one and this
one, but it doesn't really matter.

Once again, thank you very much for your time and your quick response.

I will recommend your work as much as possible :)
