### ISSUE TITLE
Why not OC version of the country？？？

### ISSUE THREAD

**Issue by huanghualove** [Juanpe/SkeletonView#32]
⚠️ Please fill out this template when filing an issue.

### What did you do?

*Please replace this with what you did.*

### What did you expect to happen?

*Please replace this with what you expected to happen.*

### What happened instead?

*Please replace this with of what happened instead.*  

### Steps to reproduce the behavior

*Please replace this with the steps to reproduce the behavior.*

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:**
**Swift version:**

**Comment by Juanpe** [comment]
Hi @huanghualove, I'm working on this 😉

**Comment by eduardbosch** [comment]
@Juanpe do you have any updates about supporting OC?
I haven't seen any branch on the repo.
