### ISSUE TITLE
Use gender-neutral pronoun in repo description

### ISSUE THREAD

**Issue by slashmo** [Juanpe/SkeletonView#325]
Great job on the README, looks very polished 👍 I noticed that in the repo description you’re using the pronoun he as opposed to a gender-neutral “they”. I propose to change it to the following:

> ☠️ An elegant way to show users that something is happening and also prepare them to which contents they are awaiting

**Comment by Juanpe** [comment]
Hi @slashmo!

Good catch 🤙 I didn't notice it 😅

✅ Repo description updated

Thanks!
