### ISSUE TITLE
The text of uilabel does not change when it is in showAnimatedSkeleton.

### ISSUE THREAD

**Issue by greatsk55** [Juanpe/SkeletonView#330]
### Description

The text of uilabel does not change when it is in showAnimatedSkeleton.
i'm using storyboard.

ex ) 

vc view----------
|     baba(label)
|
|
|
|------------------ 

```
view.showAnimatedSkeleton(usingColor: .clouds, animation: .none, transition: .none)
label.text = "haha"
view.hideSkeleton()
```

label text is still baba.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ X ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version:**
**Xcode version:**
**Swift version:**

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1.
2.
3.

#### Expected result:

*Please replace this with what you expected to happen.*

#### Actual result:

*Please replace this with of what happened instead.*  

#### Attachments:

Logs, screenshots, sample project, funny gif, etc.

**Comment by Juanpe** [comment]
Hi @greatsk55 , the next version will fix this problem. 

If you want to check if the problem is solved with this fix you can set the dependency in your podfile, pointing to the develop branch.

**Podfile**
`pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git', :branch => 'develop'`

**Comment by Juanpe** [comment]
SkeletonView v1.10 has been released, so you don't need to modify your podfile :)
