### ISSUE TITLE
Version 1.9 breaks swift package manager

### ISSUE THREAD

**Issue by BrentMifsud** [Juanpe/SkeletonView#332]
### Description

1.9 is not a semantic version number. As such SPM cannot resolve.

Please update/create a new tag `1.9.0`

Using the commit SHA from 1.9 works, and any other tag works.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version: 1.9**
**Xcode version: 12.0**
**Swift version: 5.3**

#### Steps to reproduce:

1. Xcode -> file -> Swift packages -> Add package dependency
2. Set exact version to 1.9
3. observe failure

#### Expected result:

package should resolve successfully

#### Actual result:

package fails to resolve

#### Attachments:

![image](https://user-images.githubusercontent.com/18543934/93510749-b8d41380-f8ef-11ea-8f8f-429fe5aab934.png)

![image](https://user-images.githubusercontent.com/18543934/93510666-9641fa80-f8ef-11ea-8d20-20a0e8b63ccc.png)

**Comment by Juanpe** [comment]
Hi @BrentMifsud! Thanks for reporting. We're going to create a new tag to solve this problem

**Comment by Juanpe** [comment]
Hi again, this issue should be resolved :) Feel free to open a new issue if you have another problem

![Screenshot 2020-09-18 at 10 48 57](https://user-images.githubusercontent.com/1409041/93577735-b54a9600-f99c-11ea-95d5-cd95e24cfa6a.png)
