### ISSUE TITLE
Displaying incorrectly a UILabel

### ISSUE THREAD

**Issue by davidecastello** [Juanpe/SkeletonView#335]
### Description

As you can see in the attachment below, I'm calling `showAnimatedGradientSkeleton` on two Skeletonable views, an UIImageView (the big one) and an UILabel.
The lateral margin on that label is 16 on both sides, but on the right side it behaves incorrectly. Every once in a while, it behaves correctly, not changing anything in the application code. 
I'm not sure if this is a known issue with UILabels on multiple lines (here we have max 2 lines), I just wanted to know if you could help me out. 
Thanks.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### SkeletonView Environment:

**SkeletonView version:** 1.9
**Xcode version:** 12.0
**Swift version:** 5

#### Attachments:

![Screenshot](https://user-images.githubusercontent.com/14249532/94179175-6faa3380-fe9c-11ea-9c5c-a15107ffc193.png)

**Comment by davidecastello** [comment]
Any news on this? Thanks.

**Comment by Juanpe** [comment]
Hi @davidecastello, I was checking but it would be nice if you give me more info related to the constraint that you're using and the view hierarchy.

Could you provide me the info, please?

Thanks

**Comment by davidecastello** [comment]
Hi @Juanpe,
it's a simple `UILabel` under an `UIImageView`, all inside a `UIView`.

The imageView is constrained to its superview with (trailing: 0, top: 0, leading: 0) and to the label with (bottom: 16). 
The label is constrained to its superview with (trailing: 16, leading: 16, bottom: 16) and to the imageView with (top: 16). 

Let me know if you need more info. Thanks.

**Comment by Juanpe** [comment]
I've created a project with the same config and it seems to work fine...

![sample](https://user-images.githubusercontent.com/1409041/95324452-05cc5980-08a0-11eb-8eb6-92ede6288942.gif)

Attach the project.
[Button.zip](https://github.com/Juanpe/SkeletonView/files/5340219/Button.zip)

**Comment by davidecastello** [comment]
Ok thanks, so maybe it was the library for the card layout that was creating some issues. 
Anyway I got rid of it, so now it works correctly. 
Thanks for the help!
