### ISSUE TITLE
Cannot make it work with UITableView.

### ISSUE THREAD

**Issue by tomerciucran** [Juanpe/SkeletonView#34]
⚠️ Please fill out this template when filing an issue.

### What did you do?

1. import SkeletonView
2. conform to 'SkeletonTableViewDataSource' and return cell identifier.
3. tableView.isSkeletonable = true
4. tableView.showSkeleton() before loading and tableView.hideSkeleton() after data is received.

### What did you expect to happen?

To see a template of the provided cell while the data is being loaded.

### What happened instead?

The whole table had a gray overlay view and it disappeared after the data was received.

### SkeletonView Environment

**SkeletonView version: 1.0.4
**Xcode version: 9.2
**Swift version: 4

**Comment by Juanpe** [comment]
Hi @tomerciucran, the problem has been fixed in version [1.0.5](https://github.com/Juanpe/SkeletonView/releases/tag/1.0.5)

**Comment by jkmathew** [comment]
I have same issue, I am Using `SkeletonView (1.1.1)`

**Comment by Poweranimal** [comment]
@jkmathew 
Facing the same problem with version 1.4.

**Comment by MtzDiego** [comment]
i have the same issue and i have the new version 1.4.1
