### ISSUE TITLE
UITextField placeholder text is visible while skeleton is showing

### ISSUE THREAD

**Issue by jsahoo** [Juanpe/SkeletonView#345]
### Description

The placeholder text of UITextField is visible while the skeleton is active (it should be hidden).

![Nov-03-2020 17-03-27](https://user-images.githubusercontent.com/6937424/98057353-ef5de300-1df6-11eb-8259-af17736d3d47.gif)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version:** 1.10
**Xcode version:** 12.1
**Swift version:** 5

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1. Add a UITextView with a placeholder to view and make it skeletonable
2. Start skeleton with `view.showAnimatedGradientSkeleton()`

#### Expected result: 

The placeholder text should not be visible

#### Actual result: 

The placeholder text is visible

**Comment by Juanpe** [comment]
Hi @jsahoo, next version will contain the fix for this issue :)

**Comment by Juanpe** [comment]
The version 1.12.1 has been released, feel free to open a new issue if you find any bug or any weird behaviour 🙂

**Comment by mparmar-covantex** [comment]
Hello @Juanpe , still I am having same issue. Can someone please help me?

Attached a small video for your better understanding,


https://user-images.githubusercontent.com/101192007/225038011-365b7a5f-3318-42a9-8cfd-064668af9b16.mp4
