### ISSUE TITLE
calculate estimatedNumberOfRows of UITableView error

### ISSUE THREAD

**Issue by chenshipeng** [Juanpe/SkeletonView#349]
### Description

when calculate of UITableView using `func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int` error when i use auto layout to set UITableView frame.i see you use
`var estimatedNumberOfRows: Int {
        return Int(ceil(frame.height / rowHeight))
    }
`
to calculate row number,but if i use SnapKit to set UITableView frame,that will be an error.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version:1.11.0
**Xcode version:12.2
**Swift version:swift 5

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1.
2.
3.

#### Expected result:

*Please replace this with what you expected to happen.*

#### Actual result:

*Please replace this with of what happened instead.*  

#### Attachments:

Logs, screenshots, sample project, funny gif, etc.

**Comment by Juanpe** [comment]
Hi @chenshipeng, 

What are you exactly mean? The app crashes or the number of cells is calculated wrongly?

could you give more info, please? 

Thanks
