### ISSUE TITLE
UITableViewHeaderFooterView support?

### ISSUE THREAD

**Issue by alexruperez** [Juanpe/SkeletonView#35]
### What did you do?

Try to make skeletonable a view inside a UITableViewHeaderFooterView subclass from a xib.

### What did you expect to happen?

UITableViewHeaderFooterView be skeletonable.

### What happened instead?

No option to make it skeletonable.

### SkeletonView Environment

**SkeletonView version:** 1.0.4
**Xcode version:** 9.2 (9C40b)
**Swift version:** 3.2

**Comment by Juanpe** [comment]
It's supported since version 1.7 :)
