### ISSUE TITLE
skeletonPaddingInsets bug

### ISSUE THREAD

**Issue by mrReason1984** [Juanpe/SkeletonView#350]
If I use skeletonPaddingInsets and set bottom inset, nothing changes.
If I use other insets all OK

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### SkeletonView Environment:

**SkeletonView version: 1.11.0**
**Xcode version: Version 12.2 (12B45b)**
**Swift version: 5.0**

#### Steps to reproduce:

label.skeletonPaddingInsets = UIEdgeInsets(top: 0, left: 0, bottom: 10, right: 50)

#### Expected result:

height of skeleton must changed by bottom inset

#### Actual result:

nothing happened

**Comment by anwer2020** [comment]
same question. Any reports please

**Comment by Juanpe** [comment]
Hi! I'm going to check it :)

**Comment by Juanpe** [comment]
Hi @mrReason1984, I have checked for a while this issue but I can't reproduce it. I used a label with the padding intets = 
`UIEdgeInsets(top: 0, left: 0, bottom: 50, right: 50)` and as you can see in the screenshot below, the padding is applied 😅

<img width="364" alt="Screenshot 2021-02-05 at 19 34 26" src="https://user-images.githubusercontent.com/1409041/107074726-6ab1a500-67e9-11eb-9a73-7bdeefa35f7f.png">


Could you give me more details? I mean, numberOfLines, has height constraint?

Thanks

**Comment by mrReason1984** [comment]
I am use SnapKit with top constraint and constant height, numberOfLines = 1.
Sorry l cant show code.

**Comment by Juanpe** [comment]
Hi @mrReason1984, please, could you try again using the latest [**version (1.29.0)**](https://github.com/Juanpe/SkeletonView/releases/tag/1.29.0)?
