### ISSUE TITLE
UILabel height constraint remains after removing skeleton layer

### ISSUE THREAD

**Issue by mdziubich** [Juanpe/SkeletonView#351]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

When using SkeletonView on UILabel that have more than one line value set on property `numberOfLines` skeleton adds heightConstraint in `updateHeightConstraintsIfNeeded` method of UILabel extension.
After calling `hideSkeleton` and loading the text to the label the constraint is not removed which results in invalid label height. 

### SkeletonView Environment:

**SkeletonView version: 1.11.0
**Xcode version: 12.0.1
**Swift version: 5.0

#### Steps to reproduce:

1. create UILabel with dynamically rendered height
2. set UILabel `numberOfLines` property to 3
3. call `showAnimatedSkeleton()` on UILabel
4. call `hideSkeleton()` on UILabel
5. set label `text` property to fit one line. 

#### Expected result:

Label adjust its height to fit intrinsic content size.

#### Actual result:

Label height is set to the one calculated by SkeletonView.

**Comment by StasanTelnov** [comment]
Hello. I have a same problem too.

**Comment by wmadao11** [comment]
Same problem. It seems that this was introduced in 1.11.0

**Comment by sseno** [comment]
Same issue, any updates?

**Comment by Juanpe** [comment]
Hi there! sorry for the delay, I'm checking this issue. I let you know when I have more info about that 👍

**Comment by jaxxxxxxxx** [comment]
label.text = "xxx"
label.removeConstraint(label.constraints.last!)

You can use the code above to solve this problem, but use it with caution.

**Comment by Juanpe** [comment]
Hi!

This issue has been resolved, the fix will be included in the next version which will be released during this week.

Thanks for using SkeletonView :)
