### ISSUE TITLE
Limit on linesCornerRadius

### ISSUE THREAD

**Issue by feliperljorge** [Juanpe/SkeletonView#355]
### Description

Why is there a limit of 10 on the linesCornerRadius? Would be nice to remove this and allow us to decide how much we want to round the corners.

The code limits the corner radius to a maximum of 10 in UILabel+Multiline.swift file:
`set { multilineCornerRadius = min(newValue, 10) }`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### SkeletonView Environment:

**SkeletonView version: 1.11.0**
**Xcode version: 12.3**
**Swift version:  5.3.2**

#### Steps to reproduce:

1. set any label's `linesCornerRadius` to a value greater than 10, i.e. `titleLabel.linesCornerRadius = 20`

#### Expected result:

To see the corners get more rounded as `linesCornerRadius` value increases above 10.

#### Actual result:

Corners do not become more rounded after `linesCornerRadius` value is greater than 10.
`linesCornerRadius = 10` and `linesCornerRadius = 20` have the same corner radius.

**Comment by Juanpe** [comment]
Hi @feliperljorge, you're right, thanks for sharing. 

It'll be removed in the next version :)
