### ISSUE TITLE
Disclose method swizzling in documentation

### ISSUE THREAD

**Issue by ugowe** [Juanpe/SkeletonView#358]
### Disclose method swizzling in documentation

SkeletonView is swizzling the `UIView.layoutSubviews` method and this has the potential to interfere with the layout of subviews not related to this framework, similar to what was experienced in https://github.com/Juanpe/SkeletonView/issues/202

### What type of issue is this?
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Possible Solutions

* Disclose method swizzling in documentation
* Provide the means to unswizzle layoutSubviews in `recursiveHideSkeleton` function
```
    private func unswizzleLayoutSubviews() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) {
            DispatchQueue.once(token: "UIView.SkeletonView.unswizzle") {
                swizzle(selector: #selector(UIView.skeletonLayoutSubviews),
                        with: #selector(UIView.layoutSubviews),
                        inClass: UIView.self,
                        usingClass: UIView.self)
            }
        }
    }
```

**Comment by Juanpe** [comment]
Hi @ugowe, the latest version (1.14.0) contains this code :) I'm going to close this issue, feel free to open a new one if you still facing the problem
