### ISSUE TITLE
Crash swizzleLayoutSubviews

### ISSUE THREAD

**Issue by chillxcode** [Juanpe/SkeletonView#373]
### Description

I tried to solve it for a long time but I could not, a crash I always encountered. I would be very happy if you could help. iOS 13 (10%) and iOS 14 (90%).

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

This come from Firebase

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1aa4c0540 cache_t::shouldFlush(objc_selector*, void (*)()) const + 16
1  libobjc.A.dylib                0x1aa4ce5f4 __method_exchangeImplementations_block_invoke + 36
2  libobjc.A.dylib                0x1aa4c7d90 invocation function for block in flushCaches(objc_class*, char const*, bool (objc_class*) block_pointer) + 32
3  libobjc.A.dylib                0x1aa4c7cec flushCaches(objc_class*, char const*, bool (objc_class*) block_pointer) + 332
4  libobjc.A.dylib                0x1aa4ce528 method_exchangeImplementations + 256
5  SkeletonView                   0x107a759a8 $sSo6UIViewC12SkeletonViewE21swizzleLayoutSubviews33_E3334C2BEC39E9FFDCF4570209E5C62ELLyyFyycfU_yyXEfU_ + 252
6  SkeletonView                   0x107a772e8 $sSo17OS_dispatch_queueC12SkeletonViewE4once5token5blockySS_yyXEtFZ014$sSo6UIViewC12dE77E21swizzleLayoutSubviews33_E3334C2BEC39E9FFDCF4570209E5C62ELLyyFyycfU_yyXEfU_So0K0CTf1ncn_nTf4nng_n + 320
7  SkeletonView                   0x107a76314 $sSo6UIViewC12SkeletonViewE21swizzleLayoutSubviews33_E3334C2BEC39E9FFDCF4570209E5C62ELLyyFyycfU_TA + 76
8  SkeletonView                   0x107a6c2c8 $sIeg_IeyB_TR + 20
9  libdispatch.dylib              0x195d92280 _dispatch_client_callout + 16
10 libdispatch.dylib              0x195d37390 _dispatch_continuation_pop$VARIANT$mp + 412
11 libdispatch.dylib              0x195d480ac _dispatch_source_invoke$VARIANT$mp + 1308
12 libdispatch.dylib              0x195d40f3c _dispatch_main_queue_callback_4CF$VARIANT$mp + 608
13 CoreFoundation                 0x1960d95e0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation                 0x1960d3a88 __CFRunLoopRun + 2480
15 CoreFoundation                 0x1960d2ba0 CFRunLoopRunSpecific + 572
16 GraphicsServices               0x1ace10598 GSEventRunModal + 160
17 UIKitCore                      0x1989c23d8 -[UIApplication _run] + 1052
18 UIKitCore                      0x1989c7958 UIApplicationMain + 164
19 dolap                          0x104b67a14 main + 29 (AppDelegate.swift:29)
20 libdyld.dylib                  0x195db1568 start + 4

### SkeletonView Environment:

**SkeletonView version: 1.11
**Xcode version: 12.2
**Swift version: 5

**Comment by Juanpe** [comment]
Hi @chillxcode, do you have any breadcrumb? any info is important to know what is happening :) Thanks

**Comment by Juanpe** [comment]
Hi @chillxcode, the latest version (1.14.0) contains a fix that could solve this problem. I'm going to close this issue, feel free to open a new one if you still facing the problem
