### ISSUE TITLE
Gray area on iPhone 8 plus

### ISSUE THREAD

**Issue by attheodo** [Juanpe/SkeletonView#38]
⚠️ Please fill out this template when filing an issue.

### What did you do?

Loaded table view that is skeletonable

### What did you expect to happen?

I expected the gradient animation to expand full-width on
views that are skeletonable.

### What happened instead?

Gray area on view that was supposed to display gradient animation full-width
![image](https://user-images.githubusercontent.com/881195/35808122-7d807416-0a8d-11e8-96f6-21b2981c8e6c.png)

### SkeletonView Environment

**SkeletonView version:** 1.0.5
**Xcode version:** 9.2
**Swift version:** 4.1

**Comment by Juanpe** [comment]
Hi @attheodo, are you sure the views is loaded when you show the skeleton? I mean, where do you launch the skeleton? viewDidLoad? loadViews? viewWillAppear?

Thanks for use SkeletonView 👍

**Comment by attheodo** [comment]
Hey @Juanpe, so I put some breakpoints and it looks the sequence of events is more or less like this:

1. viewdidLoad
2. showing skeleton
3. viewWillAppear

The way skeleton view is being displayed is my View Model has a `isLoading` property and when that value changes, it notifies my View Controller via a delegate method. Seems to be ok with all device types apart from Plus family.

Any ideas?

**Comment by Juanpe** [comment]
Mmm...just to test, could you move the showSkeleton call to ```viewWillAppear```?

**Comment by attheodo** [comment]
@Juanpe just tested that and it didn't seem to do the trick. By the way the exact show skeleton view is `view.showAnimatedGradientSkeleton()`

**Comment by Juanpe** [comment]
Sorry, I wanted to say ```viewDidAppear```. The skeleton needs to know the final frame of the table

**Comment by attheodo** [comment]
`viewDidAppear` did the trick. Thanks. I am wondering whether there's a more elegant way for Skeleton View to handle its logic to not have this a hard requirement?

**Comment by Juanpe** [comment]
Perfect! I've in the backlog research about this, but today, it's the only way 🤷‍♂️
