### ISSUE TITLE
Add option to allow user interaction while skeletons are visible

### ISSUE THREAD

**Issue by lordzsolt** [Juanpe/SkeletonView#391]
### Describe the feature or problem you’d like to solve

Currently, when showing skeletons in a table/collection/scroll view, it feels kinda bad (imho) that user interaction or scrolling is disabled.

### Proposed solution

Add some kind of flag to allow views to scroll while skeletons are visible?

Global or per-scroll view?

**Comment by Juanpe** [comment]
Hi @lordzsolt, this feature has been included in the latest version (1.7.1)
