### ISSUE TITLE
How should SkeletonView be used with iOS 14's contentConfiguration APIs?

### ISSUE THREAD

**Issue by btc** [Juanpe/SkeletonView#396]
Is SkeletonView compatible with the new content configuration APIs in iOS 14?

**Comment by Juanpe** [comment]
Hi @btc, 

Sorry, but now, I don't have this feature in the roadmap 😕

**Comment by Juanpe** [comment]
I'm going to close this issue since this feature is not included in the roadmap yet 👍🏼
