### ISSUE TITLE
The skeleton view do not complete hide.

### ISSUE THREAD

**Issue by gloryluu** [Juanpe/SkeletonView#399]
### Description

I upgraded the library from 1.7 to 1.16 and got some problems about show and hide the skeleton view. After taking a look from open issue and the sample code as well, but I still not find out how to fix the issue :/

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version: 1.16**
**Xcode version:12.5**
**Swift version:5.3**

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1. Declare a table with 2 custom labels. One of them is dynamic height (line number = 0)
2. Show view skeleton
3. Hide vide skeleton

#### Expected result:

*Please replace this with what you expected to happen.*
All dummy skeleton should be hidden after hide skeleton

#### Actual result:

*Please replace this with of what happened instead.*  
The dummy skeleton views are with the table view cell. I also attach the sample [tableview_autodimension.zip](https://github.com/Juanpe/SkeletonView/files/6603847/tableview_autodimension.zip).
#### Attachments:
![Simulator Screen Shot - iPod touch (7th generation) - 2021-06-06 at 15 30 08](https://user-images.githubusercontent.com/10140561/120917946-173e5d80-c6dc-11eb-9204-e3e718f24006.png)

Logs, screenshots, sample project, funny gif, etc.

**Comment by harrisonsj** [comment]
Seems like this is caused by the estimatedRowHeight being significantly smaller than the actual row height turns out to be, hideSkeleton only removes the skeleton from the 'visibleCells' which leaves some reused cells with the skeleton still active if the number of visibleCells is significantly less with your data loaded than it is using the estimatedRowHeight.

Works properly if you use self.tableView.hideSkeleton(reloadDataAfter: false) or set an estimatedRowHeight closer to what the actual row height will be (if possible).

**Comment by gloryluu** [comment]
Many thank to @harrisonsj . It works for me.

**Comment by Juanpe** [comment]
Thanks @harrisonsj for the research, I really appreciate it :) 

I'll try to find a solution asap. BTW, feel free to create a PR with a solution if you know how to solve this issue ;)
