### ISSUE TITLE
Lost UILabel constraint height after call `hideSkeleton`

### ISSUE THREAD

**Issue by huangshan-ios** [Juanpe/SkeletonView#405]
### Description

Lost constraint height of UILabel after call `container.hideSkeleton()`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version: 1.16.0
**Xcode version: 12.5
**Swift version: 5.0

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1. Set constraint height for label
2. Call `showAnimatedSkeleton` in UILabel container view
3. After delay call `hideSkeleton` in container view

#### Expected result:

Does not remove the current height constraint of UILabel.

#### Actual result:

The height constraint of UILabel is removed.

#### Attachments:

None

**Comment by Juanpe** [comment]
Hi @huangshan-ios, thanks for reporting this bug.

I've checked and you were right, there was a bug related to the constraints.

This issue has been solved, but it's not released yet, although you can check the solution by installing the pod (if you are using CocoaPods) indicating the specific branch:

`pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git', :branch => 'main'`

**Comment by Juanpe** [comment]
The version that includes the fix has been released!
