### ISSUE TITLE
Skeleton view not aligned properly in RTL

### ISSUE THREAD

**Issue by Prempriya08** [Juanpe/SkeletonView#407]
![IMG_0828](https://user-images.githubusercontent.com/66105815/121680752-8bf80a00-cad7-11eb-964f-48a39e913b20.PNG)
![IMG_0827](https://user-images.githubusercontent.com/66105815/121680787-94504500-cad7-11eb-9edf-6e6d21c1c14d.PNG)
In english its working fine but when checking in arabic. The skeleton view gets distorted. Please, help me.

**Comment by yousefelsayed** [comment]
Hi @Prempriya08  Did you find a solution to this issue?  it's happening with me also .

**Comment by Juanpe** [comment]
Hi! could you give more context? SkeletonView version, iOS version... I've tried to reproduce this issue but I can't. 

![Screenshot 2021-06-22 at 09 39 52](https://user-images.githubusercontent.com/1409041/122883962-f44bb480-d33d-11eb-96bd-bc28827aa5f6.png)


Thanks

**Comment by yousefelsayed** [comment]
Hi @Juanpe  thanks for your reply , i faced same issue on RTL , the Skelton version i setup was latest version and the iOS is 14.3 , here is a screenshot from the behaviour it happened with me while scrolling 
![image](https://user-images.githubusercontent.com/17254384/124141042-55376300-da89-11eb-947c-8f00ea0e3ef5.png)

**Comment by Juanpe** [comment]
It's so weird...I did some tests using the example app, and I couldn't reproduce it. 

Could be a problem with the constraints? Could you show the constraints?

In the example app, the constraints look like this:
![Screenshot 2021-07-02 at 15 53 24](https://user-images.githubusercontent.com/1409041/124285413-2f27c680-db4e-11eb-9afe-72d49a0f74a7.png)

And the result is this:
<img width="349" alt="Screenshot 2021-07-02 at 15 53 31" src="https://user-images.githubusercontent.com/1409041/124285407-2afba900-db4e-11eb-8b5b-de793802c2c7.png">

As you can see, the labels were rendered well.

There is something not clear for me. You said that this issue happens when you are scrolling?

**Comment by yousefelsayed** [comment]
@Juanpe  here is my constraints all my labels on a vertical stackview , i use showAnimatedSkeleton function at cell content view 
![image](https://user-images.githubusercontent.com/17254384/124381666-fad61680-dcc3-11eb-8f7b-4ae05276b2d9.png)
![image](https://user-images.githubusercontent.com/17254384/124381704-340e8680-dcc4-11eb-9ce3-366109c4cf3f.png)

**Comment by Juanpe** [comment]
Hi @yousefelsayed, could you provide a sample project? I think it'll be useful to fix this issue faster :/

**Comment by Prempriya08** [comment]
Constraints are properly aligned. the labels have leading, trailing, top and bottom but still it occurs when we come back and froth from one screen to other.

**Comment by Juanpe** [comment]
mmm... 🤔 this is another thing, so the problem is when you push/present another view and come back, doesn't it?

**Comment by shivamsinha-quytech** [comment]
Hi @Juanpe ,

I am also facing same issue in Arabic language (Which support RTL) randomly when we switch between screens. I attached screenshots please check

In English language
![Simulator Screen Shot - iPhone 8 - 2021-08-17 at 13 57 47](https://user-images.githubusercontent.com/55876688/129692220-3755e5b7-3609-45c4-b479-58a8fb09f3cf.png)

In Arabic language
![Simulator Screen Shot - iPhone 8 - 2021-08-17 at 13 57 10](https://user-images.githubusercontent.com/55876688/129692302-e9392ed6-c311-4044-b4b2-f8dbc1144383.png)

Cell with constraint (which have skeleton)
![Screenshot 2021-08-17 at 2 01 04 PM](https://user-images.githubusercontent.com/55876688/129692380-2824ceab-9017-477f-8dd6-e1dc1486f8f5.png)

**Comment by Juanpe** [comment]
Hi @shivamsinha-quytech, please, could you provide a sample project? 

I'm trying to reproduce it, but I can't :/
https://user-images.githubusercontent.com/1409041/129776055-27c1701b-d8e1-4bc6-96a1-5120d89e16f3.mp4

**Comment by shivamsinha-quytech** [comment]
Hi Juanpe,

Thanks for quick response.


I think you are focusing only on LTR view but i am facing problem in RTL view. As my app is available in english and arabic both. So when i change the app language the semantic get changed to RTL mode and the complete screen get flipped. The issue starts happening after switching between the languages ENGLISH TO ARABIC or ARABIC to ENGLISH. It is very random.

I will share a sample project once got time.

Thanks

**Comment by shivamsinha-quytech** [comment]
Hi @Juanpe,

I think now you got my point so have you any update on this or you still need sample project.

**Comment by Juanpe** [comment]
Hi @shivamsinha-quytech, yep, I think the sample project would help me to reproduce and fix the issue sooner. So, could you provide me one, please? 🤙🏼

**Comment by Juanpe** [comment]
Hi @shivamsinha-quytech, could you create the sample project? 🙂

**Comment by shivamsinha-quytech** [comment]
Hi @Juanpe sorry for late response.
Please find sample project for reference.

For recreate problem 
Step 1 :- launch app
Step 2:- change language from setting icon
and you got the problem

[SampleProjectForSkeleton.zip](https://github.com/Juanpe/SkeletonView/files/7183126/SampleProjectForSkeleton.zip)


Thanks

**Comment by shivamsinha-quytech** [comment]
Hi @Juanpe

 any update on this ?

Thanks

**Comment by shivamsinha-quytech** [comment]
Hi @Juanpe

any update on this ?

Thanks

**Comment by Juanpe** [comment]
Sorry for the late response. I'm going to check it asap 👍🏼 Thanks for the sample project

**Comment by Juanpe** [comment]
I've checked this issue in your sample project using the latest version (1.27.0) and it seems it's fixed. Could you take a look please?

|RTL| LTR|
|-----|----|
|<img width="200px" src="https://user-images.githubusercontent.com/1409041/148644491-89be2b83-b828-4775-bd48-3c2ab94d769d.png" />|<img width="200px" src="https://user-images.githubusercontent.com/1409041/148644493-bb10c725-bf8d-4989-8040-71c6798c347c.png" />|
