### ISSUE TITLE
Skeleton not working if UICollectionView cell's Nib is registered in code

### ISSUE THREAD

**Issue by kjoneandrei** [Juanpe/SkeletonView#41]
Skeleton loading does't work if cells get register in code:
`collectionView.register(UINib.init(nibName: "\(Cell.self)", bundle: Bundle.main), forCellWithReuseIdentifier: "Cell")`

### What did you do

- Created UIViewController in .xib file
- Added UICollectionView in UIViewController as a subview
- Added view and collectionView as skeletonable
- Created UICollectionView cell in a separate .xib file 
- Linked cell to UICollectionView by `collectionView.register(UINib.init(nibName: "\(Cell.self)", bundle: Bundle.main), forCellWithReuseIdentifier: "Cell")`
- added delegate and dataSource for UICollectionView as self (UIViewController)
- start animating in `viewDidLoad `
- implemented SkeletonCollectionViewDataSource
- run app

I would expect it to identify the cell and add Skeleton loading to it but instead just the UICollectionView animates

### Steps to reproduce the behavior
Create a UICollectionView in a UIViewController placed in a .xib file and not .storyboard.
Register UICollectionViewCell in code as presented above.

**SkeletonView version:**
1.1.1
**Xcode version:**
9.2
**Swift version:**
4

**Comment by kjoneandrei** [comment]
looked a bit around the framework and it seems that in this case the cells in `extension SkeletonCollectionDataSource: UICollectionViewDataSource` get placed after `func recursiveShowSkeleton` gets called

**Comment by Juanpe** [comment]
Solved in the latest version **1.3**
