### ISSUE TITLE
Configure Cell Feature

### ISSUE THREAD

**Issue by nemanjachoco** [Juanpe/SkeletonView#412]
### Describe the feature or problem you’d like to solve

Our codebase is modularized and have only one dependency on a protocol modules.
We then inject the implementation from the main app, including one implementation to configure skeleton on cells. But because SkeletonView is creating UITableViewCell and passing it back directly there is no way for us to configure that cell.

### Proposed solution

Add an optional method to SkeletonCollectionDataSource protocol that would allow us to configure cell that is created by SkeletonView. This method is optional can can be ignored which assure backward compatibility. 

### Additional context

All of this works is for UICollectionView as well.

[PR Link](https://github.com/Juanpe/SkeletonView/pull/415)

**Comment by KarimAlweheshy** [comment]
+1

**Comment by datoutwo** [comment]
+1
