### ISSUE TITLE
`isSkeletonActive` returns incorrect value

### ISSUE THREAD

**Issue by p-nicolaou** [Juanpe/SkeletonView#421]
### Description

In our app, we display the SkeletonViews while waiting for remote data to be available. Once received, we hide skeleton and call `reloadData()`

In addition, we're implementing UITableViewDelegate's method as below

```
override func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
    guard view.isSkeletonActive == false else { return }
}
```

in order to update the UI with some extra info. 

Everything was working as expected while on SkeletonView 1.15.0.

Recently, we attempted to upgrade to a most recent 1.20.0 but doing so we realise that the logic described above is now broken. `view.isSkeletonActive` is shown as `true` even though we've called the `hideSkeleton()` before that.

We've spent few days in order to understand what's going on but eventually it comes down to this merge https://github.com/Juanpe/SkeletonView/pull/402#issue-666220264. If I revert the changes described into this commit then, everything works as before. I understand that this change has been introduced with 1.17.0. The 1.16.0 works ok too.

Do we have to use `isSkeletonActive` in a different way since 1.17.0 or is this an actual bug?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version: 1.20.0**
**Xcode version: 12.5.1**
**Swift version: Swift 5.5**

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1. Implement `willDisplayCell` of UITableViewDelegate protocol
2. Print the value of `view.isSkeletonActive` inside
3. On `viewDidLayoutSubviews` call `view.showAnimatedGradientSkeleton(animation: animation)` once
4. Call `view.hideSkeleton()` and `tableView.reloadData()` after a while

#### Expected result:

`view.isSkeletonActive` should print `false`

#### Actual result:

`view.isSkeletonActive` prints `true`

#### Attachments:

These screenshots show the actual value of `isSkeletonActive` when is called inside willDisplayCell using versions 1.16.0 and 1.17.0 (as described on reproduce steps above).

<img width="147" alt="Screenshot 2021-07-14 at 22 45 18" src="https://user-images.githubusercontent.com/17762810/125694600-4f3da702-c3f2-4376-ac94-18cafe006065.png">
<img width="101" alt="Screenshot 2021-07-14 at 22 49 01" src="https://user-images.githubusercontent.com/17762810/125694621-9f5df124-d9ca-419f-a8c4-280d769c9715.png">

**Comment by p-nicolaou** [comment]
@Juanpe any chance being able to look into this issue?

**Comment by Juanpe** [comment]
Hi @p-nicolaou,

The library reloads the data when the skeleton will hide, although you can omit this step. 
Could you try to call `view.hideSkeleton(reloadDataAfter: false)` instead?

**Comment by p-nicolaou** [comment]
Thank you for your response @Juanpe,

I've tried that already with no luck unfortunately.

One thing I noticed is that, by calling `view.hideSkeleton(reloadDataAfter: false)` and manually calling `tableView.reloadData()` is not working BUT
if I wrap the later into `DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(2)) { }` then it works as before. The `guard view.isSkeletonActive == false else { return }` is `false` as it should be.

**Comment by Juanpe** [comment]
Mm, ok, maybe it's related to the transition. If you dispatch after 0.25secs, it should work as well.

I'm not sure why this issue but with this clue I'm on track of find a possible solution, meanwhile a workaround for you could be dispatching the reload data task after 0.3secs

**Comment by p-nicolaou** [comment]
I will try to replicate it in a sample project as well. That way, I can share the full code as well. In the mean time, have a look at this too. Might be helpful somehow,

I've change the `isSkeletonActive` to this:
```
var isSkeletonActive: Bool {
      if self is UITableView {
        print(">>> \(subviewsSkeletonables)")
      }
      return status == .on || subviewsSkeletonables.contains(where: { $0.isSkeletonActive })
}
```

Then, I ran my app using versions SkeletonView 1.16.0 & 1.17.2

1.16.0
```
>>> []
>>> []
>>> []
>>> []
>>> []
>>> []
>>> []
>>> []
>>> []
>>> [<MyApp.SkeletonTableViewCell: 0x7f8c65c08580; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600003fa0440>>, <MyApp.SkeletonTableViewCell: 0x7f8c687e37c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600003ff96a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f8c65c08580; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600003fa0440>>, <MyApp.SkeletonTableViewCell: 0x7f8c687e37c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600003ff96a0>>]
>>> []
>>> []
>>> []
>>> []

```

1.17.2
```
>>> []
>>> []
>>> []
>>> [<MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c055a0>>]
>>> [<MyApp.SkeletonTableViewCell: 0x7f9eccd37640; baseClass = UITableViewCell; frame = (0 786; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c075a0>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64a59c0; baseClass = UITableViewCell; frame = (0 415; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c05080>>, <MyApp.SkeletonTableViewCell: 0x7f9ec64b29f0; baseClass = UITableViewCell; frame = (0 44; 390 371); hidden = YES; autoresize = W; layer = <CALayer: 0x600002c055a0>>]

```

`SkeletonTableViewCell` is the dummy cell we're using while fetching remote data

**Comment by p-nicolaou** [comment]
@Juanpe I can confirm that by passing transition = .none here,
`view.hideSkeleton(transition: .none)` also solves the issue. So, as you correctly speculated, has something to do with the transition animation. But I can't figure out why is causing this issue with 1.17.2.

**Comment by Juanpe** [comment]
Yeah, made sense :) I've created a branch with a possible fix. I think it'll be enough. 

Please, could you point to this branch to check if the problem is solved? 
The branch is `bug/set_skeleton_off_before_transition`, so if you are using Cocoapods, you should replace the current line for this one:
```bash
pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git', :branch => 'bug/set_skeleton_off_before_transition'

```

**Comment by p-nicolaou** [comment]
I can confirm that the problem is solved under the branch `'bug/set_skeleton_off_before_transition'`

Good catch. :)

**Comment by Juanpe** [comment]
Great! I'll create a new version that includes this fix. Thanks for your help 🤙🏼

**Comment by p-nicolaou** [comment]
Thank you for taking the time looking into this

**Comment by Juanpe** [comment]
Version **[1.21.2](https://github.com/Juanpe/SkeletonView/releases/tag/1.21.2)** has been released 🚀
