### ISSUE TITLE
SwiftUI Support

### ISSUE THREAD

**Issue by remlostime** [Juanpe/SkeletonView#422]
### Describe the feature or problem you’d like to solve

SwiftUI is here for a while, do we have the plan to support it

### Proposed solution

Make a `SkeltonView` which conforms `View` in SwiftUI

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Juanpe** [comment]
Hi @remlostime, 

TBH I'm not in the backlog because SwiftUI has a [view modifier](https://developer.apple.com/documentation/swiftui/view/redacted(reason:)) that allows you to simulate the content as well.

I don't know if I'll do, but not now 😕

**Comment by remlostime** [comment]
I didn't see this api introduce simulate the content func? @Juanpe

**Comment by Juanpe** [comment]
Yep, you could check [this blog post](https://www.fivestars.blog/articles/redacted-custom-effects/)

Since this feature is not in the backlog I'm going to close this issue 👍🏼
