### ISSUE TITLE
The UILabel doesn't consider the font line height while showing skeleton

### ISSUE THREAD

**Issue by ankitagarwal007** [Juanpe/SkeletonView#426]
### Description

The UIlabel takes the line-height of either the height constraint or the line SkeletonViewAppearance.multilineHeight
It doesn't consider the font line height as considered in UITextView. This is causing issues in the ios 12 version as the text behind the skeleton is visible. Also on versions >=13.0 the font line height is not considered so all the labels are of the same height

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version:** 1.21.2
**Xcode version:** 12.5.1
**Swift version:** 5.1

#### Steps to reproduce:

1. Create a UILabel and enable its Skeleton 
2. Put font of System 24.0

#### Expected result:

Skeleton View should be according to the line height of the font. Code should be similar to UITextview+Multiline.swift line-height property

#### Actual result:

iOS 12.0 : The text behind is showing 
iOS >=13.0 : UIlabel skeleton height is equal to SkeletonViewAppearance.multilineHeight

#### Attachments:

**iOS 12.0**
![Simulator Screen Shot - iPhone X - 2021-08-10 at 02 32 15](https://user-images.githubusercontent.com/30247896/128774132-05a9b414-2682-4a1b-8a30-c05ac285a494.png)

**iOS >=13.0**
![Simulator Screen Shot - iPhone X - 2021-08-10 at 02 32 00](https://user-images.githubusercontent.com/30247896/128774311-f7a90d6f-c13b-4dee-8f73-1656b1b478f4.png)

** Expected on all iOS Versions**

![Simulator Screen Shot - iPhone X - 2021-08-10 at 01 59 44](https://user-images.githubusercontent.com/30247896/128774341-ea274932-60b0-4740-a78b-9fba0e19674d.png)

**Comment by Juanpe** [comment]
Hi @ankitagarwal007, thanks for opening this issue. I can't reproduce it 🤔 
I realized that you're using version 1.8.2and the latest version is **1.21.2**. Please, could you update the dependency? I think this issue is already solved :)

**Comment by ankitagarwal007** [comment]
@Juanpe  I have mentioned the wrong version. I am using the latest version 1.21.2. 
I dug a Lil deeper and I found that if I use a color from color. xcassets it is replicating and  if I use any color directly than it is showing fine but with a fixed height of SkeletonViewAppearance.multilineHeight

I have tried it on 12.2 iPhone X, and I have also raised a PR for the fix. If you see the PR we haven't consider font line height anywhere like we have done it for UITextView.

**Comment by Juanpe** [comment]
It's so weird 🤔 could you provide me a simple project?

**Comment by ankitagarwal007** [comment]
[SkeletonDemo.zip](https://github.com/Juanpe/SkeletonView/files/6966547/SkeletonDemo.zip)
@Juanpe Attached a simple project

**Comment by Juanpe** [comment]
Solved by #427
