### ISSUE TITLE
Possibility to align multiline skeleton view

### ISSUE THREAD

**Issue by literallysofia** [Juanpe/SkeletonView#428]
Hello! 👋

I've been using this framework for a few months now and came across the following scenario while working on a project:

We have a screen with a vertical stack view aligned in the view's center. This stack has some labels with more than one line and with text **center** aligned. When using skeleton views on these labels, it looks kind of wrong because the last line (when not filling 100%) is **_always_** aligned to the left. Our goal was to be able to align the last line of the skeleton according to how the label's text is aligned. Forcing it to always align left poses a limitation to how we could customise skeleton views, since it's mostly UI...

That being said, I see two possible approaches:
1️⃣ Add a new property (like `lastLineFillPercent` and `linesCornerRadius`) to define the skeleton's alignment, could be `left` by default. Other options would be `center` and `right`.
2️⃣ Use a similar approach to number of lines, and given the text alignment of a label, apply it to the skeleton.

I feel like this feature would be a big plus! Didn't really see anyone pointing this issue which surprises me. 😅 I mean, when making skeleton views (which are placeholders) for text, it really does makes sense for it to have the same alignment.
Let me know how you feel. I started working on a solution, but noticed that in the contribution guidelines you asked to submit an issue first to get some input.

**Comment by Juanpe** [comment]
Hi @literallysofia!

Wow, TBH I didn't realize yet 😅 Well, I think it could be a great feature 👍🏼 

About the approaches...I really like the second approach more than the first one 👌🏼

**Comment by iOSDias** [comment]
@Juanpe Hello, did you realize first approach? It is necessary to make multiline center align according to design
