### ISSUE TITLE
Can you provide an example of RxDataSource

### ISSUE THREAD

**Issue by lumangmang** [Juanpe/SkeletonView#429]

**Comment by Juanpe** [comment]
Hi @lumangmang 👋🏼 

Today the library is not fully compatible with `RxDataSource`. We're working on this feature, but it's not ready yet. Meanwhile, you can create a fake `collectionview` / `tableview` that shows skeleton without using **Rx** and is hidden when data is received: /

**Comment by Juanpe** [comment]
Duplicate of #370
