### ISSUE TITLE
How to get this library working with UICollectionView?

### ISSUE THREAD

**Issue by agordeev** [Juanpe/SkeletonView#43]
The documentation seems outdated as there's no `SkeletonCollectionViewDataSource` protocol in the library installed from Cocoapods.

**Comment by agordeev** [comment]
I hvae version `1.0.5` by the way. Did you pushed `1.1.1` to trunk?

**Comment by kjoneandrei** [comment]
@agordeev the UICollectionView support was introduced only from version 1.1, so you will need to updated

**Comment by TParizek** [comment]
Just update SkeletonView version. I had 1.0.4 and updating it to 1.1.1 solved the problem.
