### ISSUE TITLE
UICollectionView wrong skeleton cell size

### ISSUE THREAD

**Issue by TParizek** [Juanpe/SkeletonView#44]
Hi,
I want to use SkeletonView to implement skeleton layout to collection view. I have VC that conforms to SkeletonCollectionViewDataSource. The skeleton layout works but the size of skeleton cells is wrong. I can see only the first cell, because it has size of the collectionview, or it's larger then it. Size of actual cells is correct and it's set by `func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize`

### SkeletonView Environment

**SkeletonView version: 1.1.1**
**Xcode version: 9.2**
**Swift version: 4.0**

**Comment by alexn-spire** [comment]
I also have a skeletonview within a cell and it does not resize properly.
