### ISSUE TITLE
`skeletonPaddingInsets` is now `internal` in both `UILabel` and `UITextView`

### ISSUE THREAD

**Issue by p4checo** [Juanpe/SkeletonView#445]
### Description

`skeletonPaddingInsets` is now `internal` in both `UILabel` and `UITextView` as of version `1.24.3`, following the latest "Codebase refactor", where it previously was public API.

Was this intentional or is it a case of missing `public` annotations? 😄 If intentional then I think this qualifies as a breaking change.

Thanks!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version:** 1.24.3
**Xcode version:** 12.5.1
**Swift version:** 5.4

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1. Use SkeletonView 1.24.3
2. Try to use `skeletonPaddingInsets` API on `UILabel` or `UITextView`
3. Cry when Xcode throws an error at you

#### Expected result:

`skeletonPaddingInsets` is publicly available like it was.

#### Actual result:

`skeletonPaddingInsets` is not publicly available anymore.

**Comment by Juanpe** [comment]
Hi @p4checo!

😳 you're totally right. I refactored the codebase and I missed including it as part of the API 😅 

I'm going to include it :) Thanks for reporting this bug 👍🏼

**Comment by Juanpe** [comment]
The issue was solved in version **1.24.4** 👍🏼
