### ISSUE TITLE
Shimmer to a specific table view section

### ISSUE THREAD

**Issue by santieduardo** [Juanpe/SkeletonView#447]
I have a table view with some sections and rows. A specific row, I have a collection view that shows some data from a web service that I'd like to make a shimmer loading.

How can I do that?

**Comment by Juanpe** [comment]
Hi @santieduardo 👋🏼 

You can show the skeleton in whatever view you want. So, I don't have the details of your code but you should launch the skeleton inside the cell view. For example:

```swift
/// CollectionCell
contentView.showSkeleton()
```

**Comment by Juanpe** [comment]
So, could we close this issue?
