### ISSUE TITLE
Estimated height doesn't consider `tableView(_:estimatedHeightForRowAt:)`

### ISSUE THREAD

**Issue by RobertDresler** [Juanpe/SkeletonView#448]
### SkeletonView Environment:

**SkeletonView version:** 1.24.4
**Xcode version:** 12.5.1
**Swift version:** 5.4.2

#### Steps to reproduce:

1. Set estimated height based on `indexPath` in `tableView(_:estimatedHeightForRowAt:)` method of `UITableViewDelegate`

#### Expected result:

SkeletonView will use this height as height for row. You can either implement taking estimated height for row from this method or creating some method like `collectionSkeletonView(_:estimatedHeightForRowAt:)`

#### Actual result:

SkeletonView uses just table view's `.estimatedRowHeight` property.

**Comment by Juanpe** [comment]
Hi @RobertDresler, I'm working on a solution for this. I'll let you know when it's ready 👍🏼

**Comment by Juanpe** [comment]
Duplicate #424

**Comment by Juanpe** [comment]
I'm going to close this issue because it's duplicated with #424 

Thanks
