### ISSUE TITLE
UITableView solid grey

### ISSUE THREAD

**Issue by beamercola** [Juanpe/SkeletonView#45]
### What did you do?

```
import SkeletonView
override func viewDidLoad() {
  ...
  tableView.isSkeletonable = true
  tableView.showSkeleton()
}

extension ChatViewController: SkeletonTableViewDataSource {
  func numSections(in collectionSkeletonView: UITableView) -> Int {
    return 1
  }

  func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return 5
  }

  func collectionSkeletonView(_ skeletonView: UITableView, cellIdenfierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
    return ChatMessageCell.identifier
  }
}

class ChatMessageCell: UITableViewCell {
  static let identifier = "ChatMessageCell"
  let userLabel = UILabel()
  let bodyLabel = ActiveLabel()

  override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
      super.init(style: style, reuseIdentifier: reuseIdentifier)
      isSkeletonable = true
      userLabel.isSkeletonable = true
      bodyLabel.isSkeletonable = true
      ...
  }
}
```

### What did you expect to happen?

It replace my labels with grey boxes

### What happened instead?

Blank white screen.  Removing `isSkeletonable = true` from the cell makes the entire view grey

### Steps to reproduce the behavior

See above.  I am not using interface builder.

### SkeletonView Environment

**SkeletonView version:**  1.1.1
**Xcode version:** 9.2
**Swift version:** 4

**Comment by thatmarcel** [comment]
I have the same issue :(

**Comment by MassimoSavinoAtKater** [comment]
You have to set the components inside your cell (possibly as well as the cell itself) to be skeletonable as well, cf the documentation on recursive view setting.

**Comment by marciok** [comment]
# After some debugging, I think I have clue on what is the issue:

SkeletonView loads its subviews recursively,  when it hits a `tableView` it creates a dummy data source with the cells that it should transform into skeletons however, when it tries to calculate the cells that should be skeletonable it uses the `rowHeight` divided by the frame.height:

```
    var estimatedNumberOfRows: Int {
        return Int(ceil(frame.height/rowHeight))
    }
 
```

 In my case the rowHeight was -1 therefore did not create any cells stoping the recursion and making one big skeleton of the `tableView`

Notice on the the exemple the `estimatedHeight` is set:
```
 @IBOutlet weak var tableview: UITableView! {
        didSet {
            tableview.rowHeight = UITableViewAutomaticDimension
            tableview.estimatedRowHeight = 120.0
        }
    }
```

**Comment by Juanpe** [comment]
Hi @marciok, you are right, #SkeletonView creates a dummy data source and calculate how many cells we need to show. 
When rowHeight is set as ```UITableViewAutomaticDimension```, rowHeight is -1. In this case, the library use ```estimatedRowHeight```. So, you must to specify what is the estimated row height.

Anyway, I'm not sure if it's enough to solve this issue. I need to check in deep :)
