### ISSUE TITLE
what about applying skeleton view pod with Swiftui views?

### ISSUE THREAD

**Issue by ghadeermohameedelmahdy** [Juanpe/SkeletonView#450]
# SkeletonView Feedback

You can use this template to give us structured feedback or just wipe it and leave us a note. Thank you!

## What have you loved?

_eg "the nice colors"_

## What was confusing or gave you pause?

_eg "it did something unexpected"_

## Are there features you'd like to see added?

_eg "SkeletonView should be compatible with SwiftUI"_

## Anything else?

_eg "have a nice day"_

**Comment by alongotv** [comment]
Although this might sound as a temporary workaround, you can wrap a skeletonable UIView as UIViewRepresentable and use it directly from SwiftUI code.

**Comment by Juanpe** [comment]
Hi!

Since this feature is not in the backlog I'm going to close this issue, ok? 👍🏼
