### ISSUE TITLE
Global setter for useFontLineHeight for whole App

### ISSUE THREAD

**Issue by ankitagarwal007** [Juanpe/SkeletonView#452]
### Describe the feature or problem you’d like to solve

Currently, useFontLineHeight needs to be set on individual UILabel and UItextView and doesn't have a global property to set for the whole app.

### Proposed solution

SkeletonAppearance should have a property so that setting once will take for all UILabels and UItextviews in the whole App

How will it benefit SkeletonView and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Juanpe** [comment]
Hi 👋🏼 yep, I think this could be a good point 👌🏼 

Thanks
