### ISSUE TITLE
how to use with RxSwift

### ISSUE THREAD

**Issue by kou-yamamoto** [Juanpe/SkeletonView#457]
### Describe the feature or problem you’d like to solve

- Is there any way to use SkeltonView with RxSwift

### Additional context

- Please let me know if there is a people who use SlektonView with RxSwift.

**Comment by ahmedkoshek** [comment]
@kou-yamamoto Did you find a way to use SkeletonView with RxSwift?

**Comment by kou-yamamoto** [comment]
@ahmedkoshek I dound this `https://github.com/anyoptional/RxSkeleton` but was archived.

**Comment by Juanpe** [comment]
I'm working on a version compatible with RxDataSource. When it's ready I'll create an example app to show how it works :)

**Comment by Juanpe** [comment]
Duplicate of #370
