### ISSUE TITLE
It crashes the application when tap on it, didSelect called and crash

### ISSUE THREAD

**Issue by FarhanAnsari92** [Juanpe/SkeletonView#46]

**Comment by Visput** [comment]
Same issue. User can tap on table view cell while skeleton view is shown. As result cell is highlighted and `didSelect` method called on `UITableViewDelegate`.

**Comment by Visput** [comment]
Fixed by setting table view selection option dynamically:
```
tableView.allowsSelection = !tableView.isSkeletonActive
```

**Comment by Visput** [comment]
Thanks for fixing it.
