### ISSUE TITLE
More customizable gradient

### ISSUE THREAD

**Issue by Zeno1995** [Juanpe/SkeletonView#461]
Hello,
I need to create a skeleton with a tighter gradient, my advice is to allow the user to init SkeletonGradient directly with a color array, this way he can initialize the object with more colors for a fully customizable gradient.

In this way for example: 
From SkeletonGradient.Swift:26
`gradientColors = [baseColor, baseColor, secondary, baseColor, baseColor]`

I don't know if I already have the way to do it, but I can't find it.
Thanks,
Enzo

**Comment by Juanpe** [comment]
Hi @Zeno1995

Let me investigate about this feature 👍🏼
