### ISSUE TITLE
TableView's insetGrouped style not work

### ISSUE THREAD

**Issue by SoprachevAK** [Juanpe/SkeletonView#463]
### Description

Describe your issue here.

### What type of issue is this? 
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**SkeletonView version: 1.25.2**
**Xcode version: 13.1**
**Swift version: 5**

#### Steps to reproduce:

1. Open [ios example](https://github.com/Juanpe/SkeletonView/tree/main/Examples/iOS%20Example)
2. In Main.storyboard change Tableview style to insetGrouped
3. In `func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int)` change count of rows to 3 (or less screen height count)
3. Build and Run application 
4. Tap on show/hide skeleton button with gradient animation

#### Expected result:

All work fine 

#### Actual result:

1. Skeleton didn't hide
2. After hide and show skeleton again,  animation on "added" cell is out of sync with existing ones

**Comment by FrolovNV** [comment]
Same problem

**Comment by SoprachevAK** [comment]
@Juanpe, I'm use clear project from latest main branch

https://user-images.githubusercontent.com/13734096/150033229-0377dc8c-7915-49da-926c-304263682927.mov

**Comment by steve7688** [comment]
I had the same problem.I use inset grouped tableview from a storyboard. there are two custom cells.
skeleton still working when I call hideSkeleton() method. @Juanpe

**Comment by tomcheung** [comment]
@Juanpe Can you take a look on that?

**Comment by codingiran** [comment]
@Juanpe Same pronlem , if tableView is set to .insetGroup style, all cells are Wrapped by UITableViewWrapperView( _wrapperView). Maybe this cause the problem, hope can solve it. Thanks a lot!
