### ISSUE TITLE
The example can to work. it show "'/System/Library/Frameworks/SkeletonView.framework/SkeletonView' (no such file)" errors

### ISSUE THREAD

**Issue by qs991011** [Juanpe/SkeletonView#471]
thany you supply so Exciting project. My xcode is 13, and swift 5.

**Comment by hyo961015** [comment]
I found this error message.
This error is when running as a device.

The solution is following these steps.

step 1. open "iOS Example" project
step 2. "Target" -> "General"
step 3. change "Do not Embed" to "Embed & Sign" in "Frameworks, Libraies, and Embedded Content"

You can use it!

**Comment by qs991011** [comment]
> I found this error message. This error is when running as a device.
> 
> The solution is following these steps.
> 
> step 1. open "iOS Example" project step 2. "Target" -> "General" step 3. change "Do not Embed" to "Embed & Sign" in "Frameworks, Libraies, and Embedded Content"
> 
> You can use it!

yeah, it solve my problem. thank tou very mouch. I am so stupid.
