### ISSUE TITLE
Notification triggered multiple times

### ISSUE THREAD

**Issue by mzying2013** [Juanpe/SkeletonView#473]
### Description

Version: 1.26.0
File: SkeletonFlowHandler.swift
Line: 18
Bug: .skeletonWillAppearNotification will  triggered multiple times in  different life cycle methods.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

**Comment by Juanpe** [comment]
Hi @mzying2013 👋🏼 

Yeah, you're right. I'm going to create a PR with the fix 👍🏼
