### ISSUE TITLE
TextView Line Corner Radius Issue

### ISSUE THREAD

**Issue by efalloon** [Juanpe/SkeletonView#474]
I cannot set a line corner radius on a textview using the `.linesCornerRadius` function programatically. However, when I apply the said corner radius on storyboards, it works.

**Comment by JacksonJang** [comment]
I solved issue

link : https://github.com/Juanpe/SkeletonView/pull/475

**Comment by Juanpe** [comment]
Hi @efalloon 👋🏼 

I've checked this issue and I can't reproduce this issue. I mean, in the example project, if I set programmatically the corner radius, it works.

**Comment by efalloon** [comment]
`descriptionTextView.isSkeletonable = true
descriptionTextView.showSkeleton(usingColor: .tertiarySystemFill, transition: .crossDissolve(1))
descriptionTextView.skeletonCornerRadius = 5
descriptionTextView.lastLineFillPercent = Int.random(in: 30..<75)
descriptionTextView.skeletonLineSpacing = 12.5
descriptionTextView.isScrollEnabled = false`
This is what my code currently looks like. Everything works except for the corner radius.

**Comment by efalloon** [comment]
`descriptionTextView.isSkeletonable = true
        descriptionTextView.showSkeleton(usingColor: .tertiarySystemFill, transition: .crossDissolve(1))`
`descriptionTextView.skeletonCornerRadius = 5
        descriptionTextView.lastLineFillPercent = Int.random(in: 30..<75)
        descriptionTextView.skeletonLineSpacing = 12.5
        descriptionTextView.isScrollEnabled = false`
This is what my code currently looks like. Everything works except for the corner radius.

**Comment by Juanpe** [comment]
Ok, the problem is that you are not using the right property. You have to use `linesCornerRadius`. Your code would look like this:

```swift
descriptionTextView.isSkeletonable = true 
descriptionTextView.showSkeleton(usingColor: .tertiarySystemFill, transition: .crossDissolve(1))
descriptionTextView.linesCornerRadius = 5 
descriptionTextView.lastLineFillPercent = Int.random(in: 30..<75) 
descriptionTextView.skeletonLineSpacing = 12.5 
descriptionTextView.isScrollEnabled = false
```

BTW, I think I should clarify this in the README file because it looks confusing
