### ISSUE TITLE
Proportional width on Custom TableViewCell not working

### ISSUE THREAD

**Issue by albertml** [Juanpe/SkeletonView#48]
⚠️ Please fill out this template when filing an issue.

### What did you do?

Follow the installation procedures and working fine.

### What did you expect to happen?

Proportional width would work when two label align horizontally.
LabelLeft = EqualWidth to ContentView with 0.6 points.
LabelRight = AlignRight to LabelLeft

### What happened instead?

It only shows LabelLeft skeletonView where proportional width not working. LabelLeft width overlaps device width.

### Steps to reproduce the behavior

By just running the application.

### SkeletonView Environment

**SkeletonView version: 1.1.1**
**Xcode version: 9.2**
**Swift version: 4**

**Comment by a144777** [comment]
Might be related to : https://github.com/Juanpe/SkeletonView/issues/16
