### ISSUE TITLE
The complementary color in Gradient color is not changed after updating the application theme

### ISSUE THREAD

**Issue by torycons** [Juanpe/SkeletonView#487]
### Description

The complementary color in Gradient color is not changed after updating the application theme

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### SkeletonView Environment:

**SkeletonView version:**
v1.29.2
**Xcode version:** 
v13.1
**Swift version:**
v5.0

#### Steps to reproduce:

1. Open Example ios application and tap UISegmentedControl to Gradient section
2. Open Settings application in iPhone and change appearance from Light to Dark or Dark to Light
3.  Go back to ios application. Gradient color in skeleton view is changed following the new application theme except  ```complementaryColor```.

#### Expected result:

The complementary color is changed following the new application theme.

#### Actual result:

The complementary color isn't changed following the new application theme.

#### Attachments:

The complementary color  isn't changed when updating the application theme from Dark to Light.
![Actual](https://user-images.githubusercontent.com/10572813/151945675-b0593560-6e68-49aa-8dbd-a0ebcb3d1993.jpg)

The complementary color should be changed when updating the application theme from Dark to Light.
![Expected](https://user-images.githubusercontent.com/10572813/151945671-29b2a4f5-c9f7-4238-b430-3b53722c9c58.jpg)

**Comment by rserentill** [comment]
I'm having the same problem. Do we have a fix/workaround for it?

**Comment by thecavilnator** [comment]
I am experiencing the same issue.

**Comment by Dolphin54rus** [comment]
#496 My fix option
