### ISSUE TITLE
How to condition import SkeletonView?

### ISSUE THREAD

**Issue by FormioCour** [Juanpe/SkeletonView#49]
### What did you do?

My `Deployment Target is 8.0`  
How to condition import SkeletonView?   
Like `#available(iOS 9, *) import SkeletonView`

### SkeletonView Environment

**SkeletonView version:1.1.1**
**Xcode version:9.2**
**Swift version:4**

**Comment by eduardbosch** [comment]
Please, check this https://stackoverflow.com/a/38538861/5710605

I'll close this issue as the library needs at least iOS 9.0

Thanks for asking here
