### ISSUE TITLE
How to override or use skeleton view for custom view?

### ISSUE THREAD

**Issue by chanonly123** [Juanpe/SkeletonView#498]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

### SkeletonView Environment:

**1.29.2**
**13.3**
**5.6**

I have a custom view which contains few labels and images. I want to show the full view as skeleton view, not individual items.

**Comment by Juanpe** [comment]
Hi @chanonly123, sorry for the late reply.

You can do it, just setting as skeletonable the custom views and the individual items as NOT skeletonable. Please, refer to the [**Hierarchy**](https://github.com/Juanpe/SkeletonView#-miscellaneous) section for more details.

Thanks
