### ISSUE TITLE
Please add customization of all params in SkeletonDefaultConfig 

### ISSUE THREAD

**Issue by maksymhusar** [Juanpe/SkeletonView#50]
### What did you do?

Create current view: https://ibb.co/gemqh7
Want to add multiline text instead of several views

### What did you expect to happen?

I want to change multilineHeight and multilineSpacing.

### What happened instead?

Don't have access

### SkeletonView Environment

**SkeletonView version:** 1.0.4
**Xcode version:** 9.2
**Swift version:** 4.1

**Comment by Juanpe** [comment]
Done in the latest version **1.3**
