### ISSUE TITLE
Don't working at M1 chip

### ISSUE THREAD

**Issue by antonyfrolov** [Juanpe/SkeletonView#502]
### Description

Pod with SkeletonView don't working at M1 chip.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report 

SkeletonView Pod don't compile. Unfortunately it unusable with M1 chip.

Project with 

### SkeletonView Environment:

**Xcode version:** 13.4
**Swift version:** 5

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1. Install Pod
2. Launch xcworkspace
3. See the bug

#### Expected result:

Just billed project

#### Actual result:

Error "Can't find framework"

**Comment by SwiftFoxx** [comment]
@antonyfrolov 
Didn't find the error.

- [x] Installed the dependency
- [x] Launched .xcworkspace
- [x] Hit ⌘ + B

Build successful.

```
OS: macOS 13.0 beta
Model: MacBook Pro (with M1)
Xcode 14.0 beta
```

Did you try reinstalling with `pod deintegrate` > `pod install` or `pod install --clean-install`?

**Comment by Juanpe** [comment]
Hi @antonyfrolov! could you try to do what @SwiftFoxx suggested to you? 

Using CocoaPods, you shouldn't get any problems. BTW, SkeletonView already supports XCFramework via SPM, so feel free to try it.

Thanks
