### ISSUE TITLE
Adding framework with Carthage does not show Storyboard property

### ISSUE THREAD

**Issue by eduardbosch** [Juanpe/SkeletonView#51]
### What did you do?

When I add the library with Carthage and open a Storyboard, I cannot see the "is skeletonable" property when selectin views.

### What did you expect to happen?

I expect to configure skeletonable property through Interface Builder.

### What happened instead?

Skeletonable property does not appear.

### Steps to reproduce the behaviour

* Add library with carthage.
* Update Carthage.
* Add the framework to the project.
* Open a Storyboard

### SkeletonView Environment

**SkeletonView version:** 1.1.1
**Xcode version:** 9.3
**Swift version:** 4.1

**Comment by Juanpe** [comment]
hi @aabanaag, today it'll be released a new version, 1.2.1. This version will solve this issue :)

**Comment by Juanpe** [comment]
The new version is already released, please could you check if it works fine? thanks

**Comment by aabanaag** [comment]
It works fine. Thanks!
