### ISSUE TITLE
Bit Code is not enabled when We use Repo with package manager.

### ISSUE THREAD

**Issue by Jenishshah2311** [Juanpe/SkeletonView#513]

**Comment by Juanpe** [comment]
Hi @Jenishshah2311, Bitcode is deprecated from Xcode 14, right? 

BTW, you can use the [XCFramework](https://github.com/Juanpe/SkeletonView-XCFramework) instead

**Comment by Jenishshah2311** [comment]
Ohh.. I seen.. thanks for clarification it is very useful thing to developer.
