### ISSUE TITLE
SkeletonView on StackView highlights the whole stack as one

### ISSUE THREAD

**Issue by acegreen** [Juanpe/SkeletonView#538]
Maybe I'm misunderstanding the implementation, but as I read it was recursive on the subviews. So I applied isSkeletonable on a stack view, but now the whole view is masked rather than the individual views within it?

I would expect it to mask the subviews separately, without me having to apply isSkeletonable and .showSkeleton() to each view individually.

Thanks in advance

<img width="1511" alt="Screenshot 2023-05-25 at 10 55 59 AM" src="https://github.com/Juanpe/SkeletonView/assets/10794609/bf79a69b-ca22-439e-8498-2b07bfef32cb">

**Comment by acegreen** [comment]
Nevemind, figured it out.

**Comment by treeleaf-nikesh** [comment]
Am stuck with same problem would love some help. @acegreen
