### ISSUE TITLE
Support for using SkeletonView with IGListKit

### ISSUE THREAD

**Issue by yusuftor** [Juanpe/SkeletonView#55]
Hi, I would love to use this library in my app, however, I'm using [IGListKit](https://github.com/Instagram/IGListKit/) for handling my collection views. This uses it's own class called `IGListAdapter` as the data source for the collection view and so there's no way to use it with `SkeletonView` at the moment. `IGListKit`, like `SkeletonView`, is a very popular open source project and I think they'd both benefit from being able to work together. It was suggested by the founder of `IGListKit` to open a support request here. Would this be possible?

**Comment by sasquatchgit** [comment]
I also tried to open an issue on IGListKit and it was suggested to request the support here. It will be so awesome if we could have both working together.

**Comment by yusuftor** [comment]
@sasquatchgit Actually it was your question that brought me here! Thanks :)

**Comment by Recouse** [comment]
Any news?

**Comment by lohenyumnam** [comment]
I would love to see the support for IGListKit. both are an awesome framework.

**Comment by SebastianBO** [comment]
Any update?

**Comment by dosymbaev** [comment]
Any update?

**Comment by adelbios** [comment]
any .  update yet ?!

**Comment by hithakshi** [comment]
Any updates??

**Comment by Recouse** [comment]
You can try this https://github.com/Instagram/IGListKit/issues/1146#issuecomment-419665360

**Comment by 10000TB** [comment]
Folks - I had a working example [here](https://github.com/Instagram/IGListKit/issues/1146#issuecomment-419665360)

Result look like this:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10967297/45257725-8df97100-b35f-11e8-85a7-a1145b88575b.gif)
