### ISSUE TITLE
UITableView Frozen

### ISSUE THREAD

**Issue by aboutsajjad** [Juanpe/SkeletonView#57]
### What did you do?

I Added TableView And all subviews Programmatically and Using Coordinator Delegate so There is no Storyboard or xib files. and registered  cell like below 
`tableview.register(SearchTableViewCell.self, forCellReuseIdentifier: "searchcell")`
and set tableview, cell and all subviews isSkeletonable to true.

### What did you expect to happen?

It replace my subviews with grey boxes

### What happened instead?

TableVIew with visible cells frozen to death. 

### Steps to reproduce the behavior

 I am not using interface builder.

### SkeletonView Environment

**SkeletonView version: 1.1.1**
**Xcode version: 9.3**
**Swift version: 4**

**Comment by grifas** [comment]
Same issue here.

I don't use storyboards/xibs. I add my tableView in `viewDidLoad` and like you, set its constraints, register my custom cell, set all subviews isSkeletonable to true but when I call 		`view.showAnimatedSkeleton()` in `viewDidLoad` or `viewWillAppear` it doesn't work (no animation) while it works in `viewDidAppear`.

With a cell xib, like in the example, it works in each methods.

**Comment by Juanpe** [comment]
Hi @grifas and @aboutsajjad, I'm going to check it asap 🙂

**Comment by grifas** [comment]
Hi @Juanpe Have you some news ?

**Comment by grifas** [comment]
@aboutsajjad I think I found a solution. I call in `viewDidLoad`:

```
DispatchQueue.main.async {
    self.view.showAnimatedSkeleton()
}
```

**Comment by Skornos** [comment]
@grifas it helped, thanks
