### ISSUE TITLE
Error available class Xcode 16 beta 1 - # is only available in iOS 12.0 or newer

### ISSUE THREAD

**Issue by lucasromanomr** [Juanpe/SkeletonView#572]
### Description

Trying to compile the project with the latest version of Skeleton, a problem is returning related to calls that are only available on iOS12 and are not being handled. 

https://developer.apple.com/documentation/quartzcore/camediatimingfunctionname

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Trying to compile the project with the latest version of Skeleton, a problem is returning related to calls that are only available on iOS12 and are not being handled. 

### SkeletonView Environment:

**SkeletonView version:** 1.31.0
**Xcode version:** 16.0 Beta 1
**Swift version:** 5

#### Steps to reproduce:

*Please replace this with the steps to reproduce the behavior.*

1. Compile

#### Expected result:
Build Success
*Please replace this with what you expected to happen.*

#### Actual result:
Build Failed
*Please replace this with of what happened instead.*  

#### Attachments:
<img width="401" alt="image" src="https://github.com/Juanpe/SkeletonView/assets/3859282/8c681908-7831-4585-a287-be73361be152">

<img width="1159" alt="image" src="https://github.com/Juanpe/SkeletonView/assets/3859282/a8cf91da-f560-4a84-a898-ca979da0213e">
<img width="1173" alt="image" src="https://github.com/Juanpe/SkeletonView/assets/3859282/07f49f84-3bbc-433c-ab59-d9e3549f52fa">
<img width="1172" alt="image" src="https://github.com/Juanpe/SkeletonView/assets/3859282/47ce4e08-38eb-4510-b652-712fb94bfead">

**Comment by lucasromanomr** [comment]
I created a fix in this pull request: #573

**Comment by sakshibala-halodoc** [comment]
I am also facing the same issue, I am using Xcode 16.2 and the latest version of this library.
