### ISSUE TITLE
Support for using SkeletonView with RxDataSources

### ISSUE THREAD

**Issue by DevilDimon** [Juanpe/SkeletonView#58]
[RxDataSources](https://github.com/RxSwiftCommunity/RxDataSources) is a popular library to work with UITableView & UICollectionView using the reactive approach of RxSwift. Both projects would benefit greatly from the ability to use SkeletonView together with RxDataSources.

**Comment by Juanpe** [comment]
Hi @DevilDimon, could be great! so I'm going to include it into the backlog ;)

**Comment by brunomunizaf** [comment]
Hi, how is the status on this? Thanks.

**Comment by felixsolorzano** [comment]
@Juanpe Any updates on this?

**Comment by papanton** [comment]
+1

**Comment by bordoli** [comment]
+1

**Comment by thangd2it** [comment]
Any updates on this ?

**Comment by HaishengLiang** [comment]
+1

**Comment by adrianodiasx93** [comment]
+1

**Comment by AnyOptional** [comment]
@Juanpe @felixsolorzano I resolved this problem, please take look at https://github.com/AnyOptional/U17, see Pods -> Development Pods -> RxSkeleton for more information.

**Comment by AnyOptional** [comment]
@felixsolorzano You can check `AppToday` in  Development Pods, use RxCollectionViewSkeletonedReloadDataSource/RxTableViewSkeletonedReloadDataSource instead of RxCollectionViewSectionedReloadDataSource/RxTableViewSectionedReloadDataSource.

**Comment by felixsolorzano** [comment]
Huge thanks!

**Comment by AnyOptional** [comment]
I've made a demo project at https://github.com/AnyOptional/RxSkeleton.

**Comment by Juanpe** [comment]
> I've made a demo project at https://github.com/AnyOptional/RxSkeleton.

Hey @AnyOptional, would you like include the code in this repo? this would be great! 😉

**Comment by AnyOptional** [comment]
@Juanpe That would be great, thanks! I've submit a version to the dev branch.

**Comment by Juanpe** [comment]
Great!! 🎉 In order to do it well, I would create two new folders inside the `Sources` folder, `Core` and `Rx`. Inside `Core` will be the current code and in `Rx` your code supporting `RxDataSources`. So, you don't need to specify inside the `podspec` the dependency with `SkeletonView` only specify the folders.
Something like this:
`s.source_files  = "Sources/Core/*", "Sources/Rx/*"`

Also, it would be great if we create another README file, to specify how to use.

Let me know if you need help and thanks

**Comment by AnyOptional** [comment]
@Juanpe Yes, I need your help. Could you please tell me what I should do next?

**Comment by aabanaag** [comment]
Hello, Any info if this was included already?

**Comment by 5torm5h4dow** [comment]
Any updates on this ?

**Comment by gsbernstein** [comment]
any updates? It doesn't look like the podspec has a subspec yet.

**Comment by alouanemed** [comment]
The progress is stopped in this comment: https://github.com/Juanpe/SkeletonView/pull/118#issuecomment-446918804 I can't find the branch mentioned there.

**Comment by Daniebro5** [comment]
Any updates on this?

**Comment by mzying2013** [comment]
Any updates on this?
