### ISSUE TITLE
CollectionView with multiple cell types

### ISSUE THREAD

**Issue by tsangaris** [Juanpe/SkeletonView#59]
Hi,

I have a **UICollectionViewController** that uses multiple cell types to build the final result.

What i do is to register each cell to the collection view like below:

    private let defaultCellId = "cellIdDefault"
    private let typeACellId = "cellIdA"

    collectionView?.register(DefaultCell.self, forCellWithReuseIdentifier: defaultCellId)
    collectionView?.register(TypeACell.self, forCellWithReuseIdentifier: typeACellId)

The data is received by performing a GET request to my server. Using a parameter in the respone i can tell which cell type i should display. Then:

    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        if cellType == ... {
            return collectionView.dequeueReusableCell(withReuseIdentifier: typeACellId, for: indexPath) as! TypeACell

        }

        if cellType == ... {
            return collectionView.dequeueReusableCell(withReuseIdentifier: defaultCellId, for: indexPath) as! DefaultTypeCell

        }
    }

And this is working just fine, rendering the correct type of cell.

Reading your documentation I couldn't find a way to let SkeletonView know the cell identifier of a set of cells. As i understand i can only use one cell identifier:

    func collectionSkeletonView(_ skeletonView: UICollectionView, cellIdentifierForItemAt indexPath: IndexPath) -> ReusableCellIdentifier {
        return defaultCellId
    }

Am i wrong? Or is there a way to use multiple Cell Identifiers?

Also, as i saw in your example, you are using a ViewController that is a subclass of UIViewController and SkeletonTableViewDataSource. What if i decide that my ViewController is a subclass of UICollectionViewController instead? How does it change, provided that UICollectionViewController forces us to use the following methods by conforming to UICollectionViewDataSource protocol:
   
    collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int
   
    collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell

Thanks in advance!

### SkeletonView Environment

**SkeletonView version: 1.1.1 (by the way, just installed it today)
**Xcode version: 9.3.1
**Swift version: 4.1

**Comment by Juanpe** [comment]
Hi @tsangaris, let me check this behaviour 🙂

**Comment by Juanpe** [comment]
Hi @tsangaris, as you can see the method `cellIdentifierForItemAt ` use the indexPath, so you can return each identifier using the index path.
