### ISSUE TITLE
SkeletonView not showing

### ISSUE THREAD

**Issue by aledefra** [Juanpe/SkeletonView#61]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I’m trying to implement SkeletonView in an app that has to download some images from a website

### What did you expect to happen?

I expect that when I tap on a button the skeleton is shown in an UIImageView while the image is downloaded from a website.

### What happened instead?

The skeleton is shown only sometimes.
But if I put a breakpoint after the showSkeleton(), I can see it every time.

### SkeletonView Environment

**SkeletonView version: 6.0**
**Xcode version: 9.3.1 **
**Swift version: 4.1**

**Comment by Juanpe** [comment]
Hi @aledefra, maybe the download time could be short? and the skeleton doesn't have enough time to appears

**Comment by aledefra** [comment]
Hi @juanpe
I’ve also tried with a very slow internet, where the download requires some seconds, but I can’t see the skeleton anyway.

**Comment by Juanpe** [comment]
Could you provide more info about how have you configured the skeletonable flag? Thanks
