### ISSUE TITLE
Custom Tableviewcell

### ISSUE THREAD

**Issue by aabanaag** [Juanpe/SkeletonView#63]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I followed the implementation of UITableView

### What did you expect to happen?

I'm using a custom tableviewcell. I was expecting to have the skeletonview mimic the layout of my tableviewcell also I created a separate nib for the tableviewcell.

![image](https://user-images.githubusercontent.com/2245822/40889341-8d880c54-6797-11e8-9168-486212ca8dcb.png)

### What happened instead?
It only animated the whole table while loading the data then disappears when it's done loading.
https://www.dropbox.com/s/o7044yeoi5ka56u/skeletonview.gif?dl=0 (I uploaded a gif to show the behavior)

### SkeletonView Environment

**SkeletonView version: 1.2**
**Xcode version: 9.4**
**Swift version: 4**

**Comment by Juanpe** [comment]
Hi @aabanaag, Are you specify correctly which views are skelelotables? also the UITableview?

**Comment by aabanaag** [comment]
I'll close this. The issue was fixed with the recent release. However I did specified tableView.isSkeletonable = true but no luck although with 1.2.1 specifically the issue where Skeletonable dropdown is not showing on the right panel of xcode was fixed.

**Comment by Erumaru** [comment]
@aabanaag I'm experiencing the same issue on version 1.4.0 swift 4.0. All view in hierarchy has isSkeletonable = true, but only whole cell plays animation, instead of labels that it contains.
