### ISSUE TITLE
Use SkeletonView with Bond

### ISSUE THREAD

**Issue by eduardbosch** [Juanpe/SkeletonView#65]
### What did you do?

I'm trying to use SkeletonView lib with Bond library.

### What did you expect to happen?

I would like to bind my TableView to a data source and allow using the Skeleton view while loading with Bond bindings.

### What happened instead?

As Bond uses a plain `UITableViewDataSource` to bind the data to a TableView, I cannot use the protocol `SkeletonTableViewDataSource` that inherits from `UITableViewDataSource`

### SkeletonView Environment

**SkeletonView version:** 1.2
**Xcode version:** 9.4
**Swift version:** 4.1

**Comment by ChristianPraiss** [comment]
Hey, try conforming to the SkeletonTableViewDataSource protocol on the viewcontroller that owns the tableView and set self.tableView.reactive.dataSource.forwardTo = self where self is the viewcontroller after setting up the tableview binding

**Comment by ChristianPraiss** [comment]
If XCode complains about the missing dataSource methods just implement them like the following (they will never be called) `
    
    // MARK: Util
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        fatalError()
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        fatalError()
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        fatalError()
    }`

**Comment by daviskoh** [comment]
Are there any updates on this?

**Comment by eduardbosch** [comment]
@daviskoh you can use the new beta Bond 7 which allows using custom binders. Just create a custom binder that extends from `SkeletonTableViewDataSource`.

Here is the solution https://github.com/DeclarativeHub/Bond/issues/534

**Comment by adelbios** [comment]
@eduardbosch can u provide demo example ,, nothing work

**Comment by eduardbosch** [comment]
Hi @adelbios 

You can create a table data source compatible with `Bond` and `SkeletonView` like this:

```swift
class SkeletonTableViewBinderDataSource<Changeset>:
        TableViewBinderDataSource<Changeset>, SkeletonTableViewDataSource
        where Changeset: SectionedDataSourceChangeset {

    private let skeletonReusableCellIdentifier: String

    init(skeletonReusableCellIdentifier: String = "SkeletonCell",
         _ createCell: @escaping (Changeset.Collection, IndexPath, UITableView) -> UITableViewCell) {
        self.skeletonReusableCellIdentifier = skeletonReusableCellIdentifier
        super.init(createCell)
    }

    func collectionSkeletonView(_ skeletonView: UITableView, cellIdentifierForRowAt indexPath: IndexPath)
                    -> ReusableCellIdentifier {
        return skeletonReusableCellIdentifier
    }
}
```

Then, bind your data to the table with `Bond` like this:

```swift
...
// Create table binder
let tableBinder = SkeletonTableViewBinderDataSource<OrderedCollectionChangeset<Array<YOUR_DATA_CLASS>>>() {
    array, indexPath, collectionView in
    let cell = collectionView.dequeueReusableCell(withIdentifier: "YOUR_CELL_NAME", for: indexPath) as! YOUR_CELL_CLASS

    // Configure your cell here with data at index position
    let data = array[indexPath.item]
    ...

    return cell
}

// Bind data to 
yourObservableData.bind(to: yourTableView, using: tableBinder)
...
```

Let me know if it's working to you 🙂

**Comment by adelbios** [comment]
thank U
