### ISSUE TITLE
Not able to set skeleton for tableView.tableHeaderView

### ISSUE THREAD

**Issue by GauravTechbirds** [Juanpe/SkeletonView#70]
What did you do?
Try to make a tableHeaderView and its subviews skeletonable

What did you expect to happen?
tableView.tableHeaderView  should be skeletonable.

What happened instead?
Could not see its skeleton.

SkeletonView Environment
SkeletonView version: 1.1
Xcode version: 9.2 (9C40b)
Swift version: 4

The only way I think i can make tableHeaderView skeleton is to put that inside a cell and use datasource method like other cells.

**Comment by Juanpe** [comment]
Hi @GauravTechbirds, it's already in the backlog. I let you know when it's ready :)

**Comment by grifas** [comment]
@Juanpe Any news ?

**Comment by Juanpe** [comment]
Yep, it's was included on [version 1.7](https://github.com/Juanpe/SkeletonView/releases/tag/1.7)
