### ISSUE TITLE
Collection View not showing skeleton for cells 

### ISSUE THREAD

**Issue by samsidd** [Juanpe/SkeletonView#71]
⚠️ Please fill out this template when filing an issue.

### What did you do?
I am trying to show skeleton in collection view , i added an image view and a label to a cell set them both skeletonable and also set the cell to skeletonable and in viewDidLoad called showAnimatedGradientSkeleton() on collectionView.

### What did you expect to happen?
I thought it should show the collectionView cells as skeleton.

### What happened instead?
but it shows the whole collection view as skeleton and the cells dont appear, basically i just have a gray view with a gradient animation showing up.

### Steps to reproduce the behavior

Add a collection view , add a cell to it , add imageview and label to cell set isSkeletonable to true
for all of them. Implement the protocol and then run

### SkeletonView Environment

**SkeletonView version:** 1.2.1
**Xcode version:** 9.3.1
**Swift version:** 4.0
![simulator screen shot - iphone 7 - 2018-06-25 at 18 17 53](https://user-images.githubusercontent.com/23699862/41852280-142b850c-78a4-11e8-8147-7949388810d8.png)

**Comment by samsidd** [comment]
Please help me with this, it works on the UItableView if i set the EstimatedRowHeight but since UICollectionView does not have any such property i couldn't resolve it. I also tried the sizeForItem method but it doesnt work also.

**Comment by kornerr** [comment]
Doesn't work for me:

![preview](https://raw.githubusercontent.com/kornerr/ios-item-hierarchy/0ac240c0a04c7c5f5a32d971461c9fb58c7141b2/preview.gif)

That's how my request to show gradient looks like:

* https://github.com/kornerr/ios-item-hierarchy/blob/0ac240c0a04c7c5f5a32d971461c9fb58c7141b2/App/Sample/SampleCoordinator.swift#L29
* https://github.com/kornerr/ios-item-hierarchy/blob/0ac240c0a04c7c5f5a32d971461c9fb58c7141b2/App/Sections/SectionsView.swift#L99

**Comment by TaomingHuang** [comment]
@samsidd Hey I seem to have the same issue as you used to have. I wonder what does it mean by a dispatch of 0.1 sec?

**Comment by Sorix** [comment]
+1

**Comment by dmitrycrys** [comment]
Try to replace this method in SkeletonView.swift 
`    fileprivate func recursiveShowSkeleton(withType type: SkeletonType, usingColors colors: [UIColor], animated: Bool, animation: SkeletonLayerAnimation?) {
        addDummyDataSourceIfNeeded()
        DispatchQueue.main.async { [weak self] in
            if let strongSelf = self {
                strongSelf.recursiveSearch(inArray: strongSelf.subviewsSkeletonables,
                                leafBlock: {
                                    guard !strongSelf.isSkeletonActive else { return }
                                    strongSelf.isUserInteractionEnabled = false
                                    strongSelf.saveViewState()
                                    (self as? PrepareForSkeleton)?.prepareViewForSkeleton()
                                    strongSelf.addSkeletonLayer(withType: type, usingColors: colors, animated: animated, animation: animation)
                }) {
                    $0.recursiveShowSkeleton(withType: type, usingColors: colors, animated: animated, animation: animation)
                }
            }
        }
    }`

**Comment by dmitrycrys** [comment]
The solution for me was to add:
` DispatchQueue.main.async` after `addDummyDataSourceIfNeeded() `  to `fileprivate func recursiveShowSkeleton(withType type: SkeletonType, usingColors colors: [UIColor], animated: Bool, animation: SkeletonLayerAnimation?) `
But I still have an issue with blinking content before skeleton appears

**Comment by Juanpe** [comment]
Hi, this issue should be solved in latest version (**1.3**).
You need to `prepareSkeleton`, you can check this PR (https://github.com/Juanpe/SkeletonView/pull/42)

**Comment by lalkrishna** [comment]
@Juanpe please fix this ASAP. Temporarly I use saxahan's code to make it working. @saxahan thanks :)

**Comment by sergeymild** [comment]
still doesn't work

**Comment by onderozcan** [comment]
Doesn't work in tableviewcell too.
