### ISSUE TITLE
Non Visible Cell Skeletons

### ISSUE THREAD

**Issue by giantramen** [Juanpe/SkeletonView#72]
### What did you do?

tableView.showAnimatedGradientSkeleton()

### What did you expect to happen?

All cells in the table show skeleton.

### What happened instead?

Only visible cells showed skeleton. 
Because the subviewsSkeletonables for the table is `visibleCells.filter { $0.isSkeletonable }`

### Steps to reproduce the behavior

showAnimatedGradientSkeleton on a table with non visible cells.

### SkeletonView Environment

**SkeletonView version:** 1.2.1
**Xcode version:** 9.3.1
**Swift version:** 4.1

Is this expected that it only works with visible cells? 
Should I move my skeleton logic to the cell level so it happens when the cells are created? 
Is there a way the library could be modified to start the animation on newly created cells?

**Comment by JordanPJamieson** [comment]
I'm having the same issue, did you figure this issue out?

**Comment by giantramen** [comment]
Yes you need to have your skeleton logic at the cell level you can't just call tableView.showAnimatedGradientSkeleton()
