### ISSUE TITLE
Skeleton won't automatically show / hide on TableViewCell even when implementing protocol SkeletonTableViewDataSource

### ISSUE THREAD

**Issue by gorkaman** [Juanpe/SkeletonView#74]
⚠️ Please fill out this template when filing an issue.

#### 🙏🏼 *Please check if it already exists other issue related with yours.*

Set skelenotable true to content view and sub views on a UITableViewCell

### What did you expect to happen?

Since I'm implementing the protocol, I expected the cells to show the skeleton automatically without having to self.showAnimatedSkeleton() on the cell.

### What happened instead?

If I don't use self.showAnimatedSkeleton() on the cell, nothing happens, but if I do the skeleton covers the content already loaded. I don't know how to have that behavior automatically when things asynchronously load. I know I can call hideSkeleton, but I thought it would be automatically when implementing the protocol.

### Steps to reproduce the behavior

1. Set cell contentView and sub views Skeletonable: true
2. Implement protocol SkeletonTableViewDataSource:
    
    func numSections(in collectionSkeletonView: UITableView) -> Int {
        return 1
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.brands.count
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, cellIdenfierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
        return "BTCatalogCardTableViewCell"
    }

3. Nothing happens unless I do self.showAnimatedSkeleton() on the cell and it never hides.

### SkeletonView Environment

**SkeletonView version: 1.2.1**
**Xcode version: 9.4.1**
**Swift version: 4**

**Comment by L4grange** [comment]
Are you calling view.showAnimatedSkeleton() in your viewDidLoad or in viewWill/DidAppear?

I found out that starting the animaiton in viewDidLoad breaks the TableView Skeleton and does not hide it when you call hideSkeleton().

In general I've been fighting to get this library working on my UITableViews for the past 3 days with not that much success. Especially if a tableView is a subclass of another tableView, where the Skeleton works on the parent but not on the child tableView.

**Comment by q351941406** [comment]
me too

**Comment by daviskoh-hiatus** [comment]
still an issue in `1.7`...

**Comment by Juanpe** [comment]
please, could you provide more details?
