### ISSUE TITLE
Skeleten Label Centered in StackView Doesn't Show Up Centered 

### ISSUE THREAD

**Issue by giantramen** [Juanpe/SkeletonView#76]
### What did you do?

Skeletoned text inside a stack view with center alignment.

### What did you expect to happen?

The skeleton to show up centered in the stack view. 

### What happened instead?

The skeleton view frame started at center so it appeared right aligned. 

i.e. 

\------------------------
|.....................................| 
|.........Label Here..........|
|.....................................|
\-------------------------

\-----------------------
|......................................| 
|...................|||||||||||||....|
|......................................|
\----------------------- 
||||||||||||| = Skeleton View 
### Steps to reproduce the behavior

Have a stack view with center alignment with a label inside. 
Set the label to skeleton and see it's offset. 

### SkeletonView Environment

SkeletonView version: 1.2.1
Xcode version: 9.3.1
Swift version: 4.1

**Comment by mattweight** [comment]
Having the exact same issue with Stack Views. Any chance this is going to get looked at? Thanks!

**Comment by giantramen** [comment]
My PR got merged in, closing this as fixed.
