### ISSUE TITLE
Assign Skeleton view datasource to custom datasource

### ISSUE THREAD

**Issue by muzamil999** [Juanpe/SkeletonView#79]
### What did you do?

I am having a custom Datasource Class which is implementing TableView delegate and datasource methods. I simply assign that class as delegate and datasource to my table view in controller. I couldn't find a way of assigning my custom DataSource file to SkeletonViewDataSource. It is not assigned the way table view delegate and datasource are assigned. Also my skeleton view is not showing up through I set all respective views as skeletonable correctly.

As per requirement, I just want to show skeleton view of tableview in my controller. 

Currently, I am setting it the following way in my controller

`func configureView() {
        
        self.newsTableView.delegate = self.homeDataSource
        self.newsTableView.dataSource = self.homeDataSource
        self.homeDataSource.newsFeeds = self.newsFeeds
        
    }`

and doing setting it in my dataSource class as

`// MARK:- TableView Delegate

extension HomeDataSource: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if self.didSelectNewsBlock != nil {
            self.didSelectNewsBlock!(self.newsFeeds[indexPath.row])
        }
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        let totalRows = tableView.numberOfRows(inSection: 0)
        if self.newsFeeds.count > 0 && indexPath.row == (totalRows - 5) && self.shouldRefreshFeeds != nil {
            self.shouldRefreshFeeds!()
        }
    }
}

// MARK:- TableView DataSource

extension HomeDataSource: SkeletonTableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let newsModel = self.newsFeeds[indexPath.row]
        if indexPath.row == 0 {
            var cell: FeaturedNewsTableViewCell? = tableView.dequeueReusableCell(withIdentifier: kFeaturedNewsTableViewCell) as? FeaturedNewsTableViewCell
            if cell == nil {
                cell = Bundle.main.loadNibNamed(kFeaturedNewsTableViewCell, owner: self, options: nil)![0] as? FeaturedNewsTableViewCell
            }
            cell?.setDataFromModel(newsModel)
            return cell!;
        }
        else {
            if newsModel.imageMedium == nil {
                var cell: SimpleNewsTableViewCell? = tableView.dequeueReusableCell(withIdentifier: kSimpleNewsCell) as? SimpleNewsTableViewCell
                if cell == nil {
                    cell = Bundle.main.loadNibNamed(kSimpleNewsCell, owner: self, options: nil)![0] as? SimpleNewsTableViewCell
                }
                cell?.setDataFromModel(newsModel)
                return cell!;
            }
            else {
                var cell: ImageNewsTableViewCell? = tableView.dequeueReusableCell(withIdentifier: kImageNewsTableViewCell) as? ImageNewsTableViewCell
                if cell == nil {
                    cell = Bundle.main.loadNibNamed(kImageNewsTableViewCell, owner: self, options: nil)![0] as? ImageNewsTableViewCell
                }
                cell?.setDataFromModel(newsModel)
                return cell!;
            }
        }
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.newsFeeds.count
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 8
    }
    
    func collectionSkeletonView(_ skeletonView: UITableView, cellIdenfierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
        skeletonView.register(UINib(nibName: kImageNewsTableViewCell, bundle: nil), forCellReuseIdentifier: kImageNewsTableViewCell)
        return kImageNewsTableViewCell
    }
}`

Any guidance to resolve this issue

**SkeletonView version:** 1.2.1
**Xcode version:** 9.3
**Swift version:** 4

**Comment by Juanpe** [comment]
Hi @muzamil999, I'm checking your code and it look fine. When are you calling `configureViews` method?
Btw, new version is live (1.3)

**Comment by muzamil999** [comment]
On viewDidLoad

**Comment by muzamil999** [comment]
This is what I get
![simulator screen shot - iphone 8 plus - 2018-08-08 at 14 51 43](https://user-images.githubusercontent.com/21131057/43830806-aae9bb00-9b1b-11e8-800e-c867e7ec0444.png)

and this is my screen design
![simulator screen shot - iphone 8 plus - 2018-08-08 at 14 52 12](https://user-images.githubusercontent.com/21131057/43830855-bdf546ce-9b1b-11e8-8ebb-878f5c856bca.png)

**Comment by Juanpe** [comment]
Hi @muzamil999, could give me more details about your view hierarchy? I mean, tableView is skeletonable? and which view is launching the skeletons `view.showSkeleton()`?

**Comment by muzamil999** [comment]
Yes the tableView is skeletonable
Also I am calling self.view.showSkeleton() from the view controller

**Comment by Juanpe** [comment]
I'm going to create a new debug system, in order to facilitate the error reporting tasks. In your case I think it will be useful to find what is it happening in with your code :)

**Comment by Juanpe** [comment]
Hi @muzamil999, new version has been published. Now, you can check the hierarchy and check if all it's well configured. [Debug mode](https://github.com/Juanpe/SkeletonView#-debug)

**Comment by gloryluu** [comment]
Have same issue. It never comes through SkeletonViewDataSource eventhough I set it, clean xcode... Eventually I give up temporarily.

**Comment by amaamoun74** [comment]
> I'm going to create a new debug system, in order to facilitate the error reporting tasks. In your case I think it will be useful to find what is it happening in with your code :)

maybe using XIP file for custom table view cell so the ReusableCellIdentifier causes this error or something like that ?
