### ISSUE TITLE
[Suggestion] Make last line of text skeleton not full width

### ISSUE THREAD

**Issue by jontelang** [Juanpe/SkeletonView#8]
Generally when drawing text, especially multiple lines, the last line is drawn with a shorter length than the other lines.

For this project, it could be optionally enabled if the user wants it as well as only on when there's 2+ lines.

If it sounds interesting I could maybe do it in a PR, but if not I won't bother (hence this ticket).

**Comment by AlexisQapa** [comment]
Would be a nice addition

**Comment by Juanpe** [comment]
Hi @jontelang, thanks for the suggestion. I really like this addition, so feel free to do the PR.

Please, le me know if you can’t or won’t do it, to do it myself, ok?

**Comment by jontelang** [comment]
Cool, I will at least take a look at it perhaps today

**Comment by jontelang** [comment]
Added https://github.com/Juanpe/SkeletonView/pull/11

**Comment by Juanpe** [comment]
It's included in [version 1.0.4](https://github.com/Juanpe/SkeletonView/releases/tag/1.0.4)
Thanks @jontelang

**Comment by jontelang** [comment]
Although it doesn't let you set the filling percent as the release notes said, it sets it to 80% regardless. The addition was just a BOOL that says "do it" or "don't do it".

**Comment by Juanpe** [comment]
Hi @jontelang, you're right, but I think when you create an open source framework you need to do it most customizable as possible. 
So, taking account this, I prefer that the developers can decide the filling percent of the last line too.

**Comment by jontelang** [comment]
Oh I didn't see that you improved upon the PR and added it. I just meant that _I_ didn't do that in my PR. But yes I agree, this is definitely an improvement.
