### ISSUE TITLE
On which view do you call showSkeleton(), etc on?

### ISSUE THREAD

**Issue by daviskoh** [Juanpe/SkeletonView#80]
⚠️ Please fill out this template when filing an issue.

### What did you do?

Tried calling `showSkeleton()` on a subview. Tried calling `showSkeleton()` on the main container view. Tried calling `showSkeleton()` on a different subview.

Tried above for all different animation functions.

I am unsure on what view exactly I am supposed to call `showSkeleton()`, etc on. Is it the view I want the animation on? Is it the container view above the view I want the animation on? I am completely lost as I cannot even get the animation to start / show / etc in any possible way.

NOTE: some container views / subviews are UIStackViews. I am not sure if this completely breaks all logic. I know there is an [issue](https://github.com/Juanpe/SkeletonView/issues/23) open on UIStackviews but this seems unrelated...

This question is more of a documentation / clarification issue.

The docs say:

```
SkeletonView is recursive, so if you want show the skeleton in all skeletonable views, you only need to call the show method in the main container view. For example, with UIViewControllers.
```

I do not understand what "For example, with UIViewControllers." means given that showSkeleton only applies to `UIView`s. 

Is there an order of execution applied to setting `isSkeletonable = true`? For instance, I am simply setting it in the `init()` of my custom views, but do I need to set the value **after** they have been setup w/ constraints and added as a subview? 

Are programmatic views are not supported?

### What did you expect to happen?

For any animation to trigger / start / begin/ show.

### What happened instead?

Nothing happened.

### Steps to reproduce the behavior

Set `.isSkeletonable = true` on UIStackview view.
Set `.isSkeletonable = true` on subview.
Call `showSkeleton()` on UIStackview view

OR

Set `.isSkeletonable = true` on UIStackview view.
Set `.isSkeletonable = true` on subview.
Call `showSkeleton()` on subview

### SkeletonView Environment

**SkeletonView version:** 1.2.1
**Xcode version:** 9.3
**Swift version:** 4.1

**Comment by daviskoh** [comment]
Perhaps it is autolayout that is preventing animation from displaying? Does this library rely on having values for `.frame`?

**Comment by daviskoh** [comment]
I can see from the `print` statements I have added that `recursiveShowSkeleton()` is traversing properly down the subviews until it reaches a subview w/o `. isSkeletonable` set.

There must be a problem w/ rendering...

**Comment by daviskoh** [comment]
I can see that I am getting:

```
(0.0, 0.0, 0.0, 0.0)
```

for `maxBoundsEstimated` in the UIView extension

**Comment by daviskoh** [comment]
Yes. So after I manually added hardcoded `frame` values, the skeletons render. Is this by design? Will autolayout not be supported?

**Comment by daviskoh** [comment]
Actually, even having "successfully" rendered the skeletons, I am bogged down by a ton of breaking autolayout constraints, ones that were previously working w/o breaking.

**Comment by Juanpe** [comment]
Hi @daviskoh, I just release a new version ([1.2.2](https://github.com/Juanpe/SkeletonView/releases/tag/1.2.2)). This version solves problem with `UIStackViews`, could you check if your project works fine using this version?
Thanks

**Comment by daviskoh** [comment]
@Juanpe I will check later today and let you know!

**Comment by daviskoh** [comment]
Sorry. havent had time to check the new version as ive been swamped w/ work. I will just close this for now and open a new issue if i still see this on `1.2.2`.

**Comment by N-ihad** [comment]
why is this closed?
