### ISSUE TITLE
disableUserInteraction() on UIScrollView intercepts all actions, not just scroll

### ISSUE THREAD

**Issue by reececomo** [Juanpe/SkeletonView#86]
### What did you do?

Tapped a custom (non-skeleton) back button on a UITableView

### What did you expect to happen?

The tap to be received

### What happened instead?

isUserInteractionEnabled = false on UIScrollView intercepts all actions, and not just scroll

### Steps to reproduce the behavior

See above

### SkeletonView Environment

**SkeletonView version:** 1.3
**Xcode version:** 9.4
**Swift version:** 4.2

**Comment by Juanpe** [comment]
Solved in your PR 😃
