### ISSUE TITLE
Animated gradient not showing on a view after a modal is dismissed

### ISSUE THREAD

**Issue by adrgrondin** [Juanpe/SkeletonView#88]
### What did you do?

*I present a modal (present modally segue) over an UIViewController with an UIImageView loading with a gradient animated.*

### What did you expect to happen?

*I expected that after the dismissal of the modal the animation will still be gradient animated.*

### What happened instead?

*The loading animation seems to be solid.*  

### Steps to reproduce the behavior

*The animation starts in viewDidLoad() on a UIImageView with imageView.showAnimatedGradientSkeleton(). After viewDidAppear(_:) a modal is presented and then dismissed.
Now the UIImageView have the animation but it is not a gradient animated is seems to be solid as explained.*

### SkeletonView Environment

**SkeletonView version: *1.2.1*
**Xcode version: *9.4.1*
**Swift version: *4.1*

**Comment by mouayyad-taja** [comment]
this also happened with me and i could not solve it

**Comment by Patrez** [comment]
Had same problem, I have fixed it with calling `hideSkeleton` on `viewDidDisappear` and then start the animation again on` viewWillAppear`

**Comment by Dalein** [comment]
Is still no fix for this bug? Only start/stop animation in viewDidDisappear/viewWillAppear?

**Comment by Juanpe** [comment]
Fixed in version 1.8.1. Please update :)
