### ISSUE TITLE
Add More colors

### ISSUE THREAD

**Issue by kak2008** [Juanpe/SkeletonView#9]
I believe in adding few more colors will enhance this project. Let me know if you want me to help you with any contributions.

**Comment by dotWasim** [comment]
I agree with you, this's the first thing I was checking when i saw previews

**Comment by Juanpe** [comment]
Hi @kak2008 and @dotWasim, maybe it's not totally clear in the README file, but  `SkeletonView` features 20 new colors, but you can use **whatever** color you want. 

For example:
```
view.showSkeleton(usingColor: UIColor.red)
view.showSkeleton(usingColor: UIColor(red: 25.0, green: 30.0, blue: 255.0, alpha: 1.0))
```
 or gradient:   
```
let gradient = SkeletonGradient(baseColor: UIColor.gray)
view.showGradientSkeleton(usingGradient: gradient)
```

**Comment by dotWasim** [comment]
thanks, I didn't notice that... I am wondering if the collection view support is going to be available any sooner?

**Comment by Juanpe** [comment]
Yes, Collection view support will be available very soon 🙂
