### ISSUE TITLE
Error using viewForHeaderInSection

### ISSUE THREAD

**Issue by rarias84** [Juanpe/SkeletonView#91]
I'm using custom cell header (UIView or UITableViewHeaderFooterView)

### What did you expect to happen?

Show skeleton in tableview using custom header

### What happened instead?
The error:
Thread 1: Fatal error: Index out of range on 
func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {}

### SkeletonView Environment

**SkeletonView version:**
1.4
**Xcode version:**
Version 9.4.1 (9F2000)
**Swift version:**
4.1

**Comment by sungkim23** [comment]
Same issue, trying to find a workaround on it :/

**Comment by sungkim23** [comment]
Think this doesn't work on table view headers, only cells, i avoided the issue simply adding a validation on the array headers takes values from and doing a array.count > 0, that avoids the index out of range issue, but I think the library in itself doesn't support headers.

**Comment by Juanpe** [comment]
bug fixed in version [1.7](https://github.com/Juanpe/SkeletonView/releases/tag/1.7)
