### ISSUE TITLE
SkeletonView can

### ISSUE THREAD

**Issue by wangrui460** [Juanpe/SkeletonView#92]
⚠️ Please fill out this template when filing an issue.

### What did you do?

*Please replace this with what you did.*

### What did you expect to happen?

*Please replace this with what you expected to happen.*

### What happened instead?

*Please replace this with of what happened instead.*  

### Steps to reproduce the behavior

*Please replace this with the steps to reproduce the behavior.*

### SkeletonView Environment

**SkeletonView version:**
**Xcode version:**
**Swift version:**

**Comment by sungkim23** [comment]
@wangrui460 there's nothing in your bug report
