### ISSUE TITLE
Only see grey background on UITableView

### ISSUE THREAD

**Issue by Fawxy** [Juanpe/SkeletonView#94]
### What did you do?

I have a UITableView that has cells that are defined in XIBs. I am calling `showSkeletonView` on the table view, but all I see is the grey background of the cells.

<img width="400" alt="screen shot 2018-08-20 at 13 25 53" src="https://user-images.githubusercontent.com/9826062/44340247-2e085c80-a47c-11e8-865b-efae15b523c9.png">

If I inspect the view with Xcode, I can see that the other views are there (and appear to be on top but I can't see them in simulator?), but they are not skeletons.

<img width="519" alt="screen shot 2018-08-20 at 13 25 53" src="https://user-images.githubusercontent.com/9826062/44340391-96efd480-a47c-11e8-8a58-8f882f730e0e.png">

My hierarchy for the table goes like this:
```
View Controller
+--View (Skeletonable: Default)
      +--Table View (Skeletonable: Yes)
            +-- Cell
```

And for the cell:
```
Cell
+--Cell Container (Skeletonable: Yes)
    +--Empty View (Skeletonable: No)
    +--View (Skeletonable: Yes)
       +--Stack View (Skeletonable: No)
          +--Stack View (Skeletonable: No)
          |  +--Label (Skeletonable: Yes)
          |  +--Label (Skeletonable: Yes)
          +--Image View (Skeletonable: Yes)
```

I have tried setting everything to skeletonable without any luck. Hopefully these hierarchies make sense...

### What did you expect to happen?

I don't want my cells to set that grey background, It should be white. The labels and the image view should be skeletons. I don't want the grey (hopefully white) cell background to obscure the skeleton views.

### What happened instead?

The table is white, the cell containers are grey, the cell subviews do not get skeletoned, even though the cells appear to be on top I can't see them, just the grey block.

### SkeletonView Environment

**SkeletonView version:** 1.4
**Xcode version:** 9.4.1
**Swift version:** 4.1

**Comment by arn00s** [comment]
Hey @Fawxy , to work as expected, your whole view hierarchy must have the isSkeletonable property set to true.

**Comment by Fawxy** [comment]
As I said I tried changing everything to skeletonable - if I understand it it's everything from the top down needs to be skeletonable? So, if I do this:
```
View Controller
+--View (Skeletonable: Default)
      +--Table View (Skeletonable: Yes)
            +-- Cell
```

```
Cell
+--Cell Container (Skeletonable: Yes)
    +--Empty View (Skeletonable: Yes)
    +--View (Skeletonable: Yes)
       +--Stack View (Skeletonable: Yes)
          +--Stack View (Skeletonable: Yes)
          |  +--Label (Skeletonable: Yes)
          |  +--Label (Skeletonable: Yes)
          +--Image View (Skeletonable: Yes)
```

I get the same result.

**Comment by arn00s** [comment]
Hey @Fawxy ,
What about the Cell ? It should also be skeletonable.
Maybe by [enabling the new debug mode](https://github.com/Juanpe/SkeletonView#-debug) it will be easier for you to identify the issue ?

**Comment by Skornos** [comment]
@Fawxy hey, are you calling `showSkeletonView()` on `viewDidAppear`?

**Comment by Fawxy** [comment]
@Skornos actually on viewWillAppear

**Comment by Juanpe** [comment]
Hi @Fawxy, as @arn00s said, could you [active debug mode](
https://github.com/Juanpe/SkeletonView#-debug) in order to see which hierarchy is using SkeletonView?

**Comment by Fawxy** [comment]
``` ⬇⬇ ☠️ Root view hierarchy with Skeletons ⬇⬇ 

 <UITableView: 0x00007fc9d701de00 | (3) subSkeletons | ☠️ > 
      <ArticleContentView: 0x00007fc9d9832600 | ☠️ > 
      <ArticleContentView: 0x00007fc9d9864a00 | ☠️ > 
      <ArticleContentView: 0x00007fc9da015e00 | ☠️ > ```

I get this result. Why wouldn't the subviews inside ArticleContentView be showing? They are set to skeletonable...

**Comment by Juanpe** [comment]
`SkeletonView` doesn’t find skeletonables views inside `ArticleContentView` view. Maybe you have a view not skeletonable between `ArticleContentView ` and those subviews? Could you give me some code of your project to try to find what is it happening? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fawxy** [comment]
Please find a demo project here: https://github.com/Fawxy/SkeletonViewTest

**Comment by Fawxy** [comment]
Ok I figured this out. My XIB contained a view, so when I converted it to a tableviewcell it embedded that view into the cell. I changed the xib so it contained a cell, made the views skeletonable and it all worked as expected. Thanks for your replies!

**Comment by Juanpe** [comment]
Great! thanks for use `SkeletonView`
