### ISSUE TITLE
Error when try to run the app

### ISSUE THREAD

**Issue by SamboVisal** [Juanpe/SkeletonView#96]
⚠️ Please fill out this template when filing an issue.

### What did you do?

*Run the app.*

### What did you expect to happen?

*Run should be successfully.*

### What happened instead?

*It throws me error in file named "RecursiveProtocol.swift". and it states that "Extension of type 'Array' with constraints cannot have an inheritance clause"*  

### SkeletonView Environment

**SkeletonView version: latest version**
**Xcode version: 9**
**Swift version: 4**

**Comment by bhargavbajani** [comment]
@SamboVisal  Any Solutions ?

**Comment by Juanpe** [comment]
Hi @SamboVisal, which specific swift version do you have?

**Comment by SamboVisal** [comment]
@Juanpe 4.0 sir!
@bhargavbajani not yet

**Comment by JaydeepVora** [comment]
I also facing this issue

**Comment by SamboVisal** [comment]
@JaydeepVora  Have you tried to run in Xcode 10?

**Comment by mtaroco** [comment]
Same problem here, any solution?
I'm not able to run in Xcode 10 yet. 
I'm using Xcode 9.2, Swift version: 4.0

**Comment by Juanpe** [comment]
Hi,

You can install the pod version which you want, so, if you are using swift 4, you can install SkeletonView 1.4, pod 'SkeletonView', '1.4'

**Comment by mtaroco** [comment]
Hi @Juanpe , thanks for your response!
I'm already using SkeletonView version 1.4 :(

**Comment by kakmul** [comment]
i face the same problem man, any solution to this? seems some coding error on the library

**Comment by zainoldin** [comment]
@mtaroco @kakmul i just mentioned the version of pod like:  pod 'SkeletonView', '1.4' and it is working.
Swift versin 4.0
Xcode 10
