### ISSUE TITLE
Skeleton UI doesn't work on a Subclass of UITableViewController or UICollectionViewController

### ISSUE THREAD

**Issue by aonawale** [Juanpe/SkeletonView#97]
⚠️ Please fill out this template when filing an issue.

### What did you do?

I tried to show skeleton UI in a table view of a subclass of UITableViewController class.

### What did you expect to happen?

I expected 3 cells to show up with loading state of the image and label on each cell

### What happened instead?

The table view shows it's own loading UI, animated light gray background, no cell shows up.

### Steps to reproduce the behavior

``` 
class Cell: UITableViewCell {
    private let titleLabel: UILabel = {
        let label = UILabel()
        label.font = UIFont.preferredFont(forTextStyle: .headline)
        label.isSkeletonable = true
        return label
    }()

    private let myImageView: UIImageView = {
        let imageView = UIImageView()
        imageView.isSkeletonable = true
        imageView.contentMode = .scaleAspectFit
        return imageView
    }()

    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        isSkeletonable = true
        accessoryType = .disclosureIndicator

        contentView.isSkeletonable = true
        contentView.addSubview(titleLabel)
        contentView.addSubview(myImageView)

        NSLayoutConstraint.activate([
            ...
        ])
    }
}

class ViewController: UITableViewController {
    var items = [Item]()

    override func viewDidLoad() {
        super.viewDidLoad()
        tableView.isSkeletonable = true
        tableView.register(Cell.self, forCellReuseIdentifier: "Cell")
        tableView.showAnimatedSkeleton()
    }
}

extension ViewController: SkeletonTableViewDataSource {
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: ServiceTableCell.reuseIdentifier, for: indexPath) as! Cell
        return cell
    }

    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return items.count
    }

    func collectionSkeletonView(_ skeletonView: UITableView, cellIdentifierForRowAt indexPath: IndexPath) -> ReusableCellIdentifier {
        return "Cell"
    }

    func collectionSkeletonView(_ skeletonView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 3
    }
}
``` 

### SkeletonView Environment

**SkeletonView version:*1.4*
**Xcode version:*9.4.1*
**Swift version:*4.1*

### Side note
I created a subclass of UIViewController, created a UITableView, added it to my view and make it fill it's bounds. That works as expected except the labels in each cell doesn't show up when the text content is empty.

I also have the same issue subclassing UICollectionViewController; the same solution of adding a collection view to a UIViewController subclass worked as well.

**Comment by saxahan** [comment]
Same here

**Comment by kraisorns** [comment]
Same here :/

**Comment by MervinDelfin** [comment]
same here

**Comment by ChristianSteffens** [comment]
How could this issue be closed - it's a serious bug - if not being solved in the near future, it should at least be mentioned in the documentation?

**Comment by StephanPartzsch** [comment]
Hopefully it gets reopened. I have the **same issue here**!

**Comment by harmittaa** [comment]
Same here still.

**Comment by Juanpe** [comment]
Hi, could you check [this comment](https://github.com/Juanpe/SkeletonView/issues/253#issuecomment-585162334), maybe it could fix our problem.

Let me know, thanks
