### ISSUE TITLE
SkeletonView not being removed from all UITableViewCell's

### ISSUE THREAD

**Issue by Garrett-Benoit** [Juanpe/SkeletonView#98]
⚠️ Please fill out this template when filing an issue.

### What did you do?

When SkeletonView is being removed from a TableView and there is only one cell in the table everything appears fine, however when more cells are added and the table is reloaded, the SkeletonView still appears on the additional cells.

### What did you expect to happen?

When tableView.hideSkeleton() is ran, the SkeletonView is removed from all visible cells.

### What happened instead?

When there were 2 SkeletonView cells visible, and my TableView contained data for 2 or more cells to be displayed, when the SkeletonView was removed and the TableView reloaded -- everything worked fine.

When there were 2 SkeletonView cells visible, and my TableView only contained data for 1 cell, when the SkeletonView was removed and the TableView reloaded -- everything appeared to have worked fine, however when I add additional data to the TableView to display more than 1 cell, the SkeletonView on the additional cells is still visible.

What the SkeletonView looks like:
![simulator screen shot - iphone 8 - 2018-09-14 at 15 34 38](https://user-images.githubusercontent.com/17788960/45573971-f5b62d00-b833-11e8-8ff8-028baf94a107.png)

What the TableView with 1 cell looks like:
![simulator screen shot - iphone 8 - 2018-09-14 at 15 34 43](https://user-images.githubusercontent.com/17788960/45573988-fea6fe80-b833-11e8-9658-26d82cdae202.png)

What the TableView that has 4 more cells added and reloaded looks like:
![simulator screen shot - iphone 8 - 2018-09-14 at 15 35 01](https://user-images.githubusercontent.com/17788960/45573993-01a1ef00-b834-11e8-96b5-da117f7aa565.png)

Scrolled down a bit to show the entire cell from image 3:
![simulator screen shot - iphone 8 - 2018-09-14 at 15 35 14](https://user-images.githubusercontent.com/17788960/45573997-04044900-b834-11e8-8acf-d9ee787f620e.png)

### Steps to reproduce the behavior

1.) Remove SkeletonView with a TableView containing 1 cell
2.) Add additional cells to the TableView
3.) Reload the TableView

### SkeletonView Environment

SkeletonView: v1.4
Xcode: v9.4.1
Swift: v4.1.2

**Comment by osbash** [comment]
I had this issue and fixed it by adding this 

```func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        cell.hideSkeleton()
    }```

**Comment by jeremypiednoel** [comment]
@osbash thanks for the solution.
I added this test before 

```swift
    override func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if cell.isSkeletonActive {
            cell.hideSkeleton()
        }
    }
```

**Comment by ramonvic** [comment]
I had to add this
```swift
public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
...
cell.hideSkeleton()
}
```
Because on `willDisplay`, was removing the skeletons before `hideSkeleton` was called

**Comment by BhavikThummar** [comment]
I also had the same issue and I tried your way @osbash, But I was facing the reuseable issue,

![Simulator Screen Shot - iPhone X - 2019-04-08 at 08 29 59](https://user-images.githubusercontent.com/16632644/55695975-99d21200-59d8-11e9-9b2a-335ef8d63d8f.png)

So I tried your condition in cell class when I set my custom property,
Like this

`class CategoryListingCell: UITableViewCell {
    
    // MARK: - Outlets
    
    @IBOutlet weak var imgIcon: UIImageView!
    
    @IBOutlet weak var lblTitle: UILabel!
    @IBOutlet weak var lblGujaratiTitle: UILabel!
    
    // -----------------------------------------------------------------------------
    
    // MARK: - Class Variables
    
    var category: Category! {
        didSet {
            imgIcon.setImage(with: category.icon)
            
            lblTitle.text = category.titleEnglish
            lblGujaratiTitle.text = category.titleGujarati
        }
    }
    
    // -----------------------------------------------------------------------------
    
    // MARK: - Life Cycle Methods
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
    
    // -----------------------------------------------------------------------------
    
}`

And It gets resolved 😇
